INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Portland', 'Minister - Official Business', 1, 372.00, 372.00, '19-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Minister - Official Business', 1, 276.00, 276.00, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Adelaide', 'Minister - Official Business', 1, 386.00, 386.00, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Minister - Official Business', 1, 442.00, 442.00, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Minister - Official Business', 1, 442.00, 442.00, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Adelaide', 'Minister - Official Business', 1, 386.00, 386.00, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 January 2017', '', '', 'Canberra', 'Minister - Official Business', 1, 273.00, 273.00, '18-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '31 Jan 17 - Melbourne to Canberra', 0, 0, 637.91, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Feb 17 - Canberra to Adelaide', 0, 0, 861.23, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide to Melbourne', 0, 0, 782.40, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne to Canberra', 0, 0, 716.51, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Canberra to Melbourne', 0, 0, 716.51, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '7 Feb 17 - Melbourne to Canberra', 0, 0, 637.91, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Canberra to Sydney', 0, 0, 628.69, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney to Melbourne', 0, 0, 842.36, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Melbourne to Canberra', 0, 0, 422.03, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra to Melbourne', 0, 0, 716.51, '16-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Feb 17 - Melbourne to Sydney', 0, 0, 842.36, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney to Melbourne', 0, 0, 842.36, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Melbourne to Canberra', 0, 0, 751.97, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Canberra to Sydney', 0, 0, 354.03, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '23 Feb 17 - Sydney to Melbourne', 0, 0, 883.94, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Melbourne to Sydney', 0, 0, 883.94, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Sydney to Melbourne', 0, 0, 883.94, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '27 Feb 17 - Melbourne to Canberra', 0, 0, 637.91, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra to Melbourne', 0, 0, 751.97, '02-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '7 Mar 17 - Melbourne to Canberra', 0, 0, 637.91, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '7 Mar 17 - Canberra to Melbourne', 0, 0, 438.57, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Mar 17 - Melbourne to Sydney', 0, 0, 883.94, '09-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Mar 17 - Sydney to Melbourne', 0, 0, 883.94, '09-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Mar 17 - Melbourne to Sydney', 0, 0, 768.76, '10-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Mar 17 - Sydney to Melbourne', 0, 0, 883.94, '10-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Mar 17 - Melbourne to Canberra', 0, 0, 751.97, '14-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Mar 17 - Canberra to Melbourne', 0, 0, 751.97, '14-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne to Canberra', 0, 0, 637.91, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '15 Mar 17 - Canberra to Adelaide', 0, 0, 903.52, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Mar 17 - Adelaide to Melbourne', 0, 0, 821.27, '16-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Melbourne to Canberra', 0, 0, 751.97, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '13 Dec 16 - Canberra to Melbourne', 0, 0, 637.91, '13-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 11 Jan to 10 Feb 17', 0, 0, 940.98, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 26 Jan to 22 Feb 17', 0, 0, 144.99, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 11 Feb to 10 Mar 17', 0, 0, 940.98, '10-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 4 Dec to 7 Dec 16', 0, 0, 40.19, '07-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 11 Dec 16 to 10 Jan 17', 0, 0, 940.98, '11-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 17 Dec to 22 Jan 17', 0, 0, 292.25, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Jan 17 - Melbourne', 0, 0, 136.71, '24-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Jan 17 - Melbourne', 0, 0, 192.57, '24-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '31 Jan 17 - Melbourne', 0, 0, 76.42, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '31 Jan 17 - Canberra', 0, 0, 41.80, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Canberra', 0, 0, 90.39, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Canberra', 0, 0, 57.64, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Canberra', 0, 0, 40.00, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Canberra', 0, 0, 53.71, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Adelaide', 0, 0, 80.40, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Adelaide', 0, 0, 40.00, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 40.00, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 40.00, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 65.50, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 148.03, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 47.16, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 78.60, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Melbourne', 0, 0, 62.70, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Melbourne', 0, 0, 119.20, '03-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Melbourne', 0, 0, 90.39, '03-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Melbourne', 0, 0, 87.76, '03-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Melbourne', 0, 0, 87.77, '03-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Feb 17 - Melbourne', 0, 0, 83.50, '05-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Feb 17 - Melbourne', 0, 0, 88.74, '05-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne', 0, 0, 86.30, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Canberra', 0, 0, 41.80, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Canberra', 0, 0, 40.00, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne', 0, 0, 54.84, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne', 0, 0, 47.10, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne', 0, 0, 92.25, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Feb 17 - Melbourne', 0, 0, 76.42, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Feb 17 - Canberra', 0, 0, 41.80, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Feb 17 - Canberra', 0, 0, 98.25, '08-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Canberra', 0, 0, 40.00, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 72.88, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 45.85, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Melbourne', 0, 0, 71.98, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Melbourne', 0, 0, 86.90, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Canberra', 0, 0, 80.40, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '13 Feb 17 - Canberra', 0, 0, 40.00, '13-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Feb 17 - Canberra', 0, 0, 40.00, '14-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra', 0, 0, 40.00, '16-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Melbourne', 0, 0, 65.32, '16-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Feb 17 - Melbourne', 0, 0, 78.60, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Feb 17 - Melbourne', 0, 0, 78.60, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Feb 17 - Melbourne', 0, 0, 81.66, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Feb 17 - Sydney', 0, 0, 43.80, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Feb 17 - Sydney', 0, 0, 78.60, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Feb 17 - Sydney', 0, 0, 43.60, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 57.64, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Melbourne', 0, 0, 65.32, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Melbourne', 0, 0, 71.18, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Canberra', 0, 0, 41.80, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Canberra', 0, 0, 40.00, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Sydney', 0, 0, 158.03, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Feb 17 - Sydney', 0, 0, 40.00, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Feb 17 - Sydney', 0, 0, 40.00, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Feb 17 - Melbourne', 0, 0, 193.81, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Melbourne', 0, 0, 86.90, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Sydney', 0, 0, 102.05, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Melbourne', 0, 0, 88.90, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Feb 17 - Melbourne', 0, 0, 75.11, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Feb 17 - Canberra', 0, 0, 165.86, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Feb 17 - Canberra', 0, 0, 40.00, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '28 Feb 17 - Canberra', 0, 0, 40.00, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Mar 17 - Canberra', 0, 0, 40.00, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra', 0, 0, 41.92, '02-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Mar 17 - Melbourne', 0, 0, 92.83, '02-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Mar 17 - Melbourne', 0, 0, 83.84, '06-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Mar 17 - Melbourne', 0, 0, 78.60, '06-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Melbourne', 0, 0, 128.93, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Canberra', 0, 0, 41.80, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Canberra', 0, 0, 40.00, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Melbourne', 0, 0, 60.08, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Mar 17 - Melbourne', 0, 0, 62.01, '09-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Mar 17 - Sydney', 0, 0, 67.64, '09-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Mar 17 - Sydney', 0, 0, 65.50, '09-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Mar 17 - Melbourne', 0, 0, 88.90, '09-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Mar 17 - Melbourne', 0, 0, 56.77, '10-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Mar 17 - Sydney', 0, 0, 53.23, '10-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Mar 17 - Sydney', 0, 0, 85.15, '10-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Mar 17 - Melbourne', 0, 0, 95.45, '10-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Mar 17 - Melbourne', 0, 0, 68.56, '14-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Mar 17 - Canberra', 0, 0, 41.80, '14-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Mar 17 - Canberra', 0, 0, 40.00, '14-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Mar 17 - Melbourne', 0, 0, 67.94, '14-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne', 0, 0, 83.09, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne', 0, 0, 55.57, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Canberra', 0, 0, 41.80, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Canberra', 0, 0, 40.00, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Adelaide', 0, 0, 41.80, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Mar 17 - Adelaide', 0, 0, 267.24, '16-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Mar 17 - Adelaide', 0, 0, 40.61, '16-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Mar 17 - Melbourne', 0, 0, 87.70, '16-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Mar 17 - Melbourne', 0, 0, 139.51, '17-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Mar 17 - Melbourne', 0, 0, 157.64, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Mar 17 - Canberra', 0, 0, 80.40, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Mar 17 - Canberra', 0, 0, 73.36, '21-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Mar 17 - Canberra', 0, 0, 40.00, '23-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Mar 17 - Melbourne', 0, 0, 67.94, '23-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Mar 17 - Melbourne', 0, 0, 45.85, '24-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Mar 17 - Melbourne', 0, 0, 86.90, '26-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Mar 17 - Canberra', 0, 0, 168.17, '26-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Mar 17 - Canberra', 0, 0, 40.00, '27-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Mar 17 - Canberra', 0, 0, 75.98, '30-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Mar 17 - Canberra', 0, 0, 78.60, '30-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Mar 17 - Canberra', 0, 0, 40.00, '30-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'Before 1 January 2017', '', '', '', '14 Dec 16 - Sydney', 0, 0, 31.00, '14-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'Before 1 January 2017', '', '', '', '15 Dec 16 - Sydney', 0, 0, 9.90, '15-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'Before 1 January 2017', '', '', '', 'Taxi 29 Aug 16', 0, 0, 96.98, '29-Aug-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'Before 1 January 2017', '', '', '', 'Taxi 1 Sep 16', 0, 0, 88.39, '01-Sep-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 58387.77, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 4770.31, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 206.15, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 23 Jan 17', 0, 0, 23.00, '23-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 392.55, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Staples 28 Jan to 27 Feb 17', 0, 0, 258.30, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 38.75, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 1458.43, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 28 Feb 17', 0, 0, 34.50, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 213.70, '27-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 16.01, '27-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Water refills 22 Dec 16', 0, 0, 52.27, '22-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 9.37, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 55.31, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Jan to 31 Jan 17', 0, 0, -22.73, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 12090.11, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '8,453 Printed items 19 Jan 17', 0, 0, 2564.75, '19-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '10,000 Printed items 23 Jan 17', 0, 0, 5272.73, '23-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '5 Printed items 27 Jan 17', 0, 0, 1000.00, '27-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Feb to 28 Feb 17', 0, 0, -45.45, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Feb to 28 Feb 17', 0, 0, 1818.18, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '15,713 Printed items 14 Nov 16', 0, 0, 9435.50, '14-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '62,000 Printed items 28 Nov 16', 0, 0, 26631.82, '28-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -22.73, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 919.09, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '15 The Australian 2 Jan to 29 Jan 17', 0, 0, 36.82, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 2 Jan to 29 Jan 17', 0, 0, 21.68, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '15 Herald Sun 2 Jan to 29 Jan 17', 0, 0, 20.45, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '14 The Australian Financial Review 2 Jan to 29 Jan 17', 0, 0, 50.91, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '15 The Age 2 Jan to 29 Jan 17', 0, 0, 38.18, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 Herald Sun 4 Feb to 18 Feb 17', 0, 0, 2.73, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 Herald Sun (Sat) 4 Feb to 18 Feb 17', 0, 0, 6.55, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 The Australian Financial Review 4 Feb to 18 Feb 17', 0, 0, 10.91, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 The Saturday Age 4 Feb to 18 Feb 17', 0, 0, 10.36, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 The Weekend Australian 4 Feb to 18 Feb 17', 0, 0, 9.55, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Australian 1 Nov to 19 Nov 16', 0, 0, 4.91, '19-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Weekend Australian 1 Nov to 19 Nov 16', 0, 0, 6.36, '19-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Australian Financial Review 1 Nov to 19 Nov 16', 0, 0, 14.55, '19-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 Herald Sun 1 Nov to 19 Nov 16', 0, 0, 2.73, '19-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 Herald Sun (Sat) 1 Nov to 19 Nov 16', 0, 0, 4.36, '19-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Saturday Age 1 Nov to 19 Nov 16', 0, 0, 3.45, '19-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Age 1 Nov to 19 Nov 16', 0, 0, 5.09, '19-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '15 The Australian 5 Dec 16 to 1 Jan 17', 0, 0, 36.82, '05-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '15 The Age 5 Dec 16 to 1 Jan 17', 0, 0, 38.18, '05-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '15 Herald Sun 5 Dec 16 to 1 Jan 17', 0, 0, 20.45, '05-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '16 The Australian Financial Review 5 Dec 16 to 1 Jan 17', 0, 0, 58.18, '05-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 5 Dec 16 to 1 Jan 17', 0, 0, 21.68, '05-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Australian Financial Review 10 Dec to 28 Dec 16', 0, 0, 14.55, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 Herald Sun 10 Dec to 28 Dec 16', 0, 0, 2.73, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Age 10 Dec to 28 Dec 16', 0, 0, 6.91, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Age 10 Dec to 28 Dec 16', 0, 0, 5.09, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Australian 10 Dec to 28 Dec 16', 0, 0, 6.36, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Australian 10 Dec to 28 Dec 16', 0, 0, 4.91, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 Herald Sun 10 Dec to 28 Dec 16', 0, 0, 6.55, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Saturday Age 10 Dec to 28 Dec 16', 0, 0, 3.45, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Saturday Age 31 Dec 16 to 21 Jan 17', 0, 0, 13.82, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Weekend Australian 31 Dec 16 to 21 Jan 17', 0, 0, 12.73, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Weekend Financial Review 31 Dec 16 to 21 Jan 17', 0, 0, 10.91, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 Herald Sun 31 Dec 16 to 21 Jan 17', 0, 0, 5.45, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 Herald Sun (Sat) 31 Dec 16 to 21 Jan 17', 0, 0, 8.73, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Australian 31 Dec 16 to 21 Jan 17', 0, 0, 9.82, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Australian Financial Review 31 Dec 16 to 21 Jan 17', 0, 0, 10.91, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Age 31 Dec 16 to 21 Jan 17', 0, 0, 5.09, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Jan 17', 0, 0, 60.92, '26-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Jan 17', 0, 0, 239.57, '26-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 26 Jan 17', 0, 0, 37.59, '26-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Feb 17', 0, 0, 307.45, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Feb 17', 0, 0, 37.95, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 26 Feb 17', 0, 0, 38.32, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 26 Dec 16', 0, 0, 32.27, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 26 Dec 16', 0, 0, 290.64, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 26 Dec 16', 0, 0, 37.59, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Josh Frydenberg', 'Member', 'Kooyong', 'Victoria', 'Liberal Party of Australia', 'Overseas Travel', 'Overseas Travel', 'Before 1 January 2017', '', '', '', '', 0, 0, 3837.30, '01-Jan-1900', '', 'OS Ministerial - Accommodation and meals');
