INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Minister - Official Business', 1, 276.00, 276.00, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Minister - Official Business', 1, 442.00, 442.00, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Jan 17 - Melbourne to Canberra', 0, 0, 689.24, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Jan 17 - Canberra to Melbourne', 0, 0, 637.91, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Jan 17 - Melbourne to Sydney', 0, 0, 756.04, '20-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Jan 17 - Sydney to Melbourne', 0, 0, 756.04, '20-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '25 Jan 17 - Melbourne to Adelaide', 0, 0, 411.14, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '25 Jan 17 - Adelaide to Melbourne', 0, 0, 411.14, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '31 Jan 17 - Melbourne to Canberra', 0, 0, 637.91, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Feb 17 - Canberra to Sydney', 0, 0, 389.54, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Sydney to Melbourne', 0, 0, 756.04, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne to Canberra', 0, 0, 637.91, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Canberra to Sydney', 0, 0, 121.30, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney to Melbourne', 0, 0, 842.36, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Melbourne to Canberra', 0, 0, 245.30, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra to Melbourne', 0, 0, 637.91, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Melbourne to Sydney', 0, 0, 768.76, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney to Melbourne', 0, 0, 768.76, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Melbourne to Canberra', 0, 0, 149.76, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Mar 17 - Melbourne to Sydney', 0, 0, 768.76, '10-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Mar 17 - Sydney to Melbourne', 0, 0, 768.76, '10-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '6 Dec 16 - Melbourne to Sydney', 0, 0, 756.04, '06-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '6 Dec 16 - Sydney to Melbourne', 0, 0, 756.04, '06-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '12 Dec 16 - Melbourne to Canberra', 0, 0, 485.82, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 7 Jan to 6 Feb 17', 0, 0, 932.34, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 10 Jan 17', 0, 0, 68.67, '10-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 23 Jan 17', 0, 0, 71.78, '23-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 7 Feb to 6 Mar 17', 0, 0, 932.34, '06-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 7 Dec to 22 Dec 16', 0, 0, 183.45, '22-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 7 Dec 16 to 6 Jan 17', 0, 0, 932.34, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 25 Dec 16 to 7 Jan 17', 0, 0, 201.43, '25-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Jan 17 - Melbourne', 0, 0, 69.01, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Jan 17 - Canberra', 0, 0, 41.80, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Jan 17 - Canberra', 0, 0, 40.00, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Jan 17 - Melbourne', 0, 0, 60.08, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Jan 17 - Melbourne', 0, 0, 71.18, '20-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Jan 17 - Sydney', 0, 0, 50.00, '20-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Jan 17 - Sydney', 0, 0, 166.37, '20-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Jan 17 - Melbourne', 0, 0, 99.49, '20-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '25 Jan 17 - Melbourne', 0, 0, 49.36, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '25 Jan 17 - Adelaide', 0, 0, 182.58, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '25 Jan 17 - Adelaide', 0, 0, 49.78, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '25 Jan 17 - Adelaide', 0, 0, 57.64, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '25 Jan 17 - Melbourne', 0, 0, 123.07, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '31 Jan 17 - Melbourne', 0, 0, 82.11, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '31 Jan 17 - Canberra', 0, 0, 41.80, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Canberra', 0, 0, 40.00, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Sydney', 0, 0, 121.83, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Melbourne', 0, 0, 82.80, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne', 0, 0, 84.73, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Canberra', 0, 0, 41.80, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Canberra', 0, 0, 40.00, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 54.54, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 113.97, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 40.00, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 41.92, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Melbourne', 0, 0, 59.22, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Melbourne', 0, 0, 86.90, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Canberra', 0, 0, 80.40, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra', 0, 0, 40.00, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Melbourne', 0, 0, 59.22, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Melbourne', 0, 0, 66.39, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 57.16, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 47.16, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Melbourne', 0, 0, 64.46, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '25 Feb 17 - Melbourne', 0, 0, 214.07, '25-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Melbourne', 0, 0, 86.90, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Canberra', 0, 0, 80.40, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra', 0, 0, 40.00, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Mar 17 - Melbourne', 0, 0, 62.70, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Mar 17 - Melbourne', 0, 0, 251.31, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Melbourne', 0, 0, 80.35, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Canberra', 0, 0, 41.80, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Canberra', 0, 0, 40.00, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Melbourne', 0, 0, 168.81, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Mar 17 - Melbourne', 0, 0, 68.56, '10-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Mar 17 - Sydney', 0, 0, 58.47, '10-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Mar 17 - Sydney', 0, 0, 113.97, '10-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Mar 17 - Melbourne', 0, 0, 67.94, '10-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 January 2017', '', '', '', 'Taxi 19 Mar 17', 0, 0, 48.53, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 44174.58, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 3519.86, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 5.62, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 251.12, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 7.71, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 149.85, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Feb to 28 Feb 17', 0, 0, 960.00, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 104.83, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 13.00, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 16', 0, 0, 120.34, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 4.07, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 63.50, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 3304.39, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '3,350 Printed items 10 Jan 17', 0, 0, 1820.00, '10-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Feb to 28 Feb 17', 0, 0, 541.53, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 10 Jul 16', 0, 0, 103.44, '10-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 31 Jul 16', 0, 0, 37.50, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 10 Aug 16', 0, 0, 100.86, '10-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 10 Sep 16', 0, 0, 102.53, '10-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 10 Oct 16', 0, 0, 101.95, '10-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 1 Nov 16', 0, 0, 103.00, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 10 Nov 16', 0, 0, 102.11, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '10,654 Printed items 10 Nov 16', 0, 0, 2154.00, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 14 Nov 16', 0, 0, 100.00, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 16 Nov 16', 0, 0, 250.00, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 30 Nov 16', 0, 0, 344.15, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 10424.92, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '17,067 Printed items 5 Dec 16', 0, 0, 4038.00, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 10 Dec 16', 0, 0, 103.95, '10-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 18 Dec 16', 0, 0, 575.57, '18-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 20 Dec 16', 0, 0, 4068.00, '20-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 22 Dec 16', 0, 0, 695.00, '22-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 news+ Full Access and 7 day 6 Jan 16', 0, 0, 50.91, '06-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian, 4 The Weekend Australian and 1 The Australian (digital) 6 Jan to 31 Jan 16', 0, 0, 54.55, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian, 4 The Weekend Australian and 1 The Australian (digital) 22 Jul to 18 Aug 16', 0, 0, 54.55, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 Herald Sun (digital) 22 Jul 16', 0, 0, 47.27, '22-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Age (digital) 31 Jul 16', 0, 0, 34.15, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian, 4 The Weekend Australian and 1 The Australian (digital) 19 Aug to 15 Sep 16', 0, 0, 54.55, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 Herald Sun (digital) 19 Aug 16', 0, 0, 47.27, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Age (digital) 31 Aug 16', 0, 0, 33.94, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian, 4 The Weekend Australian and 1 The Australian (digital) 16 Sep to 13 Oct 16', 0, 0, 54.55, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 Herald Sun (digital) 16 Sep 16', 0, 0, 47.27, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Age (digital) 30 Sep 16', 0, 0, 33.94, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 news+ Full Access and 7 day 14 Oct 16', 0, 0, 50.91, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian, 4 The Weekend Australian and 1 The Australian (digital) 14 Oct to 10 Nov 16', 0, 0, 54.55, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Age (digital) 31 Oct 16', 0, 0, 33.94, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 news+ Full Access and 7 day 11 Nov 16', 0, 0, 50.91, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian, 4 The Weekend Australian and 1 The Australian (digital) 11 Nov to 8 Dec 16', 0, 0, 54.55, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Age (digital) 30 Nov 16', 0, 0, 33.94, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian, 4 The Weekend Australian and 1 The Australian (digital) 9 Dec 16 to 5 Jan 17', 0, 0, 54.55, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 news+ Full Access and 7 day 9 Dec 16', 0, 0, 50.91, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Age (digital) 31 Dec 16', 0, 0, 33.94, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Jan 17', 0, 0, 127.97, '26-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Jan 17', 0, 0, 319.65, '26-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 26 Jan 17', 0, 0, 32.14, '26-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Feb 17', 0, 0, 163.76, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Feb 17', 0, 0, 367.93, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 26 Feb 17', 0, 0, 32.14, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 23 Aug 16', 0, 0, 30.00, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 26 Dec 16', 0, 0, 121.06, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 26 Dec 16', 0, 0, 402.74, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Kelly O''Dwyer', 'Member', 'Higgins', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 26 Dec 16', 0, 0, 32.14, '26-Dec-2016', '');
