INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 276.00, 276.00, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Brisbane', 'Human Rights', 1, 411.00, 411.00, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Economics - Reps', 2, 276.00, 552.00, '06-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '27 Jan 17 - Perth to Melbourne', 0, 0, 1452.55, '27-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '27 Jan 17 - Melbourne to Hobart', 0, 0, 0, '27-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '30 Jan 17 - Hobart to Melbourne', 0, 0, 640.54, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Feb 17 - Melbourne to Sydney', 0, 0, 842.36, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Sydney to Adelaide', 0, 0, 970.71, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide to Perth', 0, 0, 1496.11, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '5 Feb 17 - Perth to Melbourne', 0, 0, 1513.55, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '5 Feb 17 - Melbourne to Canberra', 0, 0, 0, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Feb 17 - Canberra to Brisbane', 0, 0, 799.62, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Brisbane to Perth', 0, 0, 1913.32, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Perth to Canberra', 0, 0, 1685.91, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra to Perth', 0, 0, 1685.91, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '18 Feb 17 - Perth to Darwin', 0, 0, 1466.52, '18-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Darwin to Perth', 0, 0, 1466.52, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '23 Feb 17 - Perth to Sydney', 0, 0, 1945.04, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '24 Feb 17 - Sydney to Canberra', 0, 0, 354.03, '24-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra to Melbourne', 0, 0, 1513.55, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Mar 17 - Melbourne to Perth', 0, 0, 0, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Mar 17 - Perth to Canberra', 0, 0, 1769.77, '06-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '8 Mar 17 - Canberra to Perth', 0, 0, 1769.77, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Perth to Sydney', 0, 0, 1513.18, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Sydney to Canberra', 0, 0, 0, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Jan 17 - Perth', 0, 0, 46.55, '27-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Jan 17 - Hobart', 0, 0, 42.00, '27-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Jan 17 - Hobart', 0, 0, 40.00, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Jan 17 - Hobart', 0, 0, 65.50, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Jan 17 - Melbourne', 0, 0, 61.84, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Melbourne', 0, 0, 54.26, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Sydney', 0, 0, 57.86, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Sydney', 0, 0, 40.00, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Sydney', 0, 0, 40.00, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 41.80, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 40.00, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Perth', 0, 0, 68.12, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Feb 17 - Perth', 0, 0, 78.60, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Feb 17 - Brisbane', 0, 0, 40.00, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Brisbane', 0, 0, 40.00, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Brisbane', 0, 0, 45.30, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Perth', 0, 0, 44.54, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Perth', 0, 0, 78.60, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Perth', 0, 0, 47.86, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '18 Feb 17 - Perth', 0, 0, 78.60, '18-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '18 Feb 17 - Darwin', 0, 0, 78.60, '18-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '18 Feb 17 - Darwin', 0, 0, 78.60, '18-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '18 Feb 17 - Darwin', 0, 0, 78.60, '18-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Darwin', 0, 0, 40.00, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Perth', 0, 0, 53.71, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Feb 17 - Perth', 0, 0, 58.95, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Feb 17 - Sydney', 0, 0, 50.00, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Feb 17 - Sydney', 0, 0, 40.00, '24-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Feb 17 - Sydney', 0, 0, 78.60, '24-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Feb 17 - Canberra', 0, 0, 41.80, '24-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra', 0, 0, 40.00, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra', 0, 0, 40.00, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra', 0, 0, 40.00, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Perth', 0, 0, 51.09, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Mar 17 - Perth', 0, 0, 78.60, '06-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Mar 17 - Canberra', 0, 0, 41.80, '06-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Canberra', 0, 0, 40.00, '07-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Canberra', 0, 0, 40.00, '07-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Canberra', 0, 0, 40.00, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Canberra', 0, 0, 40.00, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Canberra', 0, 0, 40.00, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Perth', 0, 0, 45.85, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Mar 17 - Perth', 0, 0, 78.60, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Mar 17 - Canberra', 0, 0, 47.16, '23-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Mar 17 - Canberra', 0, 0, 40.00, '24-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '1 Feb 17', 0, 0, 9.88, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '19 Feb 17', 0, 0, 14.39, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '19 Feb 17', 0, 0, 14.39, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 31182.52, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 3465.28, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 210.90, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 60.42, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 127.60, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 696.15, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 362.75, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 100.05, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 16', 0, 0, 635.31, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 65.84, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 24.94, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 11 Jan 17', 0, 0, 132.40, '11-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 25 Jan 17', 0, 0, 132.40, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Printing 25 Jan 17', 0, 0, 220.00, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 5062 rental 1 Apr 17 to 31 Mar 18', 0, 0, 112.73, '01-Apr-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 25 Nov 16', 0, 0, 847.35, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 7 Dec 16', 0, 0, 804.05, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 7 Dec 16', 0, 0, 631.82, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 9 Dec 16', 0, 0, 847.35, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '500 Printed items 9 Dec 16', 0, 0, 2580.00, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 14 Dec 16', 0, 0, 132.40, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 16 Dec 16', 0, 0, 227.26, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1,010 Printed items 16 Dec 16', 0, 0, 3330.00, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 28 Dec 16', 0, 0, 132.40, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Weekend Financial Review 3 Jan to 31 Jan 17', 0, 0, 14.55, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '21 The Australian 3 Jan to 31 Jan 17', 0, 0, 51.55, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '21 The Australian Financial Review 3 Jan to 31 Jan 17', 0, 0, 76.36, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Weekend Australian 3 Jan to 31 Jan 17', 0, 0, 12.73, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Sunday Times 3 Jan to 31 Jan 17', 0, 0, 9.82, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '21 The West Australian 3 Jan to 31 Jan 17', 0, 0, 28.64, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Weekend West 3 Jan to 31 Jan 17', 0, 0, 9.82, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian 1 Feb to 28 Feb 17', 0, 0, 52.09, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Sunday Times 1 Feb to 28 Feb 17', 0, 0, 9.82, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 The Weekend Financial Review 1 Feb to 28 Feb 17', 0, 0, 10.91, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 The Weekend Australian 1 Feb to 28 Feb 17', 0, 0, 9.55, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The West Australian 1 Feb to 28 Feb 17', 0, 0, 27.27, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 The Weekend West 1 Feb to 28 Feb 17', 0, 0, 7.36, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian Financial Review 1 Feb to 28 Feb 17', 0, 0, 72.73, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The Australian Financial Review 6 Feb to 5 Mar 17', 0, 0, 40.00, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The Australian 6 Feb to 5 Mar 17', 0, 0, 29.18, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 6 Feb to 5 Mar 17', 0, 0, 2.00, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The West Australian 6 Feb to 5 Mar 17', 0, 0, 65.00, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 28 Nov 16 to 1 Jan 17', 0, 0, 0.73, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The West Australian 28 Nov 16 to 1 Jan 17', 0, 0, 23.64, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Australian 28 Nov 16 to 1 Jan 17', 0, 0, 9.82, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Australian Financial Review 28 Nov 16 to 1 Jan 17', 0, 0, 14.55, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '17 The West Australian 1 Dec to 23 Dec 16', 0, 0, 23.18, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Weekend Australian 1 Dec to 23 Dec 16', 0, 0, 9.55, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Weekend Financial Review 1 Dec to 23 Dec 16', 0, 0, 10.91, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Sunday Times 1 Dec to 23 Dec 16', 0, 0, 7.36, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '17 The Australian 1 Dec to 23 Dec 16', 0, 0, 41.73, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '17 The Australian Financial Review 1 Dec to 23 Dec 16', 0, 0, 61.82, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Weekend West 1 Dec to 23 Dec 16', 0, 0, 7.36, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 1 Jan 17', 0, 0, 318.00, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 1 Jan 17', 0, 0, 31.77, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 1 Feb 17', 0, 0, 238.42, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 1 Feb 17', 0, 0, 31.77, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 4 Mar 17', 0, 0, 292.32, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 4 Mar 17', 0, 0, 32.50, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '27 Jan 17 - Perth to Melbourne', 0, 0, 1452.55, '27-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '27 Jan 17 - Melbourne to Hobart', 0, 0, 0, '27-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '30 Jan 17 - Hobart to Melbourne', 0, 0, 640.54, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '1 Feb 17 - Melbourne to Perth', 0, 0, 1981.39, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '18 Feb 17 - Perth to Darwin', 0, 0, 1466.52, '18-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Darwin to Perth', 0, 0, 1466.52, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Melbourne', 0, 0, 72.94, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Perth', 0, 0, 49.17, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Madeleine King', 'Member', 'Brand', 'Western Australia', 'Australian Labor Party', 'Family Travel Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '29 Mar 17 - Perth', 0, 0, 46.55, '29-Mar-2017', '');
