INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Minister - Official Business', 3, 276.00, 828.00, '30-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 276.00, 276.00, '02-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Minister - Official Business', 1, 276.00, 276.00, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 2, 276.00, 552.00, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Townsville', 'Minister - Official Business', 1, 372.00, 372.00, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Minister - Official Business', 1, 442.00, 442.00, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Albury', 'Minister - Official Business', 1, 372.00, 372.00, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Shepparton', 'Minister - Official Business', 1, 372.00, 372.00, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 4957.08, '01-Jan-1900', 'OS Ministerial - Accommodation and meals', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 430.00, '01-Jan-1900', 'OS Ministerial - Equipment allowance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 29967.97, '01-Jan-1900', 'OS Ministerial - Fares', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 7080.66, '01-Jan-1900', 'OS Ministerial - Ground transport', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 315.00, '01-Jan-1900', 'OS Ministerial - Minor official expense advance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 254.00, '01-Jan-1900', 'OS Ministerial - Passport costs', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 33.90, '01-Jan-1900', 'OS Ministerial - Related travel expenses', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 169.10, '01-Jan-1900', 'OS Ministerial - Travel advance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 53.54, '01-Jan-1900', 'OS Ministerial - Accommodation and meals', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 430.00, '01-Jan-1900', 'OS Ministerial - Equipment allowance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 49128.51, '01-Jan-1900', 'OS Ministerial - Fares', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 1083.48, '01-Jan-1900', 'OS Ministerial - Medical costs', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 504.00, '01-Jan-1900', 'OS Ministerial - Minor official expense advance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 45.00, '01-Jan-1900', 'OS Ministerial - Passport costs', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 501.92, '01-Jan-1900', 'OS Ministerial - Travel advance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Jan 17 - Brisbane to Sydney', 0, 0, 816.37, '14-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Jan 17 - Sydney to Brisbane', 0, 0, 816.37, '14-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Jan 17 - Brisbane to Rockhampton', 0, 0, 314.98, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Feb 17 - Canberra to Brisbane', 0, 0, 799.62, '03-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Feb 17 - Brisbane to Mackay', 0, 0, 421.00, '03-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '5 Feb 17 - Rockhampton to Brisbane', 0, 0, 1114.60, '05-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Brisbane to Canberra', 0, 0, 0, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Feb 17 - Canberra to Brisbane', 0, 0, 1109.07, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Feb 17 - Brisbane to Rockhampton', 0, 0, 0, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Rockhampton to Brisbane', 0, 0, 916.26, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Brisbane to Canberra', 0, 0, 0, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Feb 17 - Canberra to Brisbane', 0, 0, 916.26, '17-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Feb 17 - Brisbane to Rockhampton', 0, 0, 0, '17-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '18 Feb 17 - Rockhampton to Brisbane', 0, 0, 320.89, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Feb 17 - Brisbane to Townsville', 0, 0, 898.60, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Feb 17 - Townsville to Brisbane', 0, 0, 1031.09, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Feb 17 - Brisbane to Sydney', 0, 0, 0, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney to Albury', 0, 0, 430.69, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '23 Feb 17 - Melbourne to Brisbane', 0, 0, 1128.52, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '25 Feb 17 - Brisbane to Rockhampton', 0, 0, 320.89, '25-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '28 Feb 17 - Rockhampton to Brisbane', 0, 0, 1154.53, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '28 Feb 17 - Brisbane to Canberra', 0, 0, 0, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Mar 17 - Canberra to Sydney', 0, 0, 659.37, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Mar 17 - Sydney to Canberra', 0, 0, 354.03, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra to Brisbane', 0, 0, 1154.53, '03-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Mar 17 - Brisbane to Rockhampton', 0, 0, 0, '03-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Mar 17 - Rockhampton to Brisbane', 0, 0, 1199.92, '06-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Mar 17 - Brisbane to Sydney', 0, 0, 0, '06-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '13 Dec 16 - Canberra to Brisbane', 0, 0, 916.26, '13-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '13 Dec 16 - Brisbane to Rockhampton', 0, 0, 0, '13-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 3 Jan to 25 Jan 17', 0, 0, 701.55, '25-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 5 Jan to 4 Feb 17', 0, 0, 2597.15, '04-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel interest fee 7 Jan to 22 Jan 17', 0, 0, 1.02, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 3 Feb to 18 Feb 17', 0, 0, 408.63, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 5 Feb to 4 Mar 17', 0, 0, 2597.15, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 25 Oct to 22 Nov 16', 0, 0, 621.81, '22-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Admin charge 31 Oct 16', 0, 0, 0.34, '31-Oct-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 5 Nov to 4 Dec 16', 0, 0, 2597.15, '04-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 5 Dec 16 to 4 Jan 17', 0, 0, 2597.15, '05-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 15 Dec to 23 Dec 16', 0, 0, 274.95, '23-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Jan 17 - Sydney', 0, 0, 88.60, '14-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Jan 17 - Sydney', 0, 0, 78.60, '14-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Jan 17 - Sydney', 0, 0, 100.95, '14-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Jan 17 - Brisbane', 0, 0, 88.65, '14-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Jan 17 - Sydney', 0, 0, 43.80, '16-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Jan 17 - Brisbane', 0, 0, 84.20, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Canberra', 0, 0, 40.00, '03-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Townsville', 0, 0, 43.50, '03-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Feb 17 - Brisbane', 0, 0, 83.00, '05-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Brisbane', 0, 0, 44.30, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Canberra', 0, 0, 41.80, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Canberra', 0, 0, 80.40, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Canberra', 0, 0, 40.00, '17-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '18 Feb 17 - Brisbane', 0, 0, 88.60, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Feb 17 - Brisbane', 0, 0, 78.60, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 55.98, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 91.70, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Feb 17 - Brisbane', 0, 0, 92.70, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Feb 17 - Brisbane', 0, 0, 65.50, '24-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Feb 17 - Brisbane', 0, 0, 98.25, '24-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '25 Feb 17 - Brisbane', 0, 0, 83.50, '25-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '25 Feb 17 - Brisbane', 0, 0, 78.60, '25-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '28 Feb 17 - Canberra', 0, 0, 41.80, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Mar 17 - Sydney', 0, 0, 50.00, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Mar 17 - Sydney', 0, 0, 40.00, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra', 0, 0, 40.00, '03-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Mar 17 - Sydney', 0, 0, 62.92, '06-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Mar 17 - Sydney', 0, 0, 132.48, '06-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Sydney', 0, 0, 47.16, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Sydney', 0, 0, 209.12, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Canberra', 0, 0, 41.80, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Mar 17 - Canberra', 0, 0, 40.00, '16-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Mar 17 - Canberra', 0, 0, 80.40, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Mar 17 - Canberra', 0, 0, 40.00, '24-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Mar 17 - Canberra', 0, 0, 80.40, '26-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Mar 17 - Canberra', 0, 0, 40.00, '30-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'Before 1 January 2017', '', '', '', '6 Dec 16 - Townsville', 0, 0, 358.28, '06-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'COMCAR', 'Before 1 January 2017', '', '', '', '11 Dec 16 - Townsville', 0, 0, 61.48, '11-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Other Car Costs', 'From 1 January 2017', '', '', '', 'Townsville 19 Feb to 20 Feb 17', 0, 0, 267.61, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 23077.52, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 4020.16, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 181.15, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 47.63, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 1.66, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 17.86, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 86.88, '27-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 3.57, '27-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 2.21, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 48.66, '28-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 28 Jan 17', 0, 0, 300.00, '28-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 30 Jan 17', 0, 0, 181.82, '30-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Feb to 28 Feb 17', 0, 0, 14.23, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 737 rental 1 Apr 17 to 31 Mar 18', 0, 0, 271.82, '01-Apr-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Refund of printed item 17 Aug 16', 0, 0, -1343.64, '17-Aug-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 545.45, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -13.64, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 Financial Times (digital) 1 Jan to 31 Jan 17', 0, 0, 36.00, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Wall Street Journal (digital) 8 Jan to 7 Feb 17', 0, 0, 40.83, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The New York Times (digital) 11 Jan to 7 Feb 17', 0, 0, 10.00, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 Townsville Bulletin (digital) 12 Jan to 8 Feb 17', 0, 0, 14.55, '08-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Cairns Post (digital) 13 Jan to 9 Feb 17', 0, 0, 14.55, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Australian (digital), 20 The Australian and 4 The Weekend Australian 16 Jan to 12 Feb 17', 0, 0, 54.55, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Morning Bulletin (digital) and 24 The Morning Bulletin 17 Jan to 14 Feb 17', 0, 0, 36.36, '14-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Sydney Morning Herald (digital) 23 Jan to 22 Feb 17', 0, 0, 22.93, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 NT News (digital) 24 Jan to 20 Feb 17', 0, 0, 14.55, '20-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '8 Central Queensland News 27 Jan to 26 Feb 17', 0, 0, 11.64, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Observer (Sat) 27 Jan to 26 Feb 17', 0, 0, 6.18, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 27 Jan to 26 Feb 17', 0, 0, 12.98, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Courier Mail 27 Jan to 26 Feb 17', 0, 0, 27.27, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Observer 27 Jan to 26 Feb 17', 0, 0, 30.91, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Courier Mail (Sat)27 Jan to 26 Feb 17', 0, 0, 9.09, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Saturday Paper 27 Jan to 26 Feb 17', 0, 0, 12.73, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 Financial Times (digital) 1 Feb to 28 Feb 17', 0, 0, 36.00, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The New York Times (digital) 8 Feb to 7 Mar 17', 0, 0, 11.00, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Wall Street Journal (digital) 8 Feb to 7 Mar 17', 0, 0, 35.54, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 Townsville Bulletin (digital) 9 Feb to 8 Mar 17', 0, 0, 14.55, '08-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Cairns Post (digital) 10 Feb to 9 Mar 17', 0, 0, 14.55, '09-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Australian (digital), 20 The Australian and 4 The Weekend Australian 13 Feb to 12 Mar 17', 0, 0, 54.55, '12-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Morning Bulletin (digital) and 24 The Morning Bulletin 14 Feb to 14 Mar 17', 0, 0, 36.36, '14-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 NT News (digital) 21 Feb to 20 Mar 17', 0, 0, 14.55, '20-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Sydney Morning Herald (digital) 23 Feb to 22 Mar 17', 0, 0, 22.93, '22-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 Financial Times (digital) 1 Mar to 31 Mar 17', 0, 0, 36.00, '31-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '8 Central Queensland News 31 Oct to 27 Nov 16', 0, 0, 10.91, '27-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 31 Oct to 27 Nov 16', 0, 0, 12.98, '27-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Saturday Paper 31 Oct to 27 Nov 16', 0, 0, 12.73, '27-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Observer (Sat) 31 Oct to 27 Nov 16', 0, 0, 6.18, '27-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Courier Mail (Sat) 31 Oct to 27 Nov 16', 0, 0, 9.09, '27-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Observer 31 Oct to 27 Nov 16', 0, 0, 27.27, '27-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Courier Mail 31 Oct to 27 Nov 16', 0, 0, 27.27, '27-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Courier Mail (Sat) 28 Nov to 25 Dec 16', 0, 0, 9.09, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Observer 28 Nov to 25 Dec 16', 0, 0, 27.27, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Observer (Sat) 28 Nov to 25 Dec 16', 0, 0, 6.18, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Saturday Paper 28 Nov to 25 Dec 16', 0, 0, 12.73, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '8 Central Queensland News 28 Nov to 25 Dec 16', 0, 0, 10.91, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 28 Nov to 25 Dec 16', 0, 0, 12.98, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Courier Mail 28 Nov to 25 Dec 16', 0, 0, 27.27, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The West Australian (digital) 30 Nov 16 to 29 Nov 17', 0, 0, 261.82, '30-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Wall Street Journal (digital) 8 Dec 16 to 7 Dec 17', 0, 0, 40.06, '08-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The New York Times (digital) 14 Dec 16 to 10 Jan 17', 0, 0, 11.00, '14-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 Townsville Bulletin (digital) 15 Dec 16 to 11 Jan 17', 0, 0, 14.55, '15-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Cairns Post (digital) 16 Dec 16 to 12 Jan 17', 0, 0, 14.55, '16-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Australian (digital), 20 The Australian and 4 The Weekend Australian 19 Dec 16 to 15 Jan 17', 0, 0, 54.55, '19-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Morning Bulletin (digital) and 24 The Morning Bulletin 20 Dec 16 to 17 Jan 17', 0, 0, 36.36, '20-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 The Sydney Morning Herald (digital) 23 Dec 16 to 22 Jan 17', 0, 0, 22.93, '23-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '5 The Courier Mail (Sat) 26 Dec 16 to 29 Jan 17', 0, 0, 11.36, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '5 The Saturday Paper 26 Dec 16 to 29 Jan 17', 0, 0, 15.91, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 26 Dec 16 to 29 Jan 17', 0, 0, 15.77, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '8 Central Queensland News 26 Dec 16 to 29 Jan 17', 0, 0, 11.64, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '5 The Observer (Sat) 26 Dec 16 to 29 Jan 17', 0, 0, 7.73, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '25 The Observer 26 Dec 16 to 29 Jan 17', 0, 0, 37.73, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '25 The Courier Mail 26 Dec 16 to 29 Jan 17', 0, 0, 34.09, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 NT News (digital) 27 Dec 16 to 23 Jan 17', 0, 0, 14.55, '27-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Jan 17', 0, 0, 932.78, '21-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Jan 17', 0, 0, 32.86, '21-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Feb 17', 0, 0, 942.43, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Feb 17', 0, 0, 31.77, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Mar 17', 0, 0, 846.25, '21-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Mar 17', 0, 0, 31.77, '21-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 21 Dec 16', 0, 0, 426.65, '21-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Matthew Canavan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 21 Dec 16', 0, 0, 32.14, '21-Dec-2016', '', '');
