INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Geraldton', 'Electorate Business', 1, 329.00, 329.00, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Geraldton', 'Electorate Business', 1, 329.00, 329.00, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Geraldton', 'Electorate Business', 2, 329.00, 658.00, '26-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Carnarvon', 'Electorate Business', 1, 305.00, 305.00, '03-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Jurien Bay', 'Electorate Business', 1, 268.00, 268.00, '04-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Northern Australia', 1, 276.00, 276.00, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Port Hedland', 'Electorate Business', 1, 414.00, 414.00, '20-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Geraldton', 'Electorate Business', 1, 329.00, 329.00, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Geraldton', 'Electorate Business', 2, 329.00, 658.00, '24-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Senate Estimates', 4, 276.00, 1104.00, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Broome', 'Electorate Business', 1, 414.00, 414.00, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Geraldton', 'Electorate Business', 1, 329.00, 329.00, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Geraldton', 'Electorate Business', 1, 329.00, 329.00, '11-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Broome', 'Electorate Business', 1, 414.00, 414.00, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 January 2017', '', '', 'Geraldton', 'Electorate Business', 4, 329.00, 1316.00, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Jan 17 - Perth to Geraldton', 0, 0, 300.16, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '18 Jan 17 - Geraldton to Perth', 0, 0, 300.16, '18-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '25 Jan 17 - Perth to Geraldton', 0, 0, 270.01, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '28 Jan 17 - Geraldton to Perth', 0, 0, 270.01, '28-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Perth to Broome', 0, 0, 720.26, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Broome to Perth', 0, 0, 720.26, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Feb 17 - Perth to Carnarvon', 0, 0, 449.90, '03-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '4 Feb 17 - Carnarvon to Perth', 0, 0, 494.89, '04-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Perth to Canberra', 0, 0, 1685.91, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Feb 17 - Canberra to Perth', 0, 0, 1685.91, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Perth to Canberra', 0, 0, 1685.91, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Feb 17 - Canberra to Perth', 0, 0, 1685.91, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Feb 17 - Perth to Karratha', 0, 0, 615.03, '20-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Port Hedland to Perth', 0, 0, 991.63, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Perth to Geraldton', 0, 0, 331.42, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '23 Feb 17 - Geraldton to Perth', 0, 0, 270.01, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Perth to Canberra', 0, 0, 1769.77, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra to Melbourne', 0, 0, 2355.99, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Mar 17 - Melbourne to Perth', 0, 0, 0, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Mar 17 - Perth to Broome', 0, 0, 0, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Mar 17 - Broome to Perth', 0, 0, 748.62, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '8 Mar 17 - Perth to Geraldton', 0, 0, 331.42, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Mar 17 - Geraldton to Perth', 0, 0, 331.42, '09-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '15 Mar 17 - Perth to Broome', 0, 0, 748.62, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Mar 17 - Broome to Perth', 0, 0, 748.62, '16-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Mar 17 - Melbourne to Canberra', 0, 0, 751.97, '20-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '2 Dec 16 - Canberra to Sydney', 0, 0, 1679.45, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '2 Dec 16 - Sydney to Perth', 0, 0, 0, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '4 Dec 16 - Perth to Broome', 0, 0, 450.16, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '5 Dec 16 - Broome to Perth', 0, 0, 713.65, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '8 Dec 16 - Karratha to Perth', 0, 0, 603.10, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '14 Dec 16 - Perth to Geraldton', 0, 0, 304.13, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '19 Dec 16 - Perth to Port Hedland', 0, 0, 942.72, '19-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '19 Dec 16 - Port Hedland to Perth', 0, 0, 605.95, '19-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Charter', 'Electorate', 'From 1 January 2017', '', '', '', 'Carnarvon 3 Feb to 4 Feb 17', 0, 0, 91.77, '04-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Charter', 'Electorate', 'From 1 January 2017', '', '', '', 'Perth to Geraldton 4 Mar 17', 0, 0, 3380.00, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Charter', 'Electorate', 'From 1 January 2017', '', '', '', 'Geraldton to Perth 4 Mar 17', 0, 0, 0, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Charter', 'Electorate', 'Before 1 January 2017', '', '', '', 'Perth to Carnarvon 12 Aug 16', 0, 0, -880.00, '12-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Charter', 'Electorate', 'Before 1 January 2017', '', '', '', 'Carnarvon to Perth 12 Aug 16', 0, 0, 0, '12-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Charter', 'Electorate', 'Before 1 January 2017', '', '', '', 'Perth to Merredin 13 Dec 16', 0, 0, 2046.36, '13-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Charter', 'Electorate', 'Before 1 January 2017', '', '', '', 'Merredin to Perth 13 Dec 16', 0, 0, 0, '13-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Charter', 'Electorate', 'Before 1 January 2017', '', '', '', 'Port Hedland 19 Dec 16', 0, 0, 214.31, '19-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 17 Jan to 16 Feb 17', 0, 0, 857.22, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', '4WD Lease 20 Jan to 19 Feb 17', 0, 0, 934.66, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', '4WD Fuel 25 Jan 17', 0, 0, 63.35, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', '4WD Fuel 28 Jan to 31 Jan 17', 0, 0, 64.88, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 4 Feb to 24 Feb 17', 0, 0, 203.30, '24-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 17 Feb to 16 Mar 17', 0, 0, 857.22, '16-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', '4WD Lease 20 Feb to 19 Mar 17', 0, 0, 934.66, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 4 Dec to 16 Dec 16', 0, 0, 241.95, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 17 Dec 16 to 16 Jan 17', 0, 0, 857.22, '17-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', '4WD Lease 20 Dec 16 to 19 Jan 17', 0, 0, 934.66, '20-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 29 Dec 16', 0, 0, 158.59, '29-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Jan 17 - Perth', 0, 0, 42.62, '17-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '18 Jan 17 - Perth', 0, 0, 45.24, '18-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Perth', 0, 0, 43.23, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Perth', 0, 0, 62.27, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Perth', 0, 0, 44.54, '03-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Feb 17 - Perth', 0, 0, 78.60, '04-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Perth', 0, 0, 44.54, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Feb 17 - Perth', 0, 0, 43.23, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Perth', 0, 0, 78.60, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Feb 17 - Perth', 0, 0, 47.16, '20-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Perth', 0, 0, 45.24, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Perth', 0, 0, 50.48, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Feb 17 - Perth', 0, 0, 78.60, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Perth', 0, 0, 78.60, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Mar 17 - Canberra', 0, 0, 40.00, '01-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra', 0, 0, 40.00, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Perth', 0, 0, 49.17, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Perth', 0, 0, 47.16, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Mar 17 - Perth', 0, 0, 40.00, '09-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Perth', 0, 0, 44.54, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Mar 17 - Perth', 0, 0, 62.27, '16-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Mar 17 - Melbourne', 0, 0, 81.66, '20-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Mar 17 - Canberra', 0, 0, 40.61, '24-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Mar 17 - Perth', 0, 0, 58.34, '24-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Mar 17 - Perth', 0, 0, 78.60, '26-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 January 2017', '', '', '', 'Geraldton 4 Mar 17', 0, 0, 117.52, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'Before 1 January 2017', '', '', '', 'Kununurra 5 Oct to 7 Oct 16', 0, 0, 204.26, '07-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'Before 1 January 2017', '', '', '', 'Karratha 7 Dec to 8 Dec 16', 0, 0, 98.38, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'Before 1 January 2017', '', '', '', 'Port Hedland 19 Dec 16', 0, 0, 214.31, '19-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 43858.55, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 3108.17, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 1225.06, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Jan to 31 Jan 17', 0, 0, 1768.29, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Jan to 23 Feb 17', 0, 0, 0.26, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Jan to 23 Feb 17', 0, 0, 10.96, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 646.87, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Feb to 28 Feb 17', 0, 0, 1967.03, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Portable and attractive items 1 Feb to 28 Feb 17', 0, 0, 275.95, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Sep to 23 Dec 16', 0, 0, 1.37, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Sep to 23 Dec 16', 0, 0, 992.25, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Nov to 23 Dec 16', 0, 0, 0.95, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Nov to 23 Dec 16', 0, 0, 0.05, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 16', 0, 0, 517.00, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 0.19, '24-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 1.25, '24-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 10.21, '24-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 0.20, '24-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 4801.32, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Feb to 28 Feb 17', 0, 0, 1819.48, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Feb to 28 Feb 17', 0, 0, -22.73, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'e-material 1 Feb 17', 0, 0, 139.39, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '12,000 Personalised letterhead stationery 17 Feb 17', 0, 0, 1336.36, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Web-services 21 Feb 17 to 20 Feb 18', 0, 0, 904.55, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 23 Feb 17', 0, 0, 280.00, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 1856 rental 1 Apr 17 to 31 Mar 18', 0, 0, 47.27, '01-Apr-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 1 Jun 16', 0, 0, 9.09, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 29 Jun 16', 0, 0, 7.27, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 2 Aug 16', 0, 0, 8.00, '02-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 27200.60, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -11.36, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 1 Dec 16', 0, 0, 150.00, '01-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 31 Dec 16', 0, 0, 528.56, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The Sandpaper 1 Jan to 31 Dec 17', 0, 0, 22.73, '31-Dec-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '9 The Geraldton Guardian 3 Jan to 31 Jan 17', 0, 0, 11.45, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 Pilbara News 3 Jan to 31 Jan 17', 0, 0, 6.18, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 North West Telegraph 3 Jan to 31 Jan 17', 0, 0, 6.18, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 Farm Weekly 3 Jan to 31 Jan 17', 0, 0, 13.82, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 Broome Advertiser 3 Jan to 31 Jan 17', 0, 0, 5.82, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 6 Oct 16 to 31 Aug 17', 0, 0, 28.60, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '26 The Muddy Waters 6 Oct 16 to 31 Aug 17', 0, 0, 65.00, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Refund of publications 13 Oct 16', 0, 0, -49.98, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '5 Cloudstreet 13 Oct 16', 0, 0, 90.86, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 Australia''s West 13 Oct 16', 0, 0, 40.91, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '1 Kin: A Real People''s History of Our Nation 13 Oct 16', 0, 0, 27.26, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '5 Farm Weekly 2 Dec to 31 Dec 16', 0, 0, 17.27, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 North West Telegraph 2 Dec to 31 Dec 16', 0, 0, 6.18, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 Broome Advertiser 2 Dec to 31 Dec 16', 0, 0, 5.82, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 Pilbara News 2 Dec to 31 Dec 16', 0, 0, 6.18, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '9 The Geraldton Guardian 2 Dec to 31 Dec 16', 0, 0, 11.45, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 1 Jan 17', 0, 0, 512.51, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 1 Jan 17', 0, 0, 79.90, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 1 Feb 17', 0, 0, 508.74, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 1 Feb 17', 0, 0, 65.00, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 4 Mar 17', 0, 0, 545.88, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 4 Mar 17', 0, 0, 65.36, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 14 Jan 17', 0, 0, 31.77, '14-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 15 Jan 17', 0, 0, 54.45, '15-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 14 Feb 17', 0, 0, 31.77, '14-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 15 Feb 17', 0, 0, 54.45, '15-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 14 Mar 17', 0, 0, 31.77, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 15 Mar 17', 0, 0, 45.41, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '25 Jan 17 - Perth to Geraldton', 0, 0, 270.01, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '28 Jan 17 - Geraldton to Perth', 0, 0, 270.01, '28-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '14 Feb 17 - Perth to Canberra', 0, 0, 1685.91, '14-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Melissa Price', 'Member', 'Durack', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '19 Feb 17 - Canberra to Perth', 0, 0, 1685.91, '19-Feb-2017', '');
