INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Shadow Minister - Official Business', 1, 134.00, 134.00, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '13-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 1, 276.00, 276.00, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Adelaide', 'Shadow Minister - Official Business', 1, 362.00, 362.00, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '20-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '30 Jan 17 - Melbourne to Sydney', 0, 0, 842.36, '30-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '30 Jan 17 - Sydney to Avalon Airport', 0, 0, 208.18, '30-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne to Canberra', 0, 0, 637.91, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Feb 17 - Canberra to Sydney', 0, 0, 628.69, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney to Avalon Airport', 0, 0, 344.55, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '13 Feb 17 - Melbourne to Canberra', 0, 0, 637.91, '13-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra to Melbourne', 0, 0, 245.30, '16-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Melbourne to Sydney', 0, 0, 883.94, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney to Melbourne', 0, 0, 883.94, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Melbourne to Canberra', 0, 0, 637.91, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Canberra to Sydney', 0, 0, 354.03, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Sydney to Melbourne', 0, 0, 768.76, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '27 Feb 17 - Melbourne to Canberra', 0, 0, 637.91, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '27 Feb 17 - Canberra to Melbourne', 0, 0, 751.97, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Mar 17 - Melbourne to Canberra', 0, 0, 637.91, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra to Melbourne', 0, 0, 637.91, '02-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '4 Mar 17 - Melbourne to Sydney', 0, 0, 1232.44, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '4 Mar 17 - Sydney to Canberra', 0, 0, 0, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '4 Mar 17 - Canberra to Melbourne', 0, 0, 438.57, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '7 Mar 17 - Melbourne to Adelaide', 0, 0, 821.27, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '8 Mar 17 - Adelaide to Melbourne', 0, 0, 821.27, '08-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne to Canberra', 0, 0, 751.97, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '15 Mar 17 - Canberra to Sydney', 0, 0, 554.99, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '15 Mar 17 - Sydney to Melbourne', 0, 0, 768.76, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Mar 17 - Melbourne to Canberra', 0, 0, 637.91, '20-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '23 Mar 17 - Canberra to Melbourne', 0, 0, 751.97, '23-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '8 Dec 16 - Melbourne to Sydney', 0, 0, 756.04, '08-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '8 Dec 16 - Sydney to Melbourne', 0, 0, 814.95, '08-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '12 Dec 16 - Melbourne to Sydney', 0, 0, 756.04, '12-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '13 Dec 16 - Sydney to Canberra', 0, 0, 121.30, '13-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '13 Dec 16 - Canberra to Melbourne', 0, 0, 637.91, '13-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 5 Jan to 4 Feb 17', 0, 0, 1081.43, '04-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 24 Jan to 23 Feb 17', 0, 0, 905.00, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 3 Feb to 24 Feb 17', 0, 0, 143.81, '24-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 5 Feb to 4 Mar 17', 0, 0, 1081.43, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 5 Dec 16 to 4 Jan 17', 0, 0, 1081.43, '05-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 7 Dec to 15 Dec 16', 0, 0, 126.54, '15-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 24 Dec 16 to 23 Jan 17', 0, 0, 905.00, '24-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 30 Dec 16 to 28 Jan 17', 0, 0, 133.99, '30-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Jan 17 - Melbourne', 0, 0, 182.09, '30-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Jan 17 - Sydney', 0, 0, 50.00, '30-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Jan 17 - Sydney', 0, 0, 40.00, '30-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '6 Feb 17 - Melbourne', 0, 0, 170.30, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Feb 17 - Sydney', 0, 0, 50.00, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 57.31, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 40.00, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 40.00, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 40.00, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney', 0, 0, 66.81, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '13 Feb 17 - Melbourne', 0, 0, 189.95, '13-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Melbourne', 0, 0, 159.20, '16-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Melbourne', 0, 0, 163.75, '17-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Melbourne', 0, 0, 54.26, '17-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Darwin', 0, 0, 40.00, '17-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Darwin', 0, 0, 78.60, '17-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Melbourne', 0, 0, 166.37, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 146.37, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 72.05, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 115.90, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Melbourne', 0, 0, 147.41, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Melbourne', 0, 0, 162.44, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Canberra', 0, 0, 41.80, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Sydney', 0, 0, 56.20, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Sydney', 0, 0, 40.00, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Melbourne', 0, 0, 146.10, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Feb 17 - Melbourne', 0, 0, 178.16, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Feb 17 - Melbourne', 0, 0, 144.79, '27-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Mar 17 - Melbourne', 0, 0, 161.13, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Mar 17 - Canberra', 0, 0, 91.70, '01-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Mar 17 - Melbourne', 0, 0, 168.37, '02-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Mar 17 - Melbourne', 0, 0, 141.48, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Mar 17 - Canberra', 0, 0, 80.40, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Mar 17 - Melbourne', 0, 0, 139.13, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Melbourne', 0, 0, 150.65, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '7 Mar 17 - Adelaide', 0, 0, 41.80, '07-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Adelaide', 0, 0, 153.27, '08-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Adelaide', 0, 0, 70.74, '08-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '8 Mar 17 - Melbourne', 0, 0, 168.37, '08-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne', 0, 0, 171.61, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Canberra', 0, 0, 102.67, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Sydney', 0, 0, 50.00, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Sydney', 0, 0, 78.60, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Sydney', 0, 0, 42.70, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Sydney', 0, 0, 42.70, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Sydney', 0, 0, 40.00, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne', 0, 0, 142.17, '15-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Mar 17 - Melbourne', 0, 0, 336.06, '16-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Mar 17 - Melbourne', 0, 0, 368.11, '16-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Mar 17 - Melbourne', 0, 0, 179.47, '20-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Mar 17 - Canberra', 0, 0, 40.00, '23-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '23 Mar 17 - Melbourne', 0, 0, 146.10, '23-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '27 Mar 17 - Melbourne', 0, 0, 168.99, '27-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '30 Jan 17', 0, 0, 50.92, '30-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '10 Feb 17', 0, 0, 48.62, '10-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '18 Feb 17', 0, 0, 61.19, '18-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 25891.68, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 10810.87, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 203.67, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Jan to 31 Jan 17', 0, 0, 1467.51, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Jan to 23 Feb 17', 0, 0, 0.55, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Jan to 23 Feb 17', 0, 0, 0.32, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 21 Feb 17', 0, 0, 46.00, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 23 Mar 17', 0, 0, 23.00, '23-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Software reimbursement 2016/17', 0, 0, 1500.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Nov to 23 Dec 16', 0, 0, 18.02, '23-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Nov to 23 Dec 16', 0, 0, 1.94, '23-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 1.80, '24-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 0.25, '24-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 1818.18, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution late payment fee Jan 17', 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Jan to 31 Jan 17', 0, 0, -45.45, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-services 1 Apr to 31 Jul 16', 0, 0, 708.00, '31-Jul-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 31 Jul 16', 0, 0, 300.79, '31-Jul-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-services 7 Sep 16', 0, 0, 164.70, '07-Sep-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-services 9 Sep 16', 0, 0, 202.50, '09-Sep-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 31 Oct 16', 0, 0, 252.53, '31-Oct-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 4816.82, '30-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Nov to 30 Nov 16', 0, 0, -90.91, '30-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution late payment fee Nov 16', 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 30 Nov 16', 0, 0, 299.71, '30-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -28.05, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution late payment fee Dec 16', 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 95.73, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 2 Jan to 29 Jan 17', 0, 0, 17.42, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '18 The Australian Financial Review 2 Jan to 29 Jan 17', 0, 0, 65.45, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '19 Herald Sun 2 Jan to 29 Jan 17', 0, 0, 25.91, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '19 The Age 2 Jan to 29 Jan 17', 0, 0, 48.36, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '19 The Australian 2 Jan to 29 Jan 17', 0, 0, 46.64, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '19 The Geelong Advertiser 2 Jan to 29 Jan 17', 0, 0, 25.91, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 30 Jan to 26 Feb 17', 0, 0, 17.82, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '15 The Australian 30 Jan to 26 Feb 17', 0, 0, 40.91, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 Herald Sun 30 Jan to 26 Feb 17', 0, 0, 27.27, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Age 30 Jan to 26 Feb 17', 0, 0, 50.91, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian Financial Review 30 Jan to 26 Feb 17', 0, 0, 72.73, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '5 The Australian 30 Jan to 26 Feb 17', 0, 0, 12.27, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Geelong Advertiser 30 Jan to 26 Feb 17', 0, 0, 27.27, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 Herald Sun 1 Jun to 28 Jun 15', 0, 0, 25.45, '28-Jun-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Age 1 Jun to 28 Jun 15', 0, 0, 45.45, '28-Jun-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian 1 Jun to 28 Jun 15', 0, 0, 45.45, '28-Jun-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Geelong Advertiser 1 Jun to 28 Jun 15', 0, 0, 25.45, '28-Jun-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 1 Jun to 28 Jun 15', 0, 0, 17.82, '28-Jun-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian Financial Review 1 Jun to 28 Jun 15', 0, 0, 69.09, '28-Jun-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 Herald Sun 28 Nov 16 to 1 Jan 17', 0, 0, 25.91, '28-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 The Geelong Advertiser 28 Nov 16 to 1 Jan 17', 0, 0, 25.91, '28-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 The Australian Financial Review 28 Nov 16 to 1 Jan 17', 0, 0, 69.09, '28-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 The Age 28 Nov 16 to 1 Jan 17', 0, 0, 48.36, '28-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 28 Nov 16 to 1 Jan 17', 0, 0, 15.35, '28-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 The Australian 28 Nov 16 to 1 Jan 17', 0, 0, 46.64, '28-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Jan 17', 0, 0, 238.88, '26-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 26 Jan 17', 0, 0, 32.86, '26-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 26 Feb 17', 0, 0, 307.05, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 26 Feb 17', 0, 0, 32.14, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 26 Dec 16', 0, 0, 427.82, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 26 Dec 16', 0, 0, 32.14, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 1 Jan 17', 0, 0, 45.41, '01-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 8 Jan 17', 0, 0, 63.55, '08-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 1 Feb 17', 0, 0, 45.41, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 8 Feb 17', 0, 0, 63.55, '08-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 4 Mar 17', 0, 0, 45.41, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 9 Mar 17', 0, 0, 63.55, '09-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes, Type)
VALUES ('Richard Marles', 'Member', 'Corio', 'Victoria', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'Before 1 January 2017', '', '', '', '', 0, 0, 807.60, '01-Jan-1900', '', 'OS Official - Accommodation and meals');
