INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '08-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '15-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 1, 273.00, 0, 273.00, '18-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 Feb 16 - Melbourne to Canberra', 0, 0, 0, 686.29, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Feb 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '04-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '8 Feb 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '08-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '11 Feb 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Feb 16 - Perth to Canberra', 0, 0, 0, 1623.59, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '25 Feb 16 - Canberra to Melbourne', 0, 0, 0, 217.51, '25-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '29 Feb 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '3 Mar 16 - Canberra to Melbourne', 0, 0, 0, 217.51, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '15 Mar 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '15-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '18 Mar 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '18-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '24 Mar 16 - Melbourne to Sydney', 0, 0, 0, 780.82, '24-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '24 Mar 16 - Sydney to Melbourne', 0, 0, 0, 780.82, '24-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '5 Apr 16 - Melbourne to Sydney', 0, 0, 0, 780.82, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 Apr 16 - Sydney to Melbourne', 0, 0, 0, 780.82, '06-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '18 Apr 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '18-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '19 Apr 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '19-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '2 May 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2016', '', '', '', '23 Nov 15 - Melbourne to Canberra', 0, 0, 0, 217.51, '23-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2016', '', '', '', '26 Nov 15 - Canberra to Melbourne', 0, 0, 0, 405.05, '26-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2016', '', '', '', '4 Dec 15 - Canberra to Melbourne', 0, 0, 0, 405.05, '04-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2016', '', '', '', '17 Dec 15 - Melbourne to Sydney', 0, 0, 0, 441.43, '17-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2016', '', '', '', '18 Dec 15 - Sydney to Melbourne', 0, 0, 0, 745.89, '18-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 Feb 16 - Melbourne', 0, 0, 0, 63.77, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 Feb 16 - Melbourne', 0, 0, 0, 46.12, '04-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '8 Feb 16 - Melbourne', 0, 0, 0, 54.15, '08-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '11 Feb 16 - Melbourne', 0, 0, 0, 44.81, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Feb 16 - Melbourne', 0, 0, 0, 56.60, '25-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '29 Feb 16 - Melbourne', 0, 0, 0, 65.08, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '3 Mar 16 - Melbourne', 0, 0, 0, 64.46, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '15 Mar 16 - Melbourne', 0, 0, 0, 59.84, '15-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '18 Mar 16 - Melbourne', 0, 0, 0, 59.22, '18-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '24 Mar 16 - Melbourne', 0, 0, 0, 68.56, '24-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '24 Mar 16 - Sydney', 0, 0, 0, 49.70, '24-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '24 Mar 16 - Sydney', 0, 0, 0, 65.50, '24-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '24 Mar 16 - Melbourne', 0, 0, 0, 55.29, '24-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '5 Apr 16 - Melbourne', 0, 0, 0, 65.08, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '5 Apr 16 - Sydney', 0, 0, 0, 49.70, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '5 Apr 16 - Sydney', 0, 0, 0, 40.00, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 Apr 16 - Sydney', 0, 0, 0, 40.00, '06-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 Apr 16 - Melbourne', 0, 0, 0, 53.98, '06-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '18 Apr 16 - Melbourne', 0, 0, 0, 63.35, '18-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Apr 16 - Melbourne', 0, 0, 0, 50.05, '19-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '2 May 16 - Melbourne', 0, 0, 0, 45.43, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 May 16 - Melbourne', 0, 0, 0, 57.91, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '3 Dec 15 - Canberra', 0, 0, 0, -40.00, '03-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '4 Dec 15 - Canberra', 0, 0, 0, -40.00, '04-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '17 Dec 15 - Sydney', 0, 0, 0, 40.00, '17-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '18 Dec 15 - Sydney', 0, 0, 0, 44.70, '18-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '18 Dec 15 - Melbourne', 0, 0, 0, 81.49, '18-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '15 Mar 16', 0, 0, 0, 26.94, '15-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '16 Mar 16', 0, 0, 0, 8.07, '16-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '5 Apr 16', 0, 0, 0, 12.38, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '5 Apr 16', 0, 0, 0, 17.26, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '5 Apr 16', 0, 0, 0, 14.00, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '27 Apr 16', 0, 0, 0, 10.93, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'Before 1 January 2016', '', '', '', '17 Dec 15', 0, 0, 0, 44.50, '17-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'Before 1 January 2016', '', '', '', '18 Dec 15', 0, 0, 0, 7.77, '18-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 66047.26, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 10037.24, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 16', 0, 0, 0, 985.44, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 154.85, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 3.77, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 274.30, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 5.50, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Mar to 1 Apr 16', 0, 0, 0, 0.68, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Mar to 31 Mar 16', 0, 0, 0, 15.31, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Mar to 27 May 16', 0, 0, 0, 483.15, '27-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Mar to 27 May 16', 0, 0, 0, 42.46, '27-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Apr to 30 Apr 16', 0, 0, 0, 464.36, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 7 Sep 13 to 30 Jun 14', 0, 0, 0, -956.74, '07-Sep-2013', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 14 to 30 Jun 15', 0, 0, 0, -812.48, '01-Jul-2014', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 15 to 31 Mar 16', 0, 0, 0, -1476.25, '01-Jul-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Software reimbursement 2015/16', 0, 0, 0, 1500.00, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Software reimbursement 2015/16', 0, 0, 0, 924.55, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'General office consumables 22 Nov 15', 0, 0, 0, 22.87, '22-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Nov 15 to 27 Jan 16', 0, 0, 0, 444.47, '28-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Nov 15 to 27 Jan 16', 0, 0, 0, 5.38, '28-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 15', 0, 0, 0, 261.49, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Jan to 31 Jan 16', 0, 0, 0, 909.09, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Jan to 31 Jan 16', 0, 0, 0, -22.73, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Jan 16', 0, 0, 0, 15.00, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 1 Jan 16', 0, 0, 0, 564.08, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Web-design 15 Jan 16', 0, 0, 0, 640.00, '15-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Web-design 21 Jan 16', 0, 0, 0, 625.00, '21-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '3,000 Printed items 29 Jan 16', 0, 0, 0, 571.00, '29-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 29 Jan 16', 0, 0, 0, 114.75, '29-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 30 Jan 16', 0, 0, 0, 640.07, '30-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Feb to 29 Feb 16', 0, 0, 0, 5.91, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Feb 16', 0, 0, 0, 15.00, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 1 Feb 16', 0, 0, 0, 19.91, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 15 Feb 16', 0, 0, 0, 2008.80, '15-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '100,000 Personalised letterhead stationery 23 Feb 16', 0, 0, 0, 3420.00, '23-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 29 Feb 16', 0, 0, 0, 67.50, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '85,000 Printed items 29 Feb 16', 0, 0, 0, 3040.00, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 29 Feb 16', 0, 0, 0, 115.21, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Mar to 31 Mar 16', 0, 0, 0, 28036.49, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 3 Mar 16', 0, 0, 0, 3120.00, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 11 Mar 16', 0, 0, 0, 60.00, '11-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 31 Mar 16', 0, 0, 0, 11.84, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'PO Box 5295 rental 1 Apr 16 to 31 Mar 17', 0, 0, 0, 164.55, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Apr to 30 Apr 16', 0, 0, 0, 1113.55, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Apr to 30 Apr 16', 0, 0, 0, -22.73, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Apr to 30 Apr 16', 0, 0, 0, -112.15, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '5 Printed items 12 Apr 16', 0, 0, 0, 130.00, '12-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 28 Apr 16', 0, 0, 0, 695.00, '28-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 May to 31 May 16', 0, 0, 0, 28350.75, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 May to 31 May 16', 0, 0, 0, -68.18, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '60,000 Postal vote applications 11 May 16', 0, 0, 0, 16383.00, '11-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '4 Printed items 12 May 16', 0, 0, 0, 102.00, '12-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '62,000 Printed items 13 May 16', 0, 0, 0, 5640.00, '13-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1,000 Printed items 23 May 16', 0, 0, 0, 240.00, '23-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '3 Printed items 25 May 16', 0, 0, 0, 88.00, '25-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '62,000 Printed items 25 May 16', 0, 0, 0, 10705.00, '25-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Printing 16 Oct 15', 0, 0, 0, 33.75, '16-Oct-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1,500 Personalised letterhead stationery 16 Oct 15', 0, 0, 0, 700.00, '16-Oct-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '3,000 Printed items 29 Oct 15', 0, 0, 0, 923.00, '29-Oct-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Web-design 25 Nov 15', 0, 0, 0, 640.00, '25-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '62,000 Printed items 27 Nov 15', 0, 0, 0, 6850.00, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Printing 27 Nov 15', 0, 0, 0, 438.75, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '62,000 Printed items 27 Nov 15', 0, 0, 0, 7075.00, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Printing 27 Nov 15', 0, 0, 0, 179.96, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'e-material 30 Nov 15', 0, 0, 0, 301.68, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 1 Dec to 31 Dec 15', 0, 0, 0, 13592.23, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'General office consumables 1 Dec to 31 Dec 15', 0, 0, 0, 6.27, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 14 Dec 15', 0, 0, 0, 5843.00, '14-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Printing 16 Dec 15', 0, 0, 0, 1359.09, '16-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 21 Dec 15', 0, 0, 0, 375.00, '21-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 4 Jan to 31 Jan 16', 0, 0, 0, 10.91, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 4 Jan to 31 Jan 16', 0, 0, 0, 12.73, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Australian 4 Jan to 31 Jan 16', 0, 0, 0, 12.73, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 4 Jan to 31 Jan 16', 0, 0, 0, 7.55, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Economist 5 Jan to 26 Jan 16', 0, 0, 0, 40.00, '26-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 5 Jan to 26 Jan 16', 0, 0, 0, 2.27, '26-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Atlantic 5 Jan to 26 Jan 16', 0, 0, 0, 17.73, '26-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Saturday Age 1 Feb to 28 Feb 16', 0, 0, 0, 12.73, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 1 Feb to 28 Feb 16', 0, 0, 0, 10.91, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Australian 1 Feb to 28 Feb 16', 0, 0, 0, 12.73, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 1 Feb to 28 Feb 16', 0, 0, 0, 7.55, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Economist 2 Feb to 23 Feb 16', 0, 0, 0, 40.00, '23-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Atlantic 2 Feb to 23 Feb 16', 0, 0, 0, 17.73, '23-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Monthly 2 Feb to 23 Feb 16', 0, 0, 0, 10.86, '23-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '5 The Age 29 Feb to 3 Apr 16', 0, 0, 0, 15.91, '03-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '5 The Age 29 Feb to 3 Apr 16', 0, 0, 0, 13.64, '03-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '5 The Australian 29 Feb to 3 Apr 16', 0, 0, 0, 15.91, '03-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 29 Feb to 3 Apr 16', 0, 0, 0, 8.45, '03-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '5 The Economist 1 Mar to 1 Apr 16', 0, 0, 0, 50.00, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 1 Mar to 1 Apr 16', 0, 0, 0, 2.27, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Atlantic 1 Mar to 1 Apr 16', 0, 0, 0, 17.73, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '2 The Monthly 1 Mar to 1 Apr 16', 0, 0, 0, 21.73, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 4 Apr to 1 May 16', 0, 0, 0, 12.73, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Australian 4 Apr to 1 May 16', 0, 0, 0, 12.73, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 4 Apr to 1 May 16', 0, 0, 0, 10.91, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 4 Apr to 1 May 16', 0, 0, 0, 7.55, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Economist 5 Apr to 27 Apr 16', 0, 0, 0, 40.00, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 5 Apr to 27 Apr 16', 0, 0, 0, 2.27, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Atlantic 5 Apr to 27 Apr 16', 0, 0, 0, 17.73, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Economist 3 May to 24 May 16', 0, 0, 0, 40.00, '24-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Monthly 3 May to 24 May 16', 0, 0, 0, 10.86, '24-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 30 May to 26 Jun 16', 0, 0, 0, 10.91, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 30 May to 26 Jun 16', 0, 0, 0, 12.73, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Australian 30 May to 26 Jun 16', 0, 0, 0, 12.73, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 30 May to 26 Jun 16', 0, 0, 0, 7.55, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Age 3 Aug to 30 Aug 15', 0, 0, 0, 10.91, '30-Aug-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Age 3 Aug to 30 Aug 15', 0, 0, 0, 12.73, '30-Aug-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Australian 3 Aug to 30 Aug 15', 0, 0, 0, 12.00, '30-Aug-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 3 Aug to 30 Aug 15', 0, 0, 0, 7.18, '30-Aug-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Australian 2 Nov to 29 Nov 15', 0, 0, 0, 12.73, '29-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Age 2 Nov to 29 Nov 15', 0, 0, 0, 12.73, '29-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Age 2 Nov to 29 Nov 15', 0, 0, 0, 10.91, '29-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 2 Nov to 29 Nov 15', 0, 0, 0, 7.27, '29-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Age 30 Nov 15 to 3 Jan 16', 0, 0, 0, 13.64, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Saturday Age 30 Nov 15 to 3 Jan 16', 0, 0, 0, 15.91, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Australian 30 Nov 15 to 3 Jan 16', 0, 0, 0, 15.91, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 30 Nov 15 to 3 Jan 16', 0, 0, 0, 8.45, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Economist 1 Dec to 22 Dec 15', 0, 0, 0, 41.82, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 1 Dec to 22 Dec 15', 0, 0, 0, 2.27, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 The Monthly 1 Dec to 22 Dec 15', 0, 0, 0, 10.86, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Directory charges 1 Jan to 31 Dec 16', 0, 0, 0, 3936.90, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Jan 16', 0, 0, 0, 262.00, '26-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Jan 16', 0, 0, 0, 32.14, '26-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Feb 16', 0, 0, 0, 266.80, '26-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Feb 16', 0, 0, 0, 32.26, '26-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Mar 16', 0, 0, 0, 262.67, '26-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Mar 16', 0, 0, 0, 32.14, '26-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Apr 16', 0, 0, 0, 276.59, '26-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Apr 16', 0, 0, 0, 32.14, '26-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 May 16', 0, 0, 0, 369.04, '26-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 May 16', 0, 0, 0, 34.33, '26-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office phones 26 Dec 15', 0, 0, 0, 325.87, '26-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office fax 26 Dec 15', 0, 0, 0, 32.35, '26-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Jan 16', 0, 0, 0, 45.41, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 Jan 16', 0, 0, 0, 31.77, '05-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Feb 16', 0, 0, 0, 45.41, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 Feb 16', 0, 0, 0, 31.77, '05-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 3 Mar 16', 0, 0, 0, 45.41, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 6 Mar 16', 0, 0, 0, 31.77, '06-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Apr 16', 0, 0, 0, 45.41, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 Apr 16', 0, 0, 0, 31.77, '08-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 2 May 16', 0, 0, 0, 45.41, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 May 16', 0, 0, 0, 31.77, '08-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Jun 16', 0, 0, 0, 45.41, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 Jun 16', 0, 0, 0, 31.77, '08-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Clare O''Neil', 'Representative', 'Hotham', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'Before 1 January 2016', '', '', '', 'Residential phones 6 Dec 15', 0, 0, 0, 31.77, '06-Dec-2015', '');
