INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Economics - Reps', 1, 273.00, 0, 273.00, '04-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '07-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '22-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '14-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 2, 273.00, 0, 546.00, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', -1, 273.00, 0, -273.00, '12-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 2, 273.00, 0, 546.00, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 1, 273.00, 0, 273.00, '03-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 January 2016', '', '', '', '', 0, 0, 0, 0, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 January 2016', '', '', 'Member initiated.', '', 0, 0, 0, 0, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '11 Feb 16 - Canberra to Sydney', 0, 0, 0, 328.20, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Apr 16 - Sydney to Canberra', 0, 0, 0, 328.20, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '19 Apr 16 - Canberra to Sydney', 0, 0, 0, 328.20, '19-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Sydney to Canberra', 0, 0, 0, 103.74, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Sydney', 0, 0, 0, 328.20, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2016', '', '', '', 'Sydney to Canberra 1 Feb 16', 0, 0, 0, 151.90, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2016', '', '', '', 'Canberra to Sydney 5 Feb 16', 0, 0, 0, 106.90, '05-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2016', '', '', '', 'Sydney to Canberra 22 Feb 16', 0, 0, 0, 106.90, '22-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2016', '', '', '', 'Canberra to Sydney 25 Feb 16', 0, 0, 0, 106.90, '25-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2016', '', '', '', 'Sydney to Canberra 29 Feb 16', 0, 0, 0, 106.90, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2016', '', '', '', 'Canberra to Sydney 3 Mar 16', 0, 0, 0, 87.10, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2016', '', '', '', 'Sydney to Canberra 14 Mar 16', 0, 0, 0, 87.10, '14-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2016', '', '', '', 'Canberra to Sydney 18 Mar 16', 0, 0, 0, 87.10, '18-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 1 Mar 15', 0, 0, 0, 3.40, '01-Mar-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 5 Mar 15', 0, 0, 0, 3.40, '05-Mar-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 15 Mar 15', 0, 0, 0, 3.40, '15-Mar-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 20 Mar 15', 0, 0, 0, 3.40, '20-Mar-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 23 Mar 15', 0, 0, 0, 3.40, '23-Mar-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 26 Mar 15', 0, 0, 0, 3.40, '26-Mar-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Lugarno to Canberra 11 May 15', 0, 0, 0, 3.40, '11-May-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Lugarno 14 May 15', 0, 0, 0, 3.40, '14-May-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 24 May 15', 0, 0, 0, 3.40, '24-May-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Lugarno 28 May 15', 0, 0, 0, 3.40, '28-May-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 1 Jun 15', 0, 0, 0, 3.40, '01-Jun-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Lugarno 4 Jun 15', 0, 0, 0, 3.40, '04-Jun-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Lugarno to Canberra 14 Jun 15', 0, 0, 0, 3.40, '14-Jun-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Lugarno 18 Jun 15', 0, 0, 0, 3.40, '18-Jun-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 21 Jun 15', 0, 0, 0, 3.40, '21-Jun-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Lugarno 25 Jun 15', 0, 0, 0, 3.40, '25-Jun-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 9 Aug 15', 0, 0, 0, 3.40, '09-Aug-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 13 Aug 15', 0, 0, 0, 3.40, '13-Aug-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 17 Aug 15', 0, 0, 0, 3.40, '17-Aug-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 21 Aug 15', 0, 0, 0, 3.40, '21-Aug-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 7 Sep 15', 0, 0, 0, 3.40, '07-Sep-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 10 Sep 15', 0, 0, 0, 3.40, '10-Sep-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 13 Sep 15', 0, 0, 0, 3.40, '13-Sep-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 18 Sep 15', 0, 0, 0, 3.40, '18-Sep-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 9 Nov 15', 0, 0, 0, 3.40, '09-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 12 Nov 15', 0, 0, 0, 3.40, '12-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 23 Nov 15', 0, 0, 0, 3.40, '23-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Canberra to Sydney 26 Nov 15', 0, 0, 0, 3.40, '26-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 30 Nov 15', 0, 0, 0, 205.90, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'Before 1 January 2016', '', '', '', 'Sydney to Canberra 3 Dec 15', 0, 0, 0, 205.90, '03-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '7 Feb 16 - Canberra', 0, 0, 0, 78.60, '07-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '11 Feb 16 - Sydney', 0, 0, 0, 43.70, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Apr 16 - Sydney', 0, 0, 0, 78.60, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Apr 16 - Sydney', 0, 0, 0, 54.79, '19-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 May 16 - Sydney', 0, 0, 0, 82.60, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 May 16 - Sydney', 0, 0, 0, 43.70, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 35925.87, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 3683.90, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 16', 0, 0, 0, 30.20, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Flags 1 Jan to 31 Jan 16', 0, 0, 0, 471.80, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 18 Jan 16', 0, 0, 0, 36.00, '18-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 18 Jan 16', 0, 0, 0, 1.14, '18-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 734.83, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 27.10, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Feb to 29 Feb 16', 0, 0, 0, 153.42, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 15 Feb 16', 0, 0, 0, 1.14, '15-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 15 Feb 16', 0, 0, 0, 60.00, '15-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 1011.21, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 13.87, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 14 Mar 16', 0, 0, 0, 72.00, '14-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 14 Mar 16', 0, 0, 0, 1.14, '14-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 725.38, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 11.26, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Apr to 30 Apr 16', 0, 0, 0, 347.45, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 11 Apr 16', 0, 0, 0, 1.14, '11-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 11 Apr 16', 0, 0, 0, 60.00, '11-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 12 Apr 16', 0, 0, 0, 11.82, '12-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 May to 31 May 16', 0, 0, 0, 200.79, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 9 May 16', 0, 0, 0, 60.00, '09-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 9 May 16', 0, 0, 0, 1.14, '09-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 6 Jun 16', 0, 0, 0, 72.00, '06-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 6 Jun 16', 0, 0, 0, 1.14, '06-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 7 Sep 13 to 30 Jun 14', 0, 0, 0, -2.48, '07-Sep-2013', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 14 to 30 Jun 15', 0, 0, 0, -69.90, '01-Jul-2014', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 15', 0, 0, 0, 879.86, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 15', 0, 0, 0, 15.19, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 163.67, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 8.15, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Water refills 14 Dec 15', 0, 0, 0, 60.00, '14-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Water refills 14 Dec 15', 0, 0, 0, 1.14, '14-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 79.51, '28-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 2.42, '28-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Jan to 31 Jan 16', 0, 0, 0, 3701.06, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Jan 16', 0, 0, 0, 15.00, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1,600 Printed items 11 Jan 16', 0, 0, 0, 626.00, '11-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '10,000 Personalised letterhead stationery 18 Jan 16', 0, 0, 0, 635.00, '18-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '7,500 Printed items 21 Jan 16', 0, 0, 0, 1960.00, '21-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 31 Dec 15', 0, 0, 0, 197.56, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Feb to 29 Feb 16', 0, 0, 0, 28490.01, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Feb to 29 Feb 16', 0, 0, 0, -22.73, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 6 Feb 16', 0, 0, 0, 200.00, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '35,432 Printed items 8 Feb 16', 0, 0, 0, 6144.00, '08-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '10,000 Personalised letterhead stationery 11 Feb 16', 0, 0, 0, 767.57, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 29 Feb 16', 0, 0, 0, 1218.26, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '67,119 Printed items 29 Feb 16', 0, 0, 0, 8350.00, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 1 Mar 16', 0, 0, 0, 38.95, '01-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Mar to 31 Mar 16', 0, 0, 0, 907.00, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Mar 16', 0, 0, 0, 15.00, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '500 Personalised letterhead stationery 17 Mar 16', 0, 0, 0, 130.00, '17-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 17 Mar 16', 0, 0, 0, 20.00, '17-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 20 Mar 16', 0, 0, 0, 950.27, '20-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 28 Mar 16', 0, 0, 0, 2240.00, '28-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 30 Mar 16', 0, 0, 0, 350.00, '30-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '10,000 Personalised letterhead stationery 31 Mar 16', 0, 0, 0, 635.00, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 31 Mar 16', 0, 0, 0, 394.25, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'PO Box 564 rental 1 Apr 16 to 31 Mar 17', 0, 0, 0, 164.55, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Apr to 30 Apr 16', 0, 0, 0, 7254.72, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Apr 16', 0, 0, 0, 15.00, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Apr to 30 Apr 16', 0, 0, 0, -22.73, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 6 Apr 16', 0, 0, 0, 350.00, '06-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '12,000 Printed items 18 Apr 16', 0, 0, 0, 1798.80, '18-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 18 Apr 16', 0, 0, 0, 2561.90, '18-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '7,000 Personalised letterhead stationery 18 Apr 16', 0, 0, 0, 560.00, '18-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 21 Apr 16', 0, 0, 0, 950.02, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 26 Apr 16', 0, 0, 0, 890.00, '26-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 30 Apr 16', 0, 0, 0, 616.65, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '10,000 Personalised letterhead stationery 6 May 16', 0, 0, 0, 635.00, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1,000 Printed items 13 May 16', 0, 0, 0, 2485.00, '13-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '8,000 Personalised letterhead stationery 19 May 16', 0, 0, 0, 695.00, '19-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Web-services 14 May 15 to 13 May 16', 0, 0, 0, 828.00, '14-May-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Web-services 29 Sep 15 to 15 Jan 16', 0, 0, 0, 381.00, '29-Sep-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Printing 10 Oct 15', 0, 0, 0, 300.00, '10-Oct-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '4,500 Personalised letterhead stationery 5 Nov 15', 0, 0, 0, 450.00, '05-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '9,000 Printed items 5 Nov 15', 0, 0, 0, 1220.00, '05-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 28 Nov 15', 0, 0, 0, 7222.58, '28-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'e-material 30 Nov to 10 Dec 15', 0, 0, 0, 365.74, '10-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'e-material 30 Nov 15', 0, 0, 0, 257.90, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 1 Dec to 31 Dec 15', 0, 0, 0, 5450.07, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '500 Printed items 4 Dec 15', 0, 0, 0, 925.00, '04-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1,500 Personalised letterhead stationery 5 Dec 15', 0, 0, 0, 1040.00, '05-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Printing 7 Dec 15', 0, 0, 0, 450.00, '07-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '100 Pocket Constitution 30 Nov 15', 0, 0, 0, 90.91, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '60 Pocket Constitution 9 Dec 15', 0, 0, 0, 69.09, '09-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 9 Jan 16', 0, 0, 0, 373.89, '09-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 9 Jan 16', 0, 0, 0, 61.23, '09-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 9 Feb 16', 0, 0, 0, 511.92, '09-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 9 Feb 16', 0, 0, 0, 68.86, '09-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 10 Mar 16', 0, 0, 0, 587.93, '10-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 10 Mar 16', 0, 0, 0, 61.95, '10-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 9 Apr 16', 0, 0, 0, 637.54, '09-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 9 Apr 16', 0, 0, 0, 69.95, '09-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 9 May 16', 0, 0, 0, 621.36, '09-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones directory charges 9 May 16', 0, 0, 0, 2549.28, '09-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 9 May 16', 0, 0, 0, 67.66, '09-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 9 Jun 16', 0, 0, 0, 768.05, '09-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 9 Jun 16', 0, 0, 0, 73.58, '09-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office phones 10 Dec 15', 0, 0, 0, 586.41, '10-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office fax 10 Dec 15', 0, 0, 0, 63.31, '10-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Jan 16', 0, 0, 0, 81.77, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 Jan 16', 0, 0, 0, 31.77, '05-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Feb 16', 0, 0, 0, 81.77, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 Feb 16', 0, 0, 0, 31.77, '05-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 3 Mar 16', 0, 0, 0, 81.77, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 6 Mar 16', 0, 0, 0, 31.78, '06-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Apr 16', 0, 0, 0, 81.77, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 Apr 16', 0, 0, 0, 35.08, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 2 May 16', 0, 0, 0, 81.77, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 May 16', 0, 0, 0, 32.68, '05-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Jun 16', 0, 0, 0, 81.76, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('David Coleman', 'Representative', 'Banks', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 Jun 16', 0, 0, 0, 31.77, '05-Jun-2016', '');
