INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '01-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '07-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 2, 273.00, 0, 546.00, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 Feb 16 - Perth to Canberra', 0, 0, 0, 1623.59, '01-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Feb 16 - Canberra to Perth', 0, 0, 0, 1623.59, '04-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '7 Feb 16 - Perth to Canberra', 0, 0, 0, 1623.59, '07-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '11 Feb 16 - Canberra to Perth', 0, 0, 0, 1623.59, '11-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Feb 16 - Perth to Canberra', 0, 0, 0, 1623.59, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '25 Feb 16 - Canberra to Perth', 0, 0, 0, 1623.59, '25-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '28 Feb 16 - Perth to Canberra', 0, 0, 0, 1623.59, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '3 Mar 16 - Canberra to Perth', 0, 0, 0, 1623.59, '03-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '14 Mar 16 - Perth to Melbourne', 0, 0, 0, 1633.60, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '14 Mar 16 - Melbourne to Canberra', 0, 0, 0, 0, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Apr 16 - Perth to Canberra', 0, 0, 0, 804.44, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '19 Apr 16 - Canberra to Perth', 0, 0, 0, 1624.54, '19-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Perth to Canberra', 0, 0, 0, 1624.54, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Sydney', 0, 0, 0, 1639.44, '06-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Sydney to Perth', 0, 0, 0, 0, '06-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 7 Jan to 6 Feb 16', 0, 0, 0, 1297.71, '06-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 30 Jan to 26 Feb 16', 0, 0, 0, 282.34, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 7 Feb to 6 Mar 16', 0, 0, 0, 1297.71, '06-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 7 Mar to 6 Apr 16', 0, 0, 0, 1297.71, '06-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 8 Mar to 24 Mar 16', 0, 0, 0, 184.70, '24-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 1 Apr to 22 Apr 16', 0, 0, 0, 367.58, '22-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 7 Apr to 6 May 16', 0, 0, 0, 1297.71, '06-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Car cleaning 10 Apr 16', 0, 0, 0, 16.09, '10-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 24 Apr to 29 May 16', 0, 0, 0, 453.36, '29-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 7 May to 6 Jun 16', 0, 0, 0, 1297.71, '06-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Car cleaning 29 May 16', 0, 0, 0, 16.09, '29-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Fuel 5 Dec to 19 Dec 15', 0, 0, 0, 310.85, '19-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Lease 7 Dec 15 to 6 Jan 16', 0, 0, 0, 1297.71, '07-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Fuel 23 Dec 15 to 25 Jan 16', 0, 0, 0, 211.64, '23-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Car cleaning 30 Dec 15', 0, 0, 0, 16.44, '30-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 Feb 16 - Perth', 0, 0, 0, 145.41, '01-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 Feb 16 - Perth', 0, 0, 0, 162.44, '04-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '7 Feb 16 - Perth', 0, 0, 0, 141.48, '07-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '10 Feb 16 - Canberra', 0, 0, 0, 40.00, '10-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '11 Feb 16 - Perth', 0, 0, 0, 150.65, '11-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Feb 16 - Perth', 0, 0, 0, 167.68, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '24 Feb 16 - Canberra', 0, 0, 0, 40.00, '24-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Feb 16 - Canberra', 0, 0, 0, 40.00, '25-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Feb 16 - Perth', 0, 0, 0, 40.00, '25-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Feb 16 - Perth', 0, 0, 0, 182.09, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '2 Mar 16 - Canberra', 0, 0, 0, 40.00, '02-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '3 Mar 16 - Perth', 0, 0, 0, 148.03, '03-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '14 Mar 16 - Perth', 0, 0, 0, 166.37, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Mar 16 - Canberra', 0, 0, 0, 40.00, '17-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '18 Mar 16 - Perth', 0, 0, 0, 151.96, '18-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Apr 16 - Perth', 0, 0, 0, 171.61, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Apr 16 - Perth', 0, 0, 0, 142.79, '19-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 May 16 - Perth', 0, 0, 0, 151.96, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 May 16 - Canberra', 0, 0, 0, 40.00, '04-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '5 May 16 - Canberra', 0, 0, 0, 40.00, '05-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 May 16 - Perth', 0, 0, 0, 40.00, '06-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '15 Oct 15 - Perth', 0, 0, 0, 40.00, '15-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 62671.78, '01-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 4271.54, '01-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Flags 1 Jan to 31 Jan 16', 0, 0, 0, 2830.80, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 11 Jan 16', 0, 0, 0, 33.00, '11-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 25 Jan 16', 0, 0, 0, 12.00, '25-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 530.02, '27-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 14.26, '27-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Feb to 29 Feb 16', 0, 0, 0, 642.19, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 8 Feb 16', 0, 0, 0, 33.00, '08-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 22 Feb 16', 0, 0, 0, 52.50, '22-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 929.63, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 19.45, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Mar to 31 Mar 16', 0, 0, 0, 363.71, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 9 Mar 16', 0, 0, 0, 42.00, '09-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 21 Mar 16', 0, 0, 0, 33.00, '21-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 680.97, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 20.24, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 4 Apr 16', 0, 0, 0, 33.00, '04-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Apr to 27 May 16', 0, 0, 0, 1091.10, '27-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Apr to 27 May 16', 0, 0, 0, 15.95, '27-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 May to 31 May 16', 0, 0, 0, 81.40, '31-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 2 May 16', 0, 0, 0, 42.00, '02-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 16 May 16', 0, 0, 0, 33.00, '16-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 30 May 16', 0, 0, 0, 33.00, '30-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 13 Jun 16', 0, 0, 0, 12.00, '13-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 27 Jun 16', 0, 0, 0, 22.00, '27-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 14 to 30 Jun 15', 0, 0, 0, -111.37, '01-Jul-2014', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 582.81, '27-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 12.99, '27-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 82.03, '28-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 4.61, '28-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '50 Printed items 15 Jan 16', 0, 0, 0, 1180.64, '15-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 21 Jan 16', 0, 0, 0, 380.00, '21-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 26 Jan 16', 0, 0, 0, 578.82, '26-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 26 Jan 16', 0, 0, 0, 720.75, '26-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Feb to 29 Feb 16', 0, 0, 0, 909.09, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Feb to 29 Feb 16', 0, 0, 0, -22.73, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 9 Feb 16', 0, 0, 0, 657.75, '09-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 9 Feb 16', 0, 0, 0, 634.26, '09-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '100 Printed items 22 Feb 16', 0, 0, 0, 143.73, '22-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Mar to 31 Mar 16', 0, 0, 0, 90.91, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'PO Box 329 rental 1 Apr 16 to 31 Mar 17', 0, 0, 0, 262.73, '01-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 19 Apr 16', 0, 0, 0, 634.26, '19-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 19 Apr 16', 0, 0, 0, 578.82, '19-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 21 Apr 16', 0, 0, 0, 500.00, '21-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 May to 31 May 16', 0, 0, 0, 296.05, '31-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '63,500 Postal vote applications 11 May 16', 0, 0, 0, 23238.45, '11-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 11 May 16', 0, 0, 0, 80.91, '11-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 11 May 16', 0, 0, 0, 10895.91, '11-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 24 May 16', 0, 0, 0, 1345.40, '24-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 24 May 16', 0, 0, 0, 1227.80, '24-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 24 May 16', 0, 0, 0, 100.00, '24-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '127,202 Printed items 24 May 16', 0, 0, 0, 16923.18, '24-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 31 May 16', 0, 0, 0, 1345.40, '31-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 31 May 16', 0, 0, 0, 1227.80, '31-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 1 Jun 16', 0, 0, 0, 800.00, '01-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 4 Jun to 25 Jun 16', 0, 0, 0, 800.00, '25-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 8 Jun 16', 0, 0, 0, 800.00, '08-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 15 Jun 16', 0, 0, 0, 800.00, '15-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 22 Jun 16', 0, 0, 0, 800.00, '22-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 29 Jun 16', 0, 0, 0, 800.00, '29-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 26 Aug 15', 0, 0, 0, 313.64, '26-Aug-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 24 Nov 15', 0, 0, 0, 720.75, '24-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 24 Nov 15', 0, 0, 0, 657.75, '24-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 3 Dec 15', 0, 0, 0, 300.00, '03-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 8 Dec 15', 0, 0, 0, 720.75, '08-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 8 Dec 15', 0, 0, 0, 578.82, '08-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 15 Dec 15', 0, 0, 0, 657.75, '15-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 17 Dec 15', 0, 0, 0, 300.00, '17-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 22 Dec 15', 0, 0, 0, 657.75, '22-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 29 Dec 15', 0, 0, 0, 712.80, '29-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 18 Jan to 14 Feb 16', 0, 0, 0, 36.36, '14-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The West Australian 18 Jan to 14 Feb 16', 0, 0, 0, 27.27, '14-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 18 Jan to 14 Feb 16', 0, 0, 0, 72.73, '14-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 18 Jan to 14 Feb 16', 0, 0, 0, 49.09, '14-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 1 Feb to 28 Feb 16', 0, 0, 0, 2.00, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '11 The Australian 1 Feb to 28 Feb 16', 0, 0, 0, 27.00, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '11 The West Australian 1 Feb to 28 Feb 16', 0, 0, 0, 65.00, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 15 Feb to 13 Mar 16', 0, 0, 0, 36.36, '13-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The West Australian 15 Feb to 13 Mar 16', 0, 0, 0, 27.27, '13-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 15 Feb to 13 Mar 16', 0, 0, 0, 72.73, '13-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 15 Feb to 13 Mar 16', 0, 0, 0, 49.09, '13-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '7 The Australian 29 Feb to 27 Mar 16', 0, 0, 0, 17.18, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '7 The West Australian 29 Feb to 27 Mar 16', 0, 0, 0, 41.36, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 29 Feb to 27 Mar 16', 0, 0, 0, 1.27, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 14 Mar to 10 Apr 16', 0, 0, 0, 36.36, '10-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '19 The Australian 14 Mar to 10 Apr 16', 0, 0, 0, 46.64, '10-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '19 The Australian Financial Review 14 Mar to 10 Apr 16', 0, 0, 0, 69.09, '10-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '19 The West Australian 14 Mar to 10 Apr 16', 0, 0, 0, 25.91, '10-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 11 Apr to 8 May 16', 0, 0, 0, 36.36, '08-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 11 Apr to 8 May 16', 0, 0, 0, 72.73, '08-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The West Australian 11 Apr to 8 May 16', 0, 0, 0, 27.27, '08-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 11 Apr to 8 May 16', 0, 0, 0, 49.09, '08-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 9 May to 5 Jun 16', 0, 0, 0, 36.36, '05-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 9 May to 5 Jun 16', 0, 0, 0, 72.73, '05-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The West Australian 9 May to 5 Jun 16', 0, 0, 0, 27.27, '05-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 9 May to 5 Jun 16', 0, 0, 0, 49.09, '05-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 23 Nov to 20 Dec 15', 0, 0, 0, 36.36, '20-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '20 The West Australian 23 Nov to 20 Dec 15', 0, 0, 0, 27.27, '20-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '20 The Australian Financial Review 23 Nov to 20 Dec 15', 0, 0, 0, 63.64, '20-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '20 The Australian 23 Nov to 20 Dec 15', 0, 0, 0, 49.09, '20-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Australian 30 Nov 15 to 3 Jan 16', 0, 0, 0, 9.82, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The West Australian 30 Nov 15 to 3 Jan 16', 0, 0, 0, 23.64, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 30 Nov 15 to 3 Jan 16', 0, 0, 0, 0.73, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '9 The Australian 21 Dec 15 to 17 Jan 16', 0, 0, 0, 22.09, '21-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 21 Dec 15 to 17 Jan 16', 0, 0, 0, 18.18, '21-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '9 The West Australian 21 Dec 15 to 17 Jan 16', 0, 0, 0, 12.27, '21-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '9 The Australian Financial Review 21 Dec 15 to 17 Jan 16', 0, 0, 0, 28.64, '21-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Jan 16', 0, 0, 0, 215.82, '01-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Jan 16', 0, 0, 0, 74.68, '01-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Feb 16', 0, 0, 0, 200.77, '01-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Feb 16', 0, 0, 0, 78.32, '01-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 3 Mar 16', 0, 0, 0, 244.08, '03-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 3 Mar 16', 0, 0, 0, 81.59, '03-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Apr 16', 0, 0, 0, 240.89, '01-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Apr 16', 0, 0, 0, 75.67, '01-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 2 May 16', 0, 0, 0, 243.69, '02-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 2 May 16', 0, 0, 0, 84.85, '02-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Jun 16', 0, 0, 0, 251.72, '01-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Jun 16', 0, 0, 0, 84.98, '01-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 Jan 16', 0, 0, 0, 31.78, '11-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 Feb 16', 0, 0, 0, 31.77, '11-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 14 Mar 16', 0, 0, 0, 31.77, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 Apr 16', 0, 0, 0, 31.84, '11-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 May 16', 0, 0, 0, 31.77, '11-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 Jun 16', 0, 0, 0, 31.94, '11-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '16 Mar 16 - Perth to Canberra', 0, 0, 0, 1624.54, '16-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2016', '', '', '', '29 Nov 15 - Perth to Canberra', 0, 0, 0, 1562.43, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2016', '', '', '', '4 Dec 15 - Canberra to Melbourne', 0, 0, 0, 1570.87, '04-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2016', '', '', '', '4 Dec 15 - Melbourne to Perth', 0, 0, 0, 0, '04-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '16 Mar 16 - Perth', 0, 0, 0, 153.27, '16-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '16 Mar 16 - Canberra', 0, 0, 0, 41.80, '16-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Mar 16 - Canberra', 0, 0, 0, 78.60, '17-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Overseas Travel', 'Overseas Travel', 'Before 1 January 2016', '', '', '', '', 0, 0, 0, 128.55, '01-Jan-2016', '', 'OS Delegation - Accommodation and meals');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Overseas Travel', 'Overseas Travel', 'Before 1 January 2016', '', '', '', '', 0, 0, 0, 634.53, '01-Jan-2016', '', 'OS Delegation - Ground transport');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes, Type)
VALUES ('Dennis Jensen', 'Representative', 'Tangney', 'Western Australia', 'Liberal Party of Australia', 'Overseas Travel', 'Overseas Travel', 'Before 1 January 2016', '', '', '', '', 0, 0, 0, 592.94, '01-Jan-2016', '', 'OS Delegation - Official hospitality non portfolio related');
