INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Cairns', 'Shadow Parliamentary Secretary - Official', 1, 291.00, 0, 291.00, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', '', 'Business', 0, 0, 0, 0, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '31 Mar 16 - Canberra to Sydney', 0, 0, 0, 684.10, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '31 Mar 16 - Sydney to Cairns', 0, 0, 0, 0, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 Apr 16 - Cairns to Townsville', 0, 0, 0, 339.92, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 Apr 16 - Townsville to Brisbane', 0, 0, 0, 651.87, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 Apr 16 - Brisbane to Canberra', 0, 0, 0, 0, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Apr 16 - Canberra to Sydney', 0, 0, 0, 103.74, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Apr 16 - Newcastle to Canberra', 0, 0, 0, 369.25, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 Jun 16 - Canberra to Melbourne', 0, 0, 0, 818.09, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 Jun 16 - Melbourne to Perth', 0, 0, 0, 0, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 Jun 16 - Perth to Sydney', 0, 0, 0, 823.93, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '2 Jun 16 - Sydney to Canberra', 0, 0, 0, 0, '02-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Jun 16 - Canberra to Sydney', 0, 0, 0, 328.20, '04-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Jun 16 - Sydney to Canberra', 0, 0, 0, 328.20, '04-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Jun 16 - Canberra to Sydney', 0, 0, 0, 711.70, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Jun 16 - Sydney to Wellcamp', 0, 0, 0, 0, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Jun 16 - Brisbane to Canberra', 0, 0, 0, 469.90, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '23 Jun 16 - Canberra to Sydney', 0, 0, 0, 859.23, '23-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '23 Jun 16 - Sydney to Darwin', 0, 0, 0, 0, '23-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '24 Jun 16 - Darwin to Melbourne', 0, 0, 0, 1241.24, '24-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '24 Jun 16 - Melbourne to Canberra', 0, 0, 0, 0, '24-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2016', '', '', '', '22 Dec 15 - Canberra to Sydney', 0, 0, 0, 103.74, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2016', '', '', '', '22 Dec 15 - Newcastle to Canberra', 0, 0, 0, 369.25, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 Jan to 17 Feb 16', 0, 0, 0, 713.79, '17-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 5 Feb to 20 Feb 16', 0, 0, 0, 113.86, '20-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 Feb to 17 Mar 16', 0, 0, 0, 713.79, '17-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 8 Mar to 20 Mar 16', 0, 0, 0, 107.50, '20-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 Mar to 17 Apr 16', 0, 0, 0, 713.79, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 5 Apr to 22 Apr 16', 0, 0, 0, 110.35, '22-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 Apr to 17 May 16', 0, 0, 0, 713.79, '17-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 11 May to 21 May 16', 0, 0, 0, 112.79, '21-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 May to 17 Jun 16', 0, 0, 0, 713.79, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Fuel 18 Nov 15', 0, 0, 0, 61.76, '18-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Lease 18 Nov to 17 Dec 15', 0, 0, 0, 713.79, '17-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Fuel 29 Nov to 11 Dec 15', 0, 0, 0, 114.92, '11-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Lease 18 Dec 15 to 17 Jan 16', 0, 0, 0, 713.79, '18-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 Apr 16 - Townsville', 0, 0, 0, 60.48, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 Apr 16 - Townsville', 0, 0, 0, 61.48, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Apr 16 - Canberra', 0, 0, 0, 40.00, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Apr 16 - Sydney', 0, 0, 0, 824.25, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Apr 16 - Canberra', 0, 0, 0, 78.60, '25-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Apr 16 - Canberra', 0, 0, 0, 78.60, '25-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 Jun 16 - Perth', 0, 0, 0, 919.62, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 Jun 16 - Canberra', 0, 0, 0, 78.60, '04-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 Jun 16 - Sydney', 0, 0, 0, 712.04, '04-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Jun 16 - Brisbane', 0, 0, 0, 548.42, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Jun 16 - Canberra', 0, 0, 0, 40.00, '23-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Jun 16 - Darwin', 0, 0, 0, 40.00, '23-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '24 Jun 16 - Darwin', 0, 0, 0, 196.50, '24-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '22 Dec 15 - Canberra', 0, 0, 0, 40.00, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '22 Dec 15 - Sydney', 0, 0, 0, 745.45, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '22 Dec 15 - Canberra', 0, 0, 0, 41.80, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 60070.76, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 2931.15, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 708.25, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 3.70, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 161.22, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 2.00, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Mar to 31 Mar 16', 0, 0, 0, 1161.23, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 46.94, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 3.92, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Flags 1 May to 31 May 16', 0, 0, 0, 471.80, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Software reimbursement 2015/16', 0, 0, 0, 1500.00, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 39.44, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 1.00, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 15', 0, 0, 0, 409.33, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Flags 1 Dec to 31 Dec 15', 0, 0, 0, 2416.40, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 18.21, '28-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 6.35, '28-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Jan to 31 Jan 16', 0, 0, 0, 501.18, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Jan to 31 Jan 16', 0, 0, 0, -12.50, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 5 Jan to 30 Jan 16', 0, 0, 0, 280.72, '30-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Feb to 29 Feb 16', 0, 0, 0, 7275.27, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 4 Feb 16', 0, 0, 0, 580.00, '04-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 11 Feb 16', 0, 0, 0, 580.00, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 18 Feb 16', 0, 0, 0, 580.00, '18-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '10,000 Printed items 29 Feb 16', 0, 0, 0, 2470.00, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '10,000 Printed items 29 Feb 16', 0, 0, 0, 4330.00, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Mar 16', 0, 0, 0, 15.00, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Apr to 30 Apr 16', 0, 0, 0, 545.45, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Apr to 30 Apr 16', 0, 0, 0, -11.36, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'e-material 30 Apr 16', 0, 0, 0, 67.00, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 May to 31 May 16', 0, 0, 0, 0.59, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 19 May 16', 0, 0, 0, 370.00, '19-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '100,000 Personalised letterhead stationery 23 May 16', 0, 0, 0, 1870.00, '23-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '100,000 Personalised letterhead stationery 24 May 16', 0, 0, 0, 4270.00, '24-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Jun to 24 Jun 16', 0, 0, 0, 11.00, '24-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Jun to 24 Jun 16', 0, 0, 0, 17719.13, '24-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Jun to 24 Jun 16', 0, 0, 0, -13.64, '24-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'e-material 27 Jul 15', 0, 0, 0, 33.81, '27-Jul-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'e-material 27 Sep 15', 0, 0, 0, 38.71, '27-Sep-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'e-material 30 Sep to 30 Oct 15', 0, 0, 0, 292.97, '30-Oct-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'e-material 27 Oct 15', 0, 0, 0, 37.63, '27-Oct-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '74,000 Printed items 20 Nov 15', 0, 0, 0, 13276.00, '20-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '3,000 Printed items 26 Nov 15', 0, 0, 0, 1575.00, '26-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'e-material 27 Nov 15', 0, 0, 0, 37.60, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 1 Dec to 31 Dec 15', 0, 0, 0, 41321.17, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution credit 1 Dec to 31 Dec 15', 0, 0, 0, -16974.65, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Feb16', 0, 0, 0, 485.03, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Feb 16', 0, 0, 0, 60.06, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones directory charges 3 Mar 16', 0, 0, 0, 2393.00, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 3 Mar 16', 0, 0, 0, 280.54, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 3 Mar 16', 0, 0, 0, 32.14, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Apr 16', 0, 0, 0, 339.99, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Apr 16', 0, 0, 0, 32.14, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 2 May 16', 0, 0, 0, 347.33, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 2 May 16', 0, 0, 0, 32.86, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Jun 16', 0, 0, 0, 331.23, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Jun 16', 0, 0, 0, 32.14, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 1 Feb 16', 0, 0, 0, 156.67, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Feb 16', 0, 0, 0, 109.00, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 3 Mar 16', 0, 0, 0, 107.75, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 3 Mar 16', 0, 0, 0, 54.50, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 1 Apr 16', 0, 0, 0, 84.09, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Apr 16', 0, 0, 0, 54.50, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones adj 2 May 16', 0, 0, 0, -38.17, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Gai Brodtmann', 'Representative', 'Canberra', 'Australian Capital Territory', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line adj 2 May 16', 0, 0, 0, -3.51, '02-May-2016', '');
