INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Lakes Entrance', 'Electorate Business', 1, 368.00, 0, 368.00, '19-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Senate Estimates', 4, 273.00, 0, 1092.00, '07-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Morwell', 'Electorate Business', 1, 258.00, 0, 258.00, '29-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Wollongong', 'Economics - Sen', 1, 123.00, 0, 123.00, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 2, 273.00, 0, 546.00, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Senate Estimates', 2, 273.00, 0, 546.00, '04-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2016', '', '', '', '', 0, 0, 0, 2732.27, '01-Jan-2016', 'OS Official - Accommodation and meals', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2016', '', '', '', '', 0, 0, 0, 17655.68, '01-Jan-2016', 'OS Official - Fares', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2016', '', '', '', '', 0, 0, 0, 441.00, '01-Jan-2016', 'OS Official - Minor official expense advance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2016', '', '', '', '', 0, 0, 0, 40.00, '01-Jan-2016', 'OS Official - Passport costs', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2016', '', '', '', '', 0, 0, 0, 307.34, '01-Jan-2016', 'OS Official - Travel advance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '31 Jan 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '5 Feb 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '05-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '7 Feb 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '07-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '11 Feb 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '11-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Feb 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '26 Feb 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '28 Feb 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Mar 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '04-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '14 Mar 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '18 Mar 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '18-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '23 Mar 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '23 Mar 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '31 Mar 16 - Melbourne to Sydney', 0, 0, 0, 698.76, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '3 Apr 16 - Sydney to Melbourne', 0, 0, 0, 698.76, '03-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Apr 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '19 Apr 16 - Canberra to Sydney', 0, 0, 0, 598.39, '19-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '27 Apr 16 - Sydney to Melbourne', 0, 0, 0, 698.76, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '06-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 4 Jan to 22 Jan 16', 0, 0, 0, 304.85, '22-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 8 Jan to 7 Feb 16', 0, 0, 0, 1059.09, '07-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 30 Jan to 31 Jan 16', 0, 0, 0, 65.95, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 8 Feb to 7 Mar 16', 0, 0, 0, 1059.09, '07-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 25 Feb 16', 0, 0, 0, 54.59, '25-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 8 Mar to 7 Apr 16', 0, 0, 0, 1059.09, '07-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 29 Mar 16', 0, 0, 0, 57.61, '29-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 8 Apr to 7 May 16', 0, 0, 0, 1059.09, '07-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 19 Apr 16', 0, 0, 0, 61.54, '19-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 8 May to 7 Jun 16', 0, 0, 0, 1059.09, '07-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 9 May to 15 May 16', 0, 0, 0, 61.20, '15-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Lease 8 Dec 15 to 7 Jan 16', 0, 0, 0, 1059.09, '08-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '31 Jan 16 - Melbourne', 0, 0, 0, 80.80, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '5 Feb 16 - Melbourne', 0, 0, 0, 44.20, '05-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '7 Feb 16 - Melbourne', 0, 0, 0, 80.80, '07-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '11 Feb 16 - Melbourne', 0, 0, 0, 44.20, '11-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Feb 16 - Melbourne', 0, 0, 0, 80.80, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '26 Feb 16 - Melbourne', 0, 0, 0, 44.20, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Feb 16 - Melbourne', 0, 0, 0, 78.60, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 Mar 16 - Melbourne', 0, 0, 0, 44.20, '04-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '14 Mar 16 - Melbourne', 0, 0, 0, 83.00, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '18 Mar 16 - Melbourne', 0, 0, 0, 82.80, '18-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Mar 16 - Melbourne', 0, 0, 0, 42.20, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Mar 16 - Canberra', 0, 0, 0, 41.80, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Mar 16 - Canberra', 0, 0, 0, 40.00, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Mar 16 - Canberra', 0, 0, 0, 40.00, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Mar 16 - Melbourne', 0, 0, 0, 44.20, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Mar 16 - Melbourne', 0, 0, 0, 47.24, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '23 Mar 16 - Melbourne', 0, 0, 0, 79.91, '23-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '31 Mar 16 - Melbourne', 0, 0, 0, 53.29, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '3 Apr 16 - Melbourne', 0, 0, 0, 82.80, '03-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Apr 16 - Melbourne', 0, 0, 0, 78.60, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Apr 16 - Sydney', 0, 0, 0, 43.70, '19-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '20 Apr 16 - Sydney', 0, 0, 0, 40.00, '20-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '27 Apr 16 - Melbourne', 0, 0, 0, 44.20, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 May 16 - Melbourne', 0, 0, 0, 80.80, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 May 16 - Melbourne', 0, 0, 0, 46.40, '06-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Jun 16 - Melbourne', 0, 0, 0, 84.60, '25-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Jun 16 - Melbourne', 0, 0, 0, 81.30, '25-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Jun 16 - Canberra', 0, 0, 0, 41.80, '28-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Jun 16 - Canberra', 0, 0, 0, 40.00, '28-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Jun 16 - Melbourne', 0, 0, 0, 44.20, '28-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '25 Feb 16', 0, 0, 0, 13.42, '25-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '4 May 16', 0, 0, 0, 13.22, '04-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Other Car Costs', 'From 1 January 2016', '', '', '', 'Sydney 31 Mar to 1 Apr 16', 0, 0, 0, 85.44, '01-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Other Car Costs', 'From 1 January 2016', '', '', '', 'Fuel charge 1 Apr 16', 0, 0, 0, 18.41, '01-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Other Car Costs', 'From 1 January 2016', '', '', '', 'Taxi 3 Apr 16', 0, 0, 0, 45.45, '03-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 60025.87, '01-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 5151.45, '01-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 16', 0, 0, 0, 2866.59, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 746.24, '27-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 21.58, '27-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Feb to 29 Feb 16', 0, 0, 0, 2302.97, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 566.18, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 16.10, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Mar to 31 Mar 16', 0, 0, 0, 1502.71, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 677.57, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 6.66, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Apr to 30 Apr 16', 0, 0, 0, 3035.73, '30-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Apr to 27 May 16', 0, 0, 0, 393.25, '27-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Apr to 27 May 16', 0, 0, 0, 55.99, '27-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 12 to 30 Jun 14', 0, 0, 0, -258.33, '01-Jul-2012', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 14 to 30 Jun 15', 0, 0, 0, -5084.66, '01-Jul-2014', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 15 to 31 Mar 16', 0, 0, 0, -1840.58, '01-Jul-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 669.69, '27-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 6.42, '27-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 133.69, '28-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 1.34, '28-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '52,571 Printed items 29 Feb 16', 0, 0, 0, 2338.00, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Mar to 31 Mar 16', 0, 0, 0, 17448.38, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Mar to 31 Mar 16', 0, 0, 0, -10514.20, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 May to 31 May 16', 0, 0, 0, 28443.25, '31-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 May to 31 May 16', 0, 0, 0, -90.91, '31-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee May 16', 0, 0, 0, 15.00, '01-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 May to 31 May 16', 0, 0, 0, 272.14, '31-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 1 Dec to 31 Dec 15', 0, 0, 0, 533.91, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution credit 1 Dec to 31 Dec 15', 0, 0, 0, -9.09, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 4 Jan to 31 Jan 16', 0, 0, 0, 4.55, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 4 Jan to 31 Jan 16', 0, 0, 0, 49.09, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 Herald Sun 4 Jan to 31 Jan 16', 0, 0, 0, 25.45, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '9 The Australian Financial Review 4 Jan to 31 Jan 16', 0, 0, 0, 31.09, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '9 The Age 4 Jan to 31 Jan 16', 0, 0, 0, 20.45, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 4 Jan to 31 Jan 16', 0, 0, 0, 2.45, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 4 Jan to 31 Jan 16', 0, 0, 0, 1.09, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Australian Financial Review 4 Jan to 31 Jan 16', 0, 0, 0, 3.45, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Age 4 Jan to 31 Jan 16', 0, 0, 0, 2.73, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Age 4 Jan to 31 Jan 16', 0, 0, 0, 3.18, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 1 Feb to 28 Feb 16', 0, 0, 0, 4.55, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 1 Feb to 28 Feb 16', 0, 0, 0, 49.09, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 Herald Sun 1 Feb to 28 Feb 16', 0, 0, 0, 26.82, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 Herald Sun 1 Feb to 28 Feb 16', 0, 0, 0, 8.91, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 1 Feb to 28 Feb 16', 0, 0, 0, 0.91, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '2 The Australian 1 Feb to 28 Feb 16', 0, 0, 0, 6.36, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 1 Feb to 28 Feb 16', 0, 0, 0, 5.45, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 1 Feb to 28 Feb 16', 0, 0, 0, 72.73, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Age 1 Feb to 28 Feb 16', 0, 0, 0, 45.45, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 1 Feb to 28 Feb 16', 0, 0, 0, 10.91, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Age 1 Feb to 28 Feb 16', 0, 0, 0, 12.73, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Australian Financial Review 1 Feb to 28 Feb 16', 0, 0, 0, 14.55, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 1 Feb to 28 Feb 16', 0, 0, 0, 4.36, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 Workplace Express (digital) 20 Mar 16 to 20 Mar 17', 0, 0, 0, 990.00, '20-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Saturday Age 24 Aug to 27 Sep 15', 0, 0, 0, 15.91, '27-Sep-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Weekend Financial Review 24 Aug to 27 Sep 15', 0, 0, 0, 17.27, '27-Sep-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Sunday Age 24 Aug to 27 Sep 15', 0, 0, 0, 13.64, '27-Sep-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Refund of publications 24 Aug to 27 Sep 15', 0, 0, 0, -24.82, '27-Sep-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 24 Aug to 27 Sep 15', 0, 0, 0, 5.45, '27-Sep-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 24 Aug to 27 Sep 15', 0, 0, 0, 6.82, '27-Sep-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '25 The Age 24 Aug to 27 Sep 15', 0, 0, 0, 56.82, '27-Sep-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '25 The Australian Financial Review 24 Aug to 27 Sep 15', 0, 0, 0, 86.36, '27-Sep-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 28 Sep to 1 Nov 15', 0, 0, 0, 5.68, '01-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '25 Herald Sun 28 Sep to 1 Nov 15', 0, 0, 0, 31.82, '01-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '25 The Australian 28 Sep to 1 Nov 15', 0, 0, 0, 61.36, '01-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Australian 28 Sep to 1 Nov 15', 0, 0, 0, 15.00, '01-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 28 Sep to 1 Nov 15', 0, 0, 0, 2.27, '01-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '10 Herald Sun 28 Sep to 1 Nov 15', 0, 0, 0, 22.27, '01-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 28 Sep to 25 Oct 15', 0, 0, 0, 5.18, '25-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '19 The Age 28 Sep to 25 Oct 15', 0, 0, 0, 43.18, '25-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '19 The Australian Financial Review 28 Sep to 25 Oct 15', 0, 0, 0, 65.64, '25-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Australian Financial Review 28 Sep to 25 Oct 15', 0, 0, 0, 13.82, '25-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Age 28 Sep to 25 Oct 15', 0, 0, 0, 12.73, '25-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Age 28 Sep to 25 Oct 15', 0, 0, 0, 10.91, '25-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 28 Sep to 25 Oct 15', 0, 0, 0, 4.36, '25-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 26 Oct to 29 Nov 15', 0, 0, 0, 6.55, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '24 The Australian Financial Review 26 Oct to 29 Nov 15', 0, 0, 0, 82.91, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '24 The Age 26 Oct to 29 Nov 15', 0, 0, 0, 54.55, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Age 26 Oct to 29 Nov 15', 0, 0, 0, 13.64, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Age 26 Oct to 29 Nov 15', 0, 0, 0, 15.91, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '5 The Australian Financial Review 26 Oct to 29 Nov 15', 0, 0, 0, 17.27, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 26 Oct to 29 Nov 15', 0, 0, 0, 5.45, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 2 Nov to 29 Nov 15', 0, 0, 0, 4.55, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '20 Herald Sun 2 Nov to 29 Nov 15', 0, 0, 0, 25.45, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '20 The Australian 2 Nov to 29 Nov 15', 0, 0, 0, 49.09, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '8 Herald Sun 2 Nov to 29 Nov 15', 0, 0, 0, 17.82, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Australian 2 Nov to 29 Nov 15', 0, 0, 0, 12.00, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 2 Nov to 29 Nov 15', 0, 0, 0, 1.82, '29-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Saturday Age 30 Nov 15 to 3 Jan 16', 0, 0, 0, 12.73, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Weekend Financial Review 30 Nov 15 to 3 Jan 16', 0, 0, 0, 13.82, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Sunday Age 30 Nov 15 to 3 Jan 16', 0, 0, 0, 10.91, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 30 Nov 15 to 3 Jan 16', 0, 0, 0, 4.36, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 30 Nov 15 to 3 Jan 16', 0, 0, 0, 5.18, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '19 The Age 30 Nov 15 to 3 Jan 16', 0, 0, 0, 43.18, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '18 The Australian Financial Review 30 Nov 15 to 3 Jan 16', 0, 0, 0, 62.18, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 30 Nov 15 to 3 Jan 16', 0, 0, 0, 4.09, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '18 Herald Sun 30 Nov 15 to 3 Jan 16', 0, 0, 0, 22.91, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '18 The Australian 30 Nov 15 to 3 Jan 16', 0, 0, 0, 44.18, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '8 Herald Sun 30 Nov 15 to 3 Jan 16', 0, 0, 0, 17.82, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '4 The Australian 30 Nov 15 to 3 Jan 16', 0, 0, 0, 12.00, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 30 Nov 15 to 3 Jan 16', 0, 0, 0, 1.82, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 The Dismissal 1 Dec 15', 0, 0, 0, 36.35, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 Reith Papers 1 Dec 15', 0, 0, 0, 40.91, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 The Short and Excruciatingly Embarrassing Reign of Captain Abbott 1 Dec 15', 0, 0, 0, 27.26, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 Men and Women of Australia: Our Greatest Modern Speeches 1 Dec 15', 0, 0, 0, 29.99, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 Keating 1 Dec 15', 0, 0, 0, 45.41, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 Catch and Kill: The Politics of Power 1 Dec 15', 0, 0, 0, 29.95, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 Advance Australia Where? 1 Dec 15', 0, 0, 0, 22.72, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 Mateship 1 Dec 15', 0, 0, 0, 27.26, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 Political Amnesia: How We Forgot To Govern (Quarterly Essay 60) 1 Dec 15', 0, 0, 0, 20.90, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '1 Invention of Russia 1 Dec 15', 0, 0, 0, 31.81, '01-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '52 The Saturday Paper and 1 The Saturday Paper (digital) 9 Dec 15 to 8 Dec 16', 0, 0, 0, 126.36, '09-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Directory charges 1 Jan to 31 Dec 16', 0, 0, 0, 3936.90, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Jan 16', 0, 0, 0, 179.01, '26-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Jan 16', 0, 0, 0, 33.00, '26-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Feb 16', 0, 0, 0, 354.65, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Feb 16', 0, 0, 0, 31.77, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Mar 16', 0, 0, 0, 379.11, '26-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Mar 16', 0, 0, 0, 31.77, '26-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Apr 16', 0, 0, 0, 221.15, '26-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Apr 16', 0, 0, 0, 32.14, '26-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 May 16', 0, 0, 0, 244.40, '26-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 May 16', 0, 0, 0, 31.91, '26-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office phones 6 Nov 15', 0, 0, 0, 50.00, '06-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office phones 26 Dec 15', 0, 0, 0, 282.16, '26-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office fax 26 Dec 15', 0, 0, 0, 31.77, '26-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Jan 16', 0, 0, 0, 81.77, '01-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 Jan 16', 0, 0, 0, 63.55, '05-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Feb 16', 0, 0, 0, 81.77, '01-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 5 Feb 16', 0, 0, 0, 63.55, '05-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 3 Mar 16', 0, 0, 0, 81.77, '03-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 6 Mar 16', 0, 0, 0, 63.55, '06-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Apr 16', 0, 0, 0, 81.77, '01-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 Apr 16', 0, 0, 0, 63.55, '08-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 26 Apr 16', 0, 0, 0, 150.00, '26-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 2 May 16', 0, 0, 0, 81.77, '02-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 May 16', 0, 0, 0, 63.55, '08-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'ADSL modem 10 May 16', 0, 0, 0, 165.00, '10-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Jun 16', 0, 0, 0, 81.77, '01-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 Jun 16', 0, 0, 0, 181.72, '08-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'Before 1 January 2016', '', '', '', 'Residential phones 6 Dec 15', 0, 0, 0, 63.55, '06-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '31 Mar 16 - Melbourne to Sydney', 0, 0, 0, 698.76, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '3 Apr 16 - Sydney to Melbourne', 0, 0, 0, 698.76, '03-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Gavin Marshall', 'Senator', '', 'Victoria', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2016', '', '', '', '24 Nov 15 - Canberra to Melbourne', 0, 0, 0, 405.05, '24-Nov-2015', '', '');
