INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 12, 273.00, 0, 3276.00, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '13-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Melbourne', 'Public Works', 1, 379.00, 0, 379.00, '04-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '31 Jan 16 - Perth to Melbourne', 0, 0, 0, 1333.31, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '31 Jan 16 - Melbourne to Canberra', 0, 0, 0, 0, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '12 Feb 16 - Canberra to Melbourne', 0, 0, 0, 1632.53, '12-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '12 Feb 16 - Melbourne to Perth', 0, 0, 0, 0, '12-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Feb 16 - Perth to Melbourne', 0, 0, 0, 1620.52, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Feb 16 - Melbourne to Canberra', 0, 0, 0, 0, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '26 Feb 16 - Canberra to Melbourne', 0, 0, 0, 1632.53, '26-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '26 Feb 16 - Melbourne to Perth', 0, 0, 0, 0, '26-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '28 Feb 16 - Perth to Sydney', 0, 0, 0, 1638.37, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '28 Feb 16 - Sydney to Canberra', 0, 0, 0, 0, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Mar 16 - Canberra to Sydney', 0, 0, 0, 1633.60, '04-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Mar 16 - Sydney to Perth', 0, 0, 0, 0, '04-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '13 Mar 16 - Perth to Melbourne', 0, 0, 0, 1633.60, '13-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '13 Mar 16 - Melbourne to Canberra', 0, 0, 0, 0, '13-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Apr 16 - Perth to Melbourne', 0, 0, 0, 1019.10, '04-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '5 Apr 16 - Melbourne to Perth', 0, 0, 0, 1019.10, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Apr 16 - Perth to Melbourne', 0, 0, 0, 1334.38, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Apr 16 - Melbourne to Canberra', 0, 0, 0, 0, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '20 Apr 16 - Canberra to Melbourne', 0, 0, 0, 1334.38, '20-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '20 Apr 16 - Melbourne to Perth', 0, 0, 0, 0, '20-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Perth to Sydney', 0, 0, 0, 1639.44, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Sydney to Canberra', 0, 0, 0, 0, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Melbourne', 0, 0, 0, 1633.60, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Melbourne to Perth', 0, 0, 0, 0, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 1 Jan to 23 Jan 16', 0, 0, 0, 217.48, '23-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Car cleaning 6 Jan 16', 0, 0, 0, 16.36, '06-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 Jan to 17 Feb 16', 0, 0, 0, 862.78, '17-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 30 Jan to 27 Feb 16', 0, 0, 0, 225.22, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 Feb to 17 Mar 16', 0, 0, 0, 862.78, '17-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 5 Mar to 28 Mar 16', 0, 0, 0, 172.05, '28-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Car cleaning 9 Mar 16', 0, 0, 0, 16.36, '09-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 18 Mar to 17 Apr 16', 0, 0, 0, 862.78, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 1 Apr to 22 Apr 16', 0, 0, 0, 152.04, '22-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 Apr to 17 May 16', 0, 0, 0, 862.78, '17-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Car cleaning 21 Apr 16', 0, 0, 0, 16.36, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 28 Apr to 29 May 16', 0, 0, 0, 202.00, '29-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 18 May to 17 Jun 16', 0, 0, 0, 862.78, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Car cleaning 22 May 16', 0, 0, 0, 16.36, '22-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Fuel 8 Dec to 27 Dec 15', 0, 0, 0, 168.89, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Car cleaning 8 Dec 15', 0, 0, 0, 16.44, '08-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Lease 18 Dec 15 to 17 Jan 16', 0, 0, 0, 862.78, '18-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '31 Jan 16 - Perth', 0, 0, 0, 78.60, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '7 Feb 16 - Canberra', 0, 0, 0, 78.60, '07-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '12 Feb 16 - Perth', 0, 0, 0, 60.26, '12-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Feb 16 - Perth', 0, 0, 0, 78.60, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '26 Feb 16 - Perth', 0, 0, 0, 61.57, '26-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Feb 16 - Perth', 0, 0, 0, 78.60, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Feb 16 - Canberra', 0, 0, 0, 80.40, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '2 Mar 16 - Canberra', 0, 0, 0, 40.00, '02-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 Mar 16 - Perth', 0, 0, 0, 133.62, '04-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '13 Mar 16 - Perth', 0, 0, 0, 78.60, '13-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '18 Mar 16 - Canberra', 0, 0, 0, 40.00, '18-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '18 Mar 16 - Perth', 0, 0, 0, 121.83, '18-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 Apr 16 - Perth', 0, 0, 0, 56.33, '04-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '4 Apr 16 - Melbourne', 0, 0, 0, 55.29, '04-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '5 Apr 16 - Melbourne', 0, 0, 0, 64.66, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '5 Apr 16 - Perth', 0, 0, 0, 57.64, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Apr 16 - Perth', 0, 0, 0, 78.60, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '20 Apr 16 - Canberra', 0, 0, 0, 40.00, '20-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '20 Apr 16 - Perth', 0, 0, 0, 93.01, '20-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 May 16 - Perth', 0, 0, 0, 78.60, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 May 16 - Canberra', 0, 0, 0, 80.40, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 May 16 - Perth', 0, 0, 0, 64.19, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 86720.74, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 4150.36, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 16', 0, 0, 0, 63.45, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Flags 1 Jan to 31 Jan 16', 0, 0, 0, 804.63, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 19 Jan 16', 0, 0, 0, 33.00, '19-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', '1 Toner cartridge 27 Jan 16', 0, 0, 0, 146.00, '27-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 67.73, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 16.72, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Feb to 29 Feb 16', 0, 0, 0, 181.85, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 2 Feb 16', 0, 0, 0, 22.00, '02-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 16 Feb 16', 0, 0, 0, 22.00, '16-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 70.62, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 12.76, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 1 Mar 16', 0, 0, 0, 22.00, '01-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 15 Mar 16', 0, 0, 0, 22.00, '15-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 77.55, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 5.46, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Apr to 30 Apr 16', 0, 0, 0, 378.31, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 12 Apr 16', 0, 0, 0, 33.00, '12-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Apr to 27 May 16', 0, 0, 0, 890.13, '27-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Apr to 27 May 16', 0, 0, 0, 7.84, '27-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 30 Apr 16 to 29 Apr 17', 0, 0, 0, 81.82, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 10 May 16', 0, 0, 0, 33.00, '10-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 7 Jun 16', 0, 0, 0, 33.00, '07-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 7 Sep 13 to 30 Jun 14', 0, 0, 0, -70.80, '07-Sep-2013', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 14 to 30 Jun 15', 0, 0, 0, -2992.49, '01-Jul-2014', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Reimbursement of price cap overspend 28 Jun to 27 Jul 15', 0, 0, 0, -4567.92, '27-Jul-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 15 to 31 Mar 16', 0, 0, 0, -1076.94, '01-Jul-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 34.46, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 13.25, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 15', 0, 0, 0, 177.82, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Water refills 22 Dec 15', 0, 0, 0, 22.00, '22-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 78.06, '28-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 9.35, '28-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Jan to 31 Jan 16', 0, 0, 0, 184.18, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Jan to 31 Jan 16', 0, 0, 0, -4.55, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 12 Jan 16', 0, 0, 0, 399.30, '12-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 21 Jan 16', 0, 0, 0, 454.50, '21-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 26 Jan 16', 0, 0, 0, 1197.90, '26-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '2,500 Personalised letterhead stationery 28 Jan 16', 0, 0, 0, 550.00, '28-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Feb to 29 Feb 16', 0, 0, 0, 512.46, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Feb to 29 Feb 16', 0, 0, 0, -4.55, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 9 Feb 16', 0, 0, 0, 399.30, '09-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 23 Feb 16', 0, 0, 0, 399.30, '23-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Mar to 31 Mar 16', 0, 0, 0, 6791.34, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Mar to 31 Mar 16', 0, 0, 0, -9.09, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 8 Mar 16', 0, 0, 0, 399.30, '08-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 15 Mar 16', 0, 0, 0, 700.00, '15-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 22 Mar 16', 0, 0, 0, 399.30, '22-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 23 Mar 16', 0, 0, 0, 204.55, '23-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '8,541 Personalised letterhead stationery 28 Mar 16', 0, 0, 0, 480.00, '28-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '25,623 Printed items 30 Mar 16', 0, 0, 0, 3450.00, '30-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 31 Mar 16', 0, 0, 0, 1300.00, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Apr to 30 Apr 16', 0, 0, 0, 604.15, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 5 Apr 16', 0, 0, 0, 399.30, '05-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 19 Apr 16', 0, 0, 0, 1863.40, '19-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 21 Apr 16', 0, 0, 0, 1575.60, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 May to 31 May 16', 0, 0, 0, 1228.27, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 3 May 16', 0, 0, 0, 399.30, '03-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '56,967 Postal vote applications 16 May 16', 0, 0, 0, 2452.51, '16-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '113,934 Printed items 16 May 16', 0, 0, 0, 2303.48, '16-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 16 May 16', 0, 0, 0, 2183.84, '16-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 17 May 16', 0, 0, 0, 1064.80, '17-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 31 May 16', 0, 0, 0, 399.30, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 1 Dec to 31 Dec 15', 0, 0, 0, 575.42, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution credit 1 Dec to 31 Dec 15', 0, 0, 0, -4.55, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 1 Dec 15', 0, 0, 0, 248.67, '01-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Jan 16', 0, 0, 0, 365.01, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Jan 16', 0, 0, 0, 32.50, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Feb 16', 0, 0, 0, 318.54, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Feb 16', 0, 0, 0, 32.14, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 3 Mar 16', 0, 0, 0, 327.75, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 3 Mar 16', 0, 0, 0, 32.64, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Apr 16', 0, 0, 0, 339.50, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Apr 16', 0, 0, 0, 32.63, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 2 May 16', 0, 0, 0, 417.35, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 2 May 16', 0, 0, 0, 32.50, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Jun 16', 0, 0, 0, 341.79, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Jun 16', 0, 0, 0, 31.90, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 Jan 16', 0, 0, 0, 81.61, '11-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Jan 16', 0, 0, 0, 63.59, '15-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 Feb 16', 0, 0, 0, 51.66, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Feb 16', 0, 0, 0, 63.59, '15-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 14 Mar 16', 0, 0, 0, 84.35, '14-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Mar 16', 0, 0, 0, 63.59, '15-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 Apr 16', 0, 0, 0, 105.74, '11-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Apr 16', 0, 0, 0, 63.59, '15-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 May 16', 0, 0, 0, 67.75, '11-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 May 16', 0, 0, 0, 63.59, '15-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 11 Jun 16', 0, 0, 0, 70.55, '11-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Jun 16', 0, 0, 0, 63.59, '15-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Perth to Sydney', 0, 0, 0, 1639.44, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Sydney to Canberra', 0, 0, 0, 0, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Melbourne', 0, 0, 0, 1633.60, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Melbourne to Perth', 0, 0, 0, 0, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Perth to Sydney', 0, 0, 0, 1639.44, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Sydney to Canberra', 0, 0, 0, 0, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Melbourne', 0, 0, 0, 1633.60, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Melbourne to Perth', 0, 0, 0, 0, '06-May-2016', '');
