INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Adelaide', 'Electorate Business', 3, 359.00, 0, 1077.00, '19-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 1, 273.00, 0, 273.00, '10-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 11, 273.00, 0, 3003.00, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 273.00, 0, 819.00, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Sydney', 'Electorate Business', 1, 133.00, 0, 133.00, '25-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2016', '', '', '', '', 0, 0, 0, 1855.16, '01-Jan-1900', 'OS Study - Fares', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '19 Jan 16 - Melbourne to Adelaide', 0, 0, 0, 418.00, '19-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '25 Jan 16 - Adelaide to Melbourne', 0, 0, 0, 418.00, '25-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '10 Feb 16 - Sydney to Canberra', 0, 0, 0, 328.20, '10-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '11 Feb 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '11-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '13 Feb 16 - Melbourne to Sydney', 0, 0, 0, 780.82, '13-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '13 Feb 16 - Sydney to Melbourne', 0, 0, 0, 446.15, '13-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Feb 16 - Melbourne to Canberra', 0, 0, 0, 686.29, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '3 Mar 16 - Canberra to Melbourne', 0, 0, 0, 409.90, '03-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '10 Mar 16 - Melbourne to Canberra', 0, 0, 0, 686.29, '10-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '10 Mar 16 - Canberra to Melbourne', 0, 0, 0, 217.51, '10-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '14 Mar 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '19 Mar 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '19-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '8 Apr 16 - Orange to Sydney', 0, 0, 0, 389.73, '08-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '8 Apr 16 - Sydney to Melbourne', 0, 0, 0, 780.82, '08-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '9 Apr 16 - Melbourne to Canberra', 0, 0, 0, 409.90, '09-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Apr 16 - Melbourne to Canberra', 0, 0, 0, 686.29, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '20 Apr 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '20-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Melbourne', 0, 0, 0, 245.30, '06-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '25 May 16 - Melbourne to Sydney', 0, 0, 0, 780.82, '25-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '26 May 16 - Sydney to Melbourne', 0, 0, 0, 780.82, '26-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 2 Jan to 25 Jan 16', 0, 0, 0, 491.28, '25-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 12 Jan to 11 Feb 16', 0, 0, 0, 1297.65, '11-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 30 Jan to 26 Feb 16', 0, 0, 0, 357.70, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 12 Feb to 11 Mar 16', 0, 0, 0, 1297.65, '11-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 28 Feb to 28 Mar 16', 0, 0, 0, 396.49, '28-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 12 Mar to 11 Apr 16', 0, 0, 0, 1297.65, '11-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 23 Mar to 26 Apr 16', 0, 0, 0, 635.22, '26-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 12 Apr to 11 May 16', 0, 0, 0, 1297.65, '11-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Fuel 3 May to 25 May 16', 0, 0, 0, 387.22, '25-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2016', '', '', '', 'Lease 12 May to 11 Jun 16', 0, 0, 0, 1297.65, '11-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Fuel 24 Nov to 26 Dec 15', 0, 0, 0, 531.33, '26-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2016', '', '', '', 'Lease 12 Dec 15 to 11 Jan 16', 0, 0, 0, 1297.65, '12-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Jan 16 - Melbourne', 0, 0, 0, 48.05, '19-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Jan 16 - Adelaide', 0, 0, 0, 80.40, '19-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '20 Jan 16 - Adelaide', 0, 0, 0, 48.47, '20-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '20 Jan 16 - Adelaide', 0, 0, 0, 40.00, '20-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '20 Jan 16 - Adelaide', 0, 0, 0, 86.46, '20-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Jan 16 - Adelaide', 0, 0, 0, 40.00, '25-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 Jan 16 - Melbourne', 0, 0, 0, 49.16, '25-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '30 Jan 16 - Melbourne', 0, 0, 0, 78.60, '30-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '10 Feb 16 - Canberra', 0, 0, 0, 41.80, '10-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '11 Feb 16 - Melbourne', 0, 0, 0, 80.60, '11-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '13 Feb 16 - Melbourne', 0, 0, 0, 78.60, '13-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '13 Feb 16 - Sydney', 0, 0, 0, 93.10, '13-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '13 Feb 16 - Sydney', 0, 0, 0, 78.60, '13-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '13 Feb 16 - Melbourne', 0, 0, 0, 80.60, '13-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Feb 16 - Melbourne', 0, 0, 0, 78.60, '21-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '26 Feb 16 - Canberra', 0, 0, 0, 40.00, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '3 Mar 16 - Canberra', 0, 0, 0, 40.00, '03-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '10 Mar 16 - Melbourne', 0, 0, 0, 49.78, '10-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '10 Mar 16 - Canberra', 0, 0, 0, 41.80, '10-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '10 Mar 16 - Canberra', 0, 0, 0, 40.00, '10-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '10 Mar 16 - Melbourne', 0, 0, 0, 42.00, '10-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '14 Mar 16 - Melbourne', 0, 0, 0, 78.60, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Mar 16 - Melbourne', 0, 0, 0, 80.60, '19-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '8 Apr 16 - Melbourne', 0, 0, 0, 51.78, '08-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '9 Apr 16 - Melbourne', 0, 0, 0, 85.70, '09-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Apr 16 - Melbourne', 0, 0, 0, 78.60, '17-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '20 Apr 16 - Canberra', 0, 0, 0, 40.00, '20-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '20 Apr 16 - Melbourne', 0, 0, 0, 42.00, '20-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 May 16 - Melbourne', 0, 0, 0, 78.60, '01-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '5 May 16 - Canberra', 0, 0, 0, 40.61, '05-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 May 16 - Melbourne', 0, 0, 0, 97.21, '06-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 May 16 - Melbourne', 0, 0, 0, 41.92, '25-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '25 May 16 - Sydney', 0, 0, 0, 43.60, '25-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '26 May 16 - Sydney', 0, 0, 0, 40.00, '26-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '26 May 16 - Melbourne', 0, 0, 0, 47.85, '26-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '21 Dec 15 - Melbourne', 0, 0, 0, 58.95, '21-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '21 Dec 15 - Melbourne', 0, 0, 0, 45.85, '21-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 January 2016', '', '', '', 'Taxi 3 Mar 16', 0, 0, 0, 53.35, '03-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 46776.83, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 35902.83, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 16', 0, 0, 0, 264.22, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Flags 1 Jan to 31 Jan 16', 0, 0, 0, 96.00, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 85.11, '27-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 11.82, '27-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Feb to 29 Feb 16', 0, 0, 0, 85.89, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Flags 1 Feb to 29 Feb 16', 0, 0, 0, 437.70, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Freight costs 7 Feb 16', 0, 0, 0, 560.00, '07-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 377.87, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 8.23, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 516.16, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 9.17, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Apr to 30 Apr 16', 0, 0, 0, 36.25, '30-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Flags 1 Apr to 30 Apr 16', 0, 0, 0, 1283.70, '30-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Apr to 27 May 16', 0, 0, 0, 310.53, '27-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Apr to 27 May 16', 0, 0, 0, 4.99, '27-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 333.71, '27-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 10.08, '27-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 15', 0, 0, 0, 419.51, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 893.59, '28-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 10.63, '28-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Jan to 31 Jan 16', 0, 0, 0, 17418.89, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Jan to 31 Jan 16', 0, 0, 0, -7409.54, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Jan 16', 0, 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 11 Jan 16', 0, 0, 0, 3974.40, '11-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Feb to 29 Feb 16', 0, 0, 0, 2727.27, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Feb to 29 Feb 16', 0, 0, 0, -68.18, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Feb 16', 0, 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 6 Feb 16', 0, 0, 0, 626.08, '06-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 8 Feb 16', 0, 0, 0, 3974.40, '08-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Mar to 31 Mar 16', 0, 0, 0, 2727.27, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Mar to 31 Mar 16', 0, 0, 0, -68.18, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Mar 16', 0, 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 14 Mar 16', 0, 0, 0, 3974.40, '14-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 28 Mar to 24 Apr 16', 0, 0, 0, 308.25, '24-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '59,000 Printed items 31 Mar 16', 0, 0, 0, 3750.47, '31-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'PO Box 124 rental 1 Apr 16 to 31 Mar 17', 0, 0, 0, 164.55, '01-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 1 Apr to 30 Apr 16', 0, 0, 0, 17522.68, '30-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution credit 1 Apr to 30 Apr 16', 0, 0, 0, -68.18, '30-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution late payment fee Apr 16', 0, 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '57,000 Printed items 27 Apr 16', 0, 0, 0, 2628.00, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '57,000 Printed items 27 Apr 16', 0, 0, 0, 4466.00, '27-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 28 Apr 16', 0, 0, 0, 695.00, '28-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Web-services 28 Apr 16', 0, 0, 0, 435.00, '28-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 16 May 16', 0, 0, 0, 964.80, '16-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 23 May 16', 0, 0, 0, 964.80, '23-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 30 May 16', 0, 0, 0, 964.80, '30-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 12 Oct 15', 0, 0, 0, 3974.40, '12-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Printing 27 Oct 15', 0, 0, 0, 1134.00, '27-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '500 Personalised letterhead stationery 30 Oct 15', 0, 0, 0, 320.00, '30-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 1 Nov to 30 Nov 15', 0, 0, 0, 2727.27, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution credit 1 Nov to 30 Nov 15', 0, 0, 0, -68.18, '30-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution late payment fee Nov 15', 0, 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 9 Nov 15', 0, 0, 0, 3974.40, '09-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '5,000 Printed items 24 Nov 15', 0, 0, 0, 1996.88, '24-Nov-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution 1 Dec to 31 Dec 15', 0, 0, 0, 12.14, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', 'Distribution credit 1 Dec to 31 Dec 15', 0, 0, 0, 15.00, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1,000 Printed items 10 Dec 15', 0, 0, 0, 1228.50, '10-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 10 Dec 15', 0, 0, 0, 782.00, '10-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '56,500 Printed items 14 Dec 15', 0, 0, 0, 26841.00, '14-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 14 Dec 15', 0, 0, 0, 3974.40, '14-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1,000 Printed items 15 Dec 15', 0, 0, 0, 2975.25, '15-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 21 Dec 15', 0, 0, 0, 695.00, '21-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '1 Printed item 23 Dec 15', 0, 0, 0, 300.00, '23-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '5 Sunday Herald Sun 4 Jan to 31 Jan 16', 0, 0, 0, 12.27, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '5 The Economist 4 Jan to 31 Jan 16', 0, 0, 0, 50.00, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 Herald Sun (Sat) 4 Jan to 31 Jan 16', 0, 0, 0, 8.00, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '3 The Sunday Age 4 Jan to 31 Jan 16', 0, 0, 0, 13.64, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Saturday Age 4 Jan to 31 Jan 16', 0, 0, 0, 12.73, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Weekend Australian 4 Jan to 31 Jan 16', 0, 0, 0, 12.73, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 4 Jan to 31 Jan 16', 0, 0, 0, 18.62, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '21 The Age 4 Jan to 31 Jan 16', 0, 0, 0, 47.73, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 4 Jan to 31 Jan 16', 0, 0, 0, 69.09, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '21 The Australian 4 Jan to 31 Jan 16', 0, 0, 0, 51.55, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '21 Herald Sun 4 Jan to 31 Jan 16', 0, 0, 0, 26.73, '31-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '5 Herald Sun 1 Feb to 28 Feb 16', 0, 0, 0, 6.36, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 Herald Sun (Sat) 1 Feb to 28 Feb 16', 0, 0, 0, 8.00, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Saturday Age 1 Feb to 28 Feb 16', 0, 0, 0, 12.73, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 Sunday Herald Sun 1 Feb to 28 Feb 16', 0, 0, 0, 9.82, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Economist 1 Feb to 28 Feb 16', 0, 0, 0, 40.00, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Sunday Age 1 Feb to 28 Feb 16', 0, 0, 0, 10.91, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Weekend Australian 1 Feb to 28 Feb 16', 0, 0, 0, 12.73, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 1 Feb to 28 Feb 16', 0, 0, 0, 18.62, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 1 Feb to 28 Feb 16', 0, 0, 0, 72.73, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '15 Herald Sun 1 Feb to 28 Feb 16', 0, 0, 0, 20.45, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Age 1 Feb to 28 Feb 16', 0, 0, 0, 45.45, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 1 Feb to 28 Feb 16', 0, 0, 0, 49.09, '28-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 Herald Sun (Sat) 29 Feb to 27 Mar 16', 0, 0, 0, 8.00, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 Sunday Herald Sun 29 Feb to 27 Mar 16', 0, 0, 0, 9.82, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Saturday Age 29 Feb to 27 Mar 16', 0, 0, 0, 12.73, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Economist 29 Feb to 27 Mar 16', 0, 0, 0, 40.00, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Weekend Australian 29 Feb to 27 Mar 16', 0, 0, 0, 12.73, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '4 The Sunday Age 29 Feb to 27 Mar 16', 0, 0, 0, 10.91, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', 'Administrative fees 29 Feb to 27 Mar 16', 0, 0, 0, 18.44, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '19 The Australian 29 Feb to 27 Mar 16', 0, 0, 0, 46.64, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '19 The Australian Financial Review 29 Feb to 27 Mar 16', 0, 0, 0, 69.09, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Age 29 Feb to 27 Mar 16', 0, 0, 0, 45.45, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 Herald Sun 29 Feb to 27 Mar 16', 0, 0, 0, 27.27, '27-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '3 The Economist 7 Dec to 31 Dec 15', 0, 0, 0, 31.82, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', 'Administrative fees 7 Dec to 31 Dec 15', 0, 0, 0, 11.54, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '13 The Australian Financial Review 7 Dec to 31 Dec 15', 0, 0, 0, 44.91, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '13 Herald Sun 7 Dec to 31 Dec 15', 0, 0, 0, 16.55, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '13 The Australian 7 Dec to 31 Dec 15', 0, 0, 0, 31.91, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '13 The Age 7 Dec to 31 Dec 15', 0, 0, 0, 29.55, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '2 Herald Sun (Sat) 7 Dec to 31 Dec 15', 0, 0, 0, 4.00, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '2 The Saturday Age 7 Dec to 31 Dec 15', 0, 0, 0, 6.36, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '2 Sunday Herald Sun 7 Dec to 31 Dec 15', 0, 0, 0, 4.91, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '2 The Sunday Age 7 Dec to 31 Dec 15', 0, 0, 0, 5.45, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '2 The Weekend Australian 7 Dec to 31 Dec 15', 0, 0, 0, 6.36, '31-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Directory charges 1 Jan to 31 Dec 16', 0, 0, 0, 3936.90, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Jan 16', 0, 0, 0, 250.65, '26-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Jan 16', 0, 0, 0, 32.50, '26-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 25 Feb 16', 0, 0, 0, 60.00, '25-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Feb 16', 0, 0, 0, 288.27, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Feb 16', 0, 0, 0, 32.63, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Mar 16', 0, 0, 0, 242.35, '26-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Mar 16', 0, 0, 0, 32.14, '26-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 Apr 16', 0, 0, 0, 266.15, '26-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 Apr 16', 0, 0, 0, 32.14, '26-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 26 May 16', 0, 0, 0, 282.22, '26-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 26 May 16', 0, 0, 0, 32.40, '26-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office phones 5 Oct 15', 0, 0, 0, 50.00, '05-Oct-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office phones 26 Dec 15', 0, 0, 0, 357.38, '26-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2016', '', '', '', 'Office fax 26 Dec 15', 0, 0, 0, 32.86, '26-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 1 Mar 16', 0, 0, 0, 270.00, '01-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 30 Mar 16', 0, 0, 0, 50.00, '30-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 Apr 16', 0, 0, 0, 95.71, '08-Apr-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 May 16', 0, 0, 0, 922.95, '08-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 1 Jun 16', 0, 0, 0, 159.62, '01-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Residential phones 8 Jun 16', 0, 0, 0, 76.25, '08-Jun-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '19 Jan 16 - Melbourne to Adelaide', 0, 0, 0, 418.00, '19-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '25 Jan 16 - Adelaide to Melbourne', 0, 0, 0, 418.00, '25-Jan-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '26 Feb 16 - Melbourne to Canberra', 0, 0, 0, 420.36, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '29 Feb 16 - Canberra to Melbourne', 0, 0, 0, 409.90, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '17 Mar 16 - Melbourne to Canberra', 0, 0, 0, 409.90, '17-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '19 Mar 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '19-Mar-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '25 May 16 - Melbourne to Sydney', 0, 0, 0, 780.82, '25-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '26 May 16 - Sydney to Melbourne', 0, 0, 0, 780.82, '26-May-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2016', '', '', '', '3 Dec 15 - Melbourne to Canberra', 0, 0, 0, 405.05, '03-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2016', '', '', '', '4 Dec 15 - Canberra to Melbourne', 0, 0, 0, 405.05, '04-Dec-2015', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '26 Feb 16 - Melbourne', 0, 0, 0, 53.71, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '26 Feb 16 - Canberra', 0, 0, 0, 41.80, '26-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '29 Feb 16 - Melbourne', 0, 0, 0, 46.54, '29-Feb-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Type, Notes)
VALUES ('Kevin Andrews', 'Representative', 'Menzies', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '17 Mar 16 - Melbourne', 0, 0, 0, 82.53, '17-Mar-2016', '', '');
