INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Melbourne', 'Electorate Business', 2, 379.00, 0, 758.00, '04-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Official Government or Vice-Regal Function', 1, 273.00, 0, 273.00, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Senate Estimates', 4, 273.00, 0, 1092.00, '07-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Sydney', 'Trade and Investment Growth', 2, 397.00, 0, 794.00, '07-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Melbourne', 'Trade and Investment Growth', 1, 379.00, 0, 379.00, '09-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 273.00, 0, 1365.00, '14-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Brisbane', 'Community Affairs', 1, 408.00, 0, 408.00, '14-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '17-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 273.00, 0, 1092.00, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2016', '', '', 'Melbourne', 'Electorate Business', 1, 379.00, 0, 379.00, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '31 Jan 16 - Perth to Canberra', 0, 0, 0, 1623.59, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '4 Feb 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '04-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 Feb 16 - Melbourne to Canberra', 0, 0, 0, 409.90, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '11 Feb 16 - Canberra to Perth', 0, 0, 0, 1623.59, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Feb 16 - Perth to Canberra', 0, 0, 0, 1623.59, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '26 Feb 16 - Canberra to Sydney', 0, 0, 0, 1638.37, '26-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '26 Feb 16 - Sydney to Perth', 0, 0, 0, 0, '26-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '28 Feb 16 - Perth to Canberra', 0, 0, 0, 1623.59, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '3 Mar 16 - Canberra to Perth', 0, 0, 0, 803.37, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '7 Mar 16 - Perth to Sydney', 0, 0, 0, 1941.35, '07-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '9 Mar 16 - Sydney to Melbourne', 0, 0, 0, 780.82, '09-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '10 Mar 16 - Melbourne to Perth', 0, 0, 0, 1892.88, '10-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '12 Mar 16 - Perth to Canberra', 0, 0, 0, 1624.54, '12-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '19 Mar 16 - Canberra to Sydney', 0, 0, 0, 1639.44, '19-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '19 Mar 16 - Sydney to Perth', 0, 0, 0, 0, '19-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '14 Apr 16 - Perth to Brisbane', 0, 0, 0, 1843.32, '14-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '15 Apr 16 - Brisbane to Canberra', 0, 0, 0, 469.90, '15-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '21 Apr 16 - Canberra to Perth', 0, 0, 0, 1624.54, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '27 Apr 16 - Perth to Sydney', 0, 0, 0, 1941.35, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '28 Apr 16 - Sydney to Perth', 0, 0, 0, 1941.35, '28-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '1 May 16 - Perth to Canberra', 0, 0, 0, 804.44, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '6 May 16 - Canberra to Melbourne', 0, 0, 0, 686.29, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '7 May 16 - Melbourne to Perth', 0, 0, 0, 1892.89, '07-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '16 Jun 16 - Perth to Albany', 0, 0, 0, 296.76, '16-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Jun 16 - Albany to Perth', 0, 0, 0, 296.76, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '17 Jun 16 - Perth to Brisbane', 0, 0, 0, 1913.32, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2016', '', '', '', '26 Jun 16 - Perth to Kalgoorlie', 0, 0, 0, 378.34, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '31 Jan 16 - Perth', 0, 0, 0, 78.60, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 Feb 16 - Canberra', 0, 0, 0, 80.40, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '7 Feb 16 - Canberra', 0, 0, 0, 78.60, '07-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '7 Feb 16 - Canberra', 0, 0, 0, 78.60, '07-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Feb 16 - Perth', 0, 0, 0, 78.60, '21-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '26 Feb 16 - Perth', 0, 0, 0, 40.00, '26-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Feb 16 - Perth', 0, 0, 0, 78.60, '28-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '3 Mar 16 - Perth', 0, 0, 0, 62.88, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '7 Mar 16 - Perth', 0, 0, 0, 78.60, '07-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '7 Mar 16 - Sydney', 0, 0, 0, 49.70, '07-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '9 Mar 16 - Sydney', 0, 0, 0, 52.40, '09-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '9 Mar 16 - Melbourne', 0, 0, 0, 60.11, '09-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '10 Mar 16 - Melbourne', 0, 0, 0, 88.66, '10-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '10 Mar 16 - Perth', 0, 0, 0, 40.00, '10-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '12 Mar 16 - Perth', 0, 0, 0, 78.60, '12-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '12 Mar 16 - Canberra', 0, 0, 0, 80.40, '12-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Mar 16 - Canberra', 0, 0, 0, 78.60, '19-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '19 Mar 16 - Perth', 0, 0, 0, 78.60, '19-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '31 Mar 16 - Perth', 0, 0, 0, 40.00, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '31 Mar 16 - Perth', 0, 0, 0, 40.00, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '14 Apr 16 - Brisbane', 0, 0, 0, 50.90, '14-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '15 Apr 16 - Canberra', 0, 0, 0, 41.80, '15-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Apr 16 - Canberra', 0, 0, 0, 40.00, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Apr 16 - Canberra', 0, 0, 0, 40.00, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '21 Apr 16 - Perth', 0, 0, 0, 40.61, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '27 Apr 16 - Sydney', 0, 0, 0, 49.80, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '28 Apr 16 - Sydney', 0, 0, 0, 57.64, '28-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '1 May 16 - Perth', 0, 0, 0, 78.60, '01-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'From 1 January 2016', '', '', '', '6 May 16 - Melbourne', 0, 0, 0, 44.20, '06-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'COMCAR', 'Before 1 January 2016', '', '', '', '15 Dec 15 - Perth', 0, 0, 0, 40.00, '15-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '6 Feb 16', 0, 0, 0, 55.72, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '11 Feb 16', 0, 0, 0, 52.75, '11-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '13 Mar 16', 0, 0, 0, 12.82, '13-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '13 Mar 16', 0, 0, 0, 16.55, '13-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '7 May 16', 0, 0, 0, 47.47, '07-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Cabcharge', 'From 1 January 2016', '', '', '', '17 Jun 16', 0, 0, 0, 54.89, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Other Car Costs', 'From 1 January 2016', '', '', '', 'Toll charges between 4 Feb and 6 Feb 16', 0, 0, 0, 16.59, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Other Car Costs', 'From 1 January 2016', '', '', '', 'Toll charges (services fee) between 4 Feb and 6 Feb 16', 0, 0, 0, 9.00, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Other Car Costs', 'From 1 January 2016', '', '', '', 'Melbourne 4 Feb to 6 Feb 16', 0, 0, 0, 257.46, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Car Costs', 'Other Car Costs', 'From 1 January 2016', '', '', '', 'Fuel charge 6 Feb 16', 0, 0, 0, 36.46, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 68825.90, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 12777.46, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 4.98, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 16', 0, 0, 0, 0.34, '27-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Feb to 29 Feb 16', 0, 0, 0, 628.80, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 15.62, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Feb to 27 Mar 16', 0, 0, 0, 0.69, '27-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 2 Mar 16', 0, 0, 0, 42.00, '02-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 10.58, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Mar to 27 Apr 16', 0, 0, 0, 0.17, '27-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 Apr to 30 Apr 16', 0, 0, 0, 685.59, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 13 Apr 16', 0, 0, 0, 42.00, '13-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Apr to 27 May 16', 0, 0, 0, 3.65, '27-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Apr to 27 May 16', 0, 0, 0, 0.12, '27-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Office requisites and stationery 1 May to 31 May 16', 0, 0, 0, 344.93, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Printer consumables 4 May 16', 0, 0, 0, 232.87, '04-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 13 May 16 to 13 May 17', 0, 0, 0, 81.82, '13-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2016', '', '', '', 'Water refills 1 Jun 16', 0, 0, 0, 42.00, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 14 to 30 Jun 15', 0, 0, 0, -356.03, '01-Jul-2014', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Toner cartridge credit 1 Jul 15 to 31 Mar 16', 0, 0, 0, -1172.57, '01-Jul-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 4.66, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 15', 0, 0, 0, 0.12, '27-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 15', 0, 0, 0, 218.85, '31-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Colour copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 14.05, '28-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2016', '', '', '', 'MFD Monochrome copy charge 28 Dec 15 to 27 Jan 16', 0, 0, 0, 0.21, '28-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 17 Mar 16', 0, 0, 0, 15.73, '17-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 23 Mar 16', 0, 0, 0, 12.18, '23-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'PO Box 6 rental 1 Apr 16 to 31 Mar 17', 0, 0, 0, 173.64, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '3 Printed items 15 Apr to 29 Apr 16', 0, 0, 0, 300.00, '29-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '10 Printed items 29 Apr 16', 0, 0, 0, 560.91, '29-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Printing 4 May 16', 0, 0, 0, 454.55, '04-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '2,000 Printed items 30 May 16', 0, 0, 0, 1617.91, '30-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 1 Jun 16', 0, 0, 0, 163.66, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', '1 Printed item 8 Jun 16', 0, 0, 0, 178.54, '08-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2016', '', '', '', 'Distribution 14 Jun to 15 Jun 16', 0, 0, 0, 30208.93, '15-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2016', '', '', '', '500 Printed items 16 Nov 15', 0, 0, 0, 452.74, '16-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '10 The West Australian 1 Jan to 31 Jan 2016', 0, 0, 0, 25.91, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '19 The Australian Financial Review 1 Jan to 31 Jan 16', 0, 0, 0, 65.64, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '19 The Australian 1 Jan to 31 Jan 16', 0, 0, 0, 46.64, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Australian Financial Review (digital) 19 Jan 16 to 18 Jan 17', 0, 0, 0, 275.89, '19-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '12 The Australian Financial Review 1 Feb to 29 Feb 16', 0, 0, 0, 43.64, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '12 The Australian 1 Feb to 29 Feb 16', 0, 0, 0, 29.45, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '12 The West Australian 1 Feb to 29 Feb 16', 0, 0, 0, 16.36, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '1 The Australian Financial Review (digital) 17 Feb 16 to 16 Feb 17', 0, 0, 0, 719.74, '17-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 1 Mar to 31 Mar 16', 0, 0, 0, 72.73, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The West Australian 1 Mar to 31 Mar 16', 0, 0, 0, 27.27, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 1 Mar to 31 Mar 16', 0, 0, 0, 49.09, '31-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian Financial Review 1 Apr to 30 Apr 16', 0, 0, 0, 72.73, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The West Australian 1 Apr to 30 Apr 16', 0, 0, 0, 27.27, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '20 The Australian 1 Apr to 30 Apr 16', 0, 0, 0, 49.09, '30-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '22 The West Australian 1 May to 31 May 16', 0, 0, 0, 30.00, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '22 The Australian Financial Review 1 May to 31 May 16', 0, 0, 0, 80.00, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2016', '', '', '', '22 The Australian 1 May to 31 May 16', 0, 0, 0, 54.00, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '15 The Australian 1 Dec to 30 Dec 15', 0, 0, 0, 36.82, '30-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '14 The Australian Financial Review 1 Dec to 30 Dec 15', 0, 0, 0, 48.36, '30-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2016', '', '', '', '15 The West Australian 1 Dec to 30 Dec 15', 0, 0, 0, 20.45, '30-Dec-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Jan 16', 0, 0, 0, 222.57, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Jan 16', 0, 0, 0, 32.86, '01-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 31 Jan 16', 0, 0, 0, 4.73, '31-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Feb 16', 0, 0, 0, 243.54, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Feb 16', 0, 0, 0, 32.14, '01-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 3 Mar 16', 0, 0, 0, 239.94, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 3 Mar 16', 0, 0, 0, 31.77, '03-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Apr 16', 0, 0, 0, 556.75, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Apr 16', 0, 0, 0, 32.14, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 2 May 16', 0, 0, 0, 141.20, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 2 May 16', 0, 0, 0, 31.77, '02-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office phones 1 Jun 16', 0, 0, 0, 293.45, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2016', '', '', '', 'Office fax 1 Jun 16', 0, 0, 0, 32.14, '01-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Jan 16', 0, 0, 0, 72.73, '15-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Feb 16', 0, 0, 0, 72.73, '15-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Mar 16', 0, 0, 0, 72.73, '15-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 Apr 16', 0, 0, 0, 72.73, '15-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2016', '', '', '', 'Dedicated data line 15 May 16', 0, 0, 0, 72.73, '15-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '5 Feb 16 - Perth to Melbourne', 0, 0, 0, 1891.94, '05-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '6 Feb 16 - Melbourne to Canberra', 0, 0, 0, 686.29, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '8 Feb 16 - Canberra to Melbourne', 0, 0, 0, 1632.53, '08-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '8 Feb 16 - Melbourne to Perth', 0, 0, 0, 0, '08-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '20 Jun 16 - Perth to Broome', 0, 0, 0, 713.11, '20-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '5 Feb 16 - Perth to Melbourne', 0, 0, 0, 1891.94, '05-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '6 Feb 16 - Melbourne to Canberra', 0, 0, 0, 409.90, '06-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '8 Feb 16 - Canberra to Melbourne', 0, 0, 0, 1632.53, '08-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '8 Feb 16 - Melbourne to Perth', 0, 0, 0, 0, '08-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Zhenya Wang', 'Senator', '', 'Western Australia', 'Palmer United Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2016', '', '', '', '20 Jun 16 - Perth to Broome', 0, 0, 0, 713.11, '20-Jun-2016', '');
