INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 273.00, 0, 273.00, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 273.00, 0, 273.00, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Sydney', 'Shadow Parliamentary Secretary - Official', 1, 397.00, 0, 397.00, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', '', 'Business', 0, 0, 0, 0, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Adelaide', 'Electoral Matters', 1, 362.00, 0, 362.00, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Perth', 'Electoral Matters', 1, 399.00, 0, 399.00, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '7 Jul 16 - Melbourne to Canberra', 0, 0, 0, 411.39, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '8 Jul 16 - Canberra to Melbourne', 0, 0, 0, 411.39, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Jul 16 - Melbourne to Canberra', 0, 0, 0, 411.39, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '22 Jul 16 - Canberra to Melbourne', 0, 0, 0, 411.39, '22-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '26 Jul 16 - Melbourne to Sydney', 0, 0, 0, 446.80, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Jul 16 - Sydney to Melbourne', 0, 0, 0, 446.80, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '4 Aug 16 - Melbourne to Adelaide', 0, 0, 0, 154.15, '04-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '5 Aug 16 - Adelaide to Melbourne', 0, 0, 0, 154.15, '05-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Aug 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '19 Aug 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '8 Sep 16 - Melbourne to Sydney', 0, 0, 0, 448.57, '08-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Sep 16 - Sydney to Melbourne', 0, 0, 0, 448.57, '09-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne to Canberra', 0, 0, 0, 245.30, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Melbourne', 0, 0, 0, 245.30, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '13 Oct 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Oct 16 - Melbourne to Brisbane', 0, 0, 0, 211.84, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Oct 16 - Brisbane to Melbourne', 0, 0, 0, 644.06, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Oct 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Oct 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Oct 16 - Melbourne to Sydney', 0, 0, 0, 448.57, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Oct 16 - Sydney to Melbourne', 0, 0, 0, 448.57, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Oct 16 - Melbourne to Sydney', 0, 0, 0, 448.57, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Oct 16 - Sydney to Melbourne', 0, 0, 0, 448.57, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Nov 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Nov 16 - Melbourne to Hobart', 0, 0, 0, 335.45, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Nov 16 - Hobart to Melbourne', 0, 0, 0, 394.28, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Nov 16 - Melbourne to Sydney', 0, 0, 0, 988.31, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Nov 16 - Sydney to Adelaide', 0, 0, 0, 0, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Nov 16 - Adelaide to Perth', 0, 0, 0, 799.39, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Nov 16 - Perth to Melbourne', 0, 0, 0, 874.65, '18-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Nov 16 - Canberra to Brisbane', 0, 0, 0, 203.37, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Nov 16 - Brisbane to Melbourne', 0, 0, 0, 644.06, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Dec 16 - Melbourne to Launceston', 0, 0, 0, 561.82, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Dec 16 - Launceston to Melbourne', 0, 0, 0, 0, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 8 Jul to 7 Aug 16', 0, 0, 0, 998.34, '07-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 8 Aug to 7 Sep 16', 0, 0, 0, 998.34, '07-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 8 Sep to 7 Oct 16', 0, 0, 0, 998.34, '07-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 8 Oct to 7 Nov 16', 0, 0, 0, 998.32, '07-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 8 Nov to 7 Dec 16', 0, 0, 0, 998.32, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Accident excess 10 Mar 16', 0, 0, 0, 500.00, '10-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Additional maintenance 10 Mar 16', 0, 0, 0, 678.25, '10-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Reimbursement of infringement notice fee 30 Mar 16', 0, 0, 0, -15.00, '30-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Infringement notice fee 8 May 16', 0, 0, 0, 15.00, '08-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Reimbursement of infringement notice fee 8 May 16', 0, 0, 0, -15.00, '08-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Accident excess 23 May 16', 0, 0, 0, 500.00, '23-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Lease 8 Jun to 7 Jul 16', 0, 0, 0, 998.34, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '7 Jul 16 - Melbourne', 0, 0, 0, 48.05, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '7 Jul 16 - Canberra', 0, 0, 0, 41.80, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Jul 16 - Canberra', 0, 0, 0, 40.00, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Jul 16 - Melbourne', 0, 0, 0, 47.43, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Jul 16 - Melbourne', 0, 0, 0, 84.73, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Jul 16 - Canberra', 0, 0, 0, 41.80, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Jul 16 - Canberra', 0, 0, 0, 78.60, '22-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Jul 16 - Canberra', 0, 0, 0, 40.00, '22-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Jul 16 - Melbourne', 0, 0, 0, 51.36, '22-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '26 Jul 16 - Melbourne', 0, 0, 0, 53.29, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '26 Jul 16 - Sydney', 0, 0, 0, 43.70, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Jul 16 - Sydney', 0, 0, 0, 57.64, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Jul 16 - Melbourne', 0, 0, 0, 48.74, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Aug 16 - Melbourne', 0, 0, 0, 45.43, '04-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Aug 16 - Adelaide', 0, 0, 0, 41.80, '04-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Aug 16 - Adelaide', 0, 0, 0, 40.00, '04-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Aug 16 - Melbourne', 0, 0, 0, 50.05, '04-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Aug 16 - Melbourne', 0, 0, 0, 57.22, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Aug 16 - Canberra', 0, 0, 0, 41.80, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '19 Aug 16 - Canberra', 0, 0, 0, 40.00, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '19 Aug 16 - Melbourne', 0, 0, 0, 47.85, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '1 Sep 16 - Melbourne', 0, 0, 0, 48.74, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Sep 16 - Sydney', 0, 0, 0, 43.70, '08-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Sep 16 - Sydney', 0, 0, 0, 40.00, '09-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne', 0, 0, 0, 80.80, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne', 0, 0, 0, 55.29, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Melbourne', 0, 0, 0, 55.91, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '7 Oct 16 - Sydney', 0, 0, 0, 97.92, '07-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne', 0, 0, 0, 80.80, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '13 Oct 16 - Melbourne', 0, 0, 0, 51.36, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Melbourne', 0, 0, 0, 100.45, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Melbourne', 0, 0, 0, 44.81, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Oct 16 - Melbourne', 0, 0, 0, 80.80, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Oct 16 - Melbourne', 0, 0, 0, 48.74, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Oct 16 - Melbourne', 0, 0, 0, 66.39, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Oct 16 - Sydney', 0, 0, 0, 50.00, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Oct 16 - Sydney', 0, 0, 0, 44.90, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Oct 16 - Melbourne', 0, 0, 0, 48.74, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Oct 16 - Melbourne', 0, 0, 0, 42.20, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Oct 16 - Sydney', 0, 0, 0, 65.02, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Oct 16 - Sydney', 0, 0, 0, 44.54, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Oct 16 - Melbourne', 0, 0, 0, 57.91, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne', 0, 0, 0, 80.80, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Nov 16 - Canberra', 0, 0, 0, 40.00, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Nov 16 - Melbourne', 0, 0, 0, 60.53, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Melbourne', 0, 0, 0, 42.20, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Hobart', 0, 0, 0, 72.05, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Hobart', 0, 0, 0, 40.00, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Melbourne', 0, 0, 0, 46.12, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Nov 16 - Melbourne', 0, 0, 0, 42.00, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Nov 16 - Sydney', 0, 0, 0, 68.95, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Nov 16 - Sydney', 0, 0, 0, 40.00, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Nov 16 - Adelaide', 0, 0, 0, 41.80, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Nov 16 - Adelaide', 0, 0, 0, 40.00, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Nov 16 - Perth', 0, 0, 0, 40.00, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Nov 16 - Perth', 0, 0, 0, 204.36, '18-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Nov 16 - Melbourne', 0, 0, 0, 44.20, '18-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Nov 16 - Melbourne', 0, 0, 0, 80.80, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Nov 16 - Brisbane', 0, 0, 0, 50.90, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Nov 16 - Brisbane', 0, 0, 0, 61.63, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Nov 16 - Melbourne', 0, 0, 0, 48.74, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne', 0, 0, 0, 80.80, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Canberra', 0, 0, 0, 40.00, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Canberra', 0, 0, 0, 40.00, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Melbourne', 0, 0, 0, 56.60, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Melbourne', 0, 0, 0, 42.20, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Sydney', 0, 0, 0, 43.80, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Sydney', 0, 0, 0, 40.00, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Melbourne', 0, 0, 0, 51.36, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Dec 16 - Melbourne', 0, 0, 0, 45.43, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Dec 16 - Melbourne', 0, 0, 0, 50.05, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 68996.04, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 3481.21, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jul to 31 Jul 16', 0, 0, 0, 2000.93, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 574.88, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 12.77, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 1284.12, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Aug to 31 Aug 16', 0, 0, 0, 1944.60, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 33.74, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 384.36, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 523.83, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 4.50, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 620.42, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 467.63, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 15.02, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 910.48, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 1 May to 31 May 16', 0, 0, 0, 1940.11, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 May to 27 Jun 16', 0, 0, 0, 401.75, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 May to 27 Jun 16', 0, 0, 0, 111.81, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jun to 30 Jun 16', 0, 0, 0, 300.95, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 14.56, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 297.30, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', '6 Packaging tape rolls 30 Jun 16', 0, 0, 0, 73.64, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '500 Printed items 21 Jul 16', 0, 0, 0, 206.00, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Aug to 31 Aug 16', 0, 0, 0, 1873.62, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '500 Printed items 8 Aug 16', 0, 0, 0, 307.00, '08-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '20,000 Personalised letterhead stationery 9 Aug 16', 0, 0, 0, 1070.00, '09-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '3 Printed items 31 Aug 16', 0, 0, 0, 100.00, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 31 Aug 16', 0, 0, 0, 525.00, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 0, 11650.23, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Oct to 31 Oct 16', 0, 0, 0, -45.45, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '60,250 Printed items 17 Oct 16', 0, 0, 0, 2361.00, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 1 Dec 16', 0, 0, 0, 718.00, '01-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution credit 1 Jun to 30 Jun 16', 0, 0, 0, -36980.44, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 1 Jun to 22 Jun 16', 0, 0, 0, 46076.67, '22-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 23 Jun to 30 Jun 16', 0, 0, 0, 10584.87, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '15,919 Printed items 24 Jun 16', 0, 0, 0, 1284.55, '24-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '61,000 Printed items 30 Jun 16', 0, 0, 0, 4407.27, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 Herald Sun 5 Jul to 3 Aug 16', 0, 0, 0, 30.00, '03-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 The Age 5 Jul to 3 Aug 16', 0, 0, 0, 50.00, '03-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 The Australian 5 Jul to 3 Aug 16', 0, 0, 0, 30.00, '03-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 The Australian Financial Review 5 Jul to 3 Aug 16', 0, 0, 0, 80.00, '03-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 The Australian Financial Review 4 Aug to 2 Sep 16', 0, 0, 0, 80.00, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 Herald Sun 4 Aug to 2 Sep 16', 0, 0, 0, 30.00, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 The Age 4 Aug to 2 Sep 16', 0, 0, 0, 50.00, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 The Australian 4 Aug to 2 Sep 16', 0, 0, 0, 30.00, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Age 5 Sep to 30 Sep 16', 0, 0, 0, 45.45, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 5 Sep to 30 Sep 16', 0, 0, 0, 27.27, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian Financial Review 5 Sep to 30 Sep 16', 0, 0, 0, 72.73, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 5 Sep to 30 Sep 16', 0, 0, 0, 27.27, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 Herald Sun 3 Oct to 1 Nov 16', 0, 0, 0, 30.00, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian 3 Oct to 1 Nov 16', 0, 0, 0, 5.45, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 The Australian Financial Review 3 Oct to 1 Nov 16', 0, 0, 0, 80.00, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '22 The Age 3 Oct to 1 Nov 16', 0, 0, 0, 56.00, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '27 The Australian 1 Oct to 6 Nov 15', 0, 0, 0, 36.82, '06-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '27 The Age 1 Oct to 6 Nov 15', 0, 0, 0, 61.36, '06-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '27 The Australian Financial Review 1 Oct to 6 Nov 15', 0, 0, 0, 93.27, '06-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '27 Herald Sun 1 Oct to 6 Nov 15', 0, 0, 0, 34.36, '06-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '15 The Australian 9 Nov to 27 Nov 15', 0, 0, 0, 20.45, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '15 The Age 9 Nov to 27 Nov 15', 0, 0, 0, 34.09, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '15 Sun Herald 9 Nov to 27 Nov 15', 0, 0, 0, 19.09, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '15 The Australian Financial Review 9 Nov to 27 Nov 15', 0, 0, 0, 51.82, '27-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '22 The Australian Financial Review 30 Nov 15 to 1 Jan 16', 0, 0, 0, 76.00, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '24 The Australian 30 Nov 15 to 1 Jan 16', 0, 0, 0, 32.73, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '24 The Age 30 Nov 15 to 1 Jan 16', 0, 0, 0, 54.55, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '24 Sun Herald 30 Nov 15 to 1 Jan 16', 0, 0, 0, 30.55, '30-Nov-2015', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Australian Financial Review 4 Jan to 29 Jan 16', 0, 0, 0, 69.09, '29-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Australian 4 Jan to 29 Jan 16', 0, 0, 0, 27.27, '29-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Age 4 Jan to 29 Jan 16', 0, 0, 0, 45.45, '29-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 Herald Sun 4 Jan to 29 Jan 16', 0, 0, 0, 25.45, '29-Jan-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 The Age 1 Feb to 29 Feb 16', 0, 0, 0, 47.73, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 The Australian 1 Feb to 29 Feb 16', 0, 0, 0, 28.64, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 Herald Sun 1 Feb to 29 Feb 16', 0, 0, 0, 28.18, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 The Australian Financial Review 1 Feb to 29 Feb 16', 0, 0, 0, 76.36, '29-Feb-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '23 The Australian 1 Mar to 1 Apr 16', 0, 0, 0, 31.36, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '24 Herald Sun 1 Mar to 1 Apr 16', 0, 0, 0, 32.73, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '24 The Age 1 Mar to 1 Apr 16', 0, 0, 0, 54.55, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '22 The Australian Financial Review 1 Mar to 1 Apr 16', 0, 0, 0, 80.00, '01-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 Sun Herald 4 Apr to 29 Apr 16', 0, 0, 0, 27.27, '29-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Age 4 Apr to 29 Apr 16', 0, 0, 0, 45.45, '29-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Australian 4 Apr to 29 Apr 16', 0, 0, 0, 27.27, '29-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '19 The Australian Financial Review 4 Apr to 29 Apr 16', 0, 0, 0, 69.09, '29-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '25 Sun Herald 2 May to 3 Jun 16', 0, 0, 0, 34.09, '03-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '25 The Australian Financial Review 2 May to 3 Jun 16', 0, 0, 0, 90.91, '03-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '25 The Age 2 May to 3 Jun 16', 0, 0, 0, 56.82, '03-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '25 The Australian 2 May to 3 Jun 16', 0, 0, 0, 34.09, '03-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Australian Financial Review 6 Jun to 4 Jul 16', 0, 0, 0, 72.73, '04-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 Herald Sun 6 Jun to 4 Jul 16', 0, 0, 0, 28.64, '04-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 The Age 6 Jun to 4 Jul 16', 0, 0, 0, 47.73, '04-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 The Australian 6 Jun to 4 Jul 16', 0, 0, 0, 28.64, '04-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Jul 16', 0, 0, 0, 283.57, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Jul 16', 0, 0, 0, 35.77, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Aug 16', 0, 0, 0, 282.47, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Aug 16', 0, 0, 0, 32.14, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Sep 16', 0, 0, 0, 207.29, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Sep 16', 0, 0, 0, 32.53, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Oct 16', 0, 0, 0, 261.00, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Oct 16', 0, 0, 0, 33.35, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Nov 16', 0, 0, 0, 266.77, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Nov 16', 0, 0, 0, 32.14, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 July 2016', '', '', '', 'Office phones 26 Jun 16', 0, 0, 0, 511.76, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Andrew Giles', 'Representative', 'Scullin', 'Victoria', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 July 2016', '', '', '', 'Office fax 26 Jun 16', 0, 0, 0, 34.55, '26-Jun-2016', '');
