INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 273.00, 0, 273.00, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 6, 276.00, 0, 1656.00, '15-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 12, 276.00, 0, 3312.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Sydney', 'Representing Minister or Presiding Officer', 1, 400.00, 0, 400.00, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Human Rights', 1, 276.00, 0, 276.00, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Jul 16 - Perth to Melbourne', 0, 0, 0, 1673.97, '16-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Jul 16 - Melbourne to Canberra', 0, 0, 0, 0, '16-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Jul 16 - Canberra to Perth', 0, 0, 0, 1673.97, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Perth to Melbourne', 0, 0, 0, 1673.97, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Melbourne to Canberra', 0, 0, 0, 0, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Sep 16 - Canberra to Melbourne', 0, 0, 0, 1673.97, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Sep 16 - Melbourne to Perth', 0, 0, 0, 0, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Perth to Melbourne', 0, 0, 0, 1674.92, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne to Canberra', 0, 0, 0, 0, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Canberra to Melbourne', 0, 0, 0, 1674.92, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Melbourne to Perth', 0, 0, 0, 0, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Perth to Melbourne', 0, 0, 0, 1835.45, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne to Canberra', 0, 0, 0, 0, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Oct 16 - Canberra to Melbourne', 0, 0, 0, 1673.97, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Oct 16 - Melbourne to Perth', 0, 0, 0, 0, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Oct 16 - Perth to Canberra', 0, 0, 0, 1817.27, '15-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Canberra to Melbourne', 0, 0, 0, 1835.45, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Melbourne to Perth', 0, 0, 0, 0, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Perth to Melbourne', 0, 0, 0, 1835.45, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne to Canberra', 0, 0, 0, 0, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Nov 16 - Canberra to Melbourne', 0, 0, 0, 1835.45, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Nov 16 - Melbourne to Perth', 0, 0, 0, 0, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Perth to Sydney', 0, 0, 0, 1679.45, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Sydney to Canberra', 0, 0, 0, 0, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Car cleaning 1 Jul 16', 0, 0, 0, 16.36, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 18 Jul to 17 Aug 16', 0, 0, 0, 862.78, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 2 Aug to 27 Aug 16', 0, 0, 0, 282.61, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Car cleaning 11 Aug 16', 0, 0, 0, 16.36, '11-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 18 Aug to 17 Sep 16', 0, 0, 0, 862.78, '17-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 5 Sep to 21 Sep 16', 0, 0, 0, 138.42, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 18 Sep to 17 Oct 16', 0, 0, 0, 862.78, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Car cleaning 21 Sep 16', 0, 0, 0, 16.36, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 28 Sep to 28 Oct 16', 0, 0, 0, 177.73, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 18 Oct to 17 Nov 16', 0, 0, 0, 886.02, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Car cleaning 28 Oct 16', 0, 0, 0, 16.36, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 1 Nov to 14 Nov 16', 0, 0, 0, 176.75, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Car cleaning 14 Nov 16', 0, 0, 0, 16.36, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 18 Nov to 17 Dec 16', 0, 0, 0, 886.02, '17-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Fuel 8 Jun to 20 Jun 16', 0, 0, 0, 120.38, '20-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Infringement notice fee 17 Jun 16', 0, 0, 0, 15.00, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Reimbursement of infringement notice fee 17 Jun 16', 0, 0, 0, -15.00, '17-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Lease 18 Jun to 17 Jul 16', 0, 0, 0, 862.78, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Fuel 30 Jun to 25 Jul 16', 0, 0, 0, 191.42, '25-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Jul 16 - Perth', 0, 0, 0, 78.60, '16-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Jul 16 - Canberra', 0, 0, 0, 80.40, '16-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Jul 16 - Canberra', 0, 0, 0, 78.60, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Jul 16 - Canberra', 0, 0, 0, 78.60, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Jul 16 - Canberra', 0, 0, 0, 78.60, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Jul 16 - Canberra', 0, 0, 0, 40.00, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Jul 16 - Perth', 0, 0, 0, 49.78, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Aug 16 - Perth', 0, 0, 0, 78.60, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Sep 16 - Perth', 0, 0, 0, 66.81, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Sep 16 - Perth', 0, 0, 0, 78.60, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Sep 16 - Perth', 0, 0, 0, 68.12, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Oct 16 - Perth', 0, 0, 0, 78.60, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Perth', 0, 0, 0, 78.60, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Oct 16 - Perth', 0, 0, 0, 78.60, '15-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Oct 16 - Canberra', 0, 0, 0, 80.40, '15-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Oct 16 - Perth', 0, 0, 0, 62.27, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Nov 16 - Perth', 0, 0, 0, 78.60, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Nov 16 - Perth', 0, 0, 0, 62.27, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Nov 16 - Perth', 0, 0, 0, 99.56, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Nov 16 - Canberra', 0, 0, 0, 40.00, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Nov 16 - Canberra', 0, 0, 0, 40.00, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Dec 16 - Canberra', 0, 0, 0, 78.60, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Dec 16 - Perth', 0, 0, 0, 78.60, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '7 Dec 16 - Perth', 0, 0, 0, 71.44, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '7 Dec 16 - Sydney', 0, 0, 0, 50.00, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Dec 16 - Sydney', 0, 0, 0, 40.00, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Dec 16 - Sydney', 0, 0, 0, 46.20, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Dec 16 - Sydney', 0, 0, 0, 40.00, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Dec 16 - Perth', 0, 0, 0, 82.53, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Dec 16 - Perth', 0, 0, 0, 99.56, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Dec 16 - Canberra', 0, 0, 0, 41.80, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Dec 16 - Canberra', 0, 0, 0, 40.00, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Dec 16 - Canberra', 0, 0, 0, 40.00, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '13 Dec 16 - Canberra', 0, 0, 0, 40.00, '13-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '13 Dec 16 - Perth', 0, 0, 0, 60.96, '13-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 88164.62, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 3712.79, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jul to 31 Jul 16', 0, 0, 0, 125.15, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 2318.18, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Jul to 31 Jul 16', 0, 0, 0, 1567.22, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 5 Jul 16', 0, 0, 0, 42.00, '05-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 18.49, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 298.12, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 303.25, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 32.06, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 511.62, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 1272.45, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Sep to 30 Sep 16', 0, 0, 0, 84.75, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 216.97, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 13.04, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 29 Sep 16', 0, 0, 0, 52.50, '29-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 248.50, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 647.89, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 47.15, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 0, 137.87, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 22 Nov 16', 0, 0, 0, 73.50, '22-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 May to 27 Jun 16', 0, 0, 0, 14.50, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 May to 27 Jun 16', 0, 0, 0, 467.71, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jun to 30 Jun 16', 0, 0, 0, 835.48, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', '2 E-Z Seal bottles 24 Jun 16', 0, 0, 0, 86.50, '24-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 12.34, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 464.06, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Jul to 31 Jul 16', 0, 0, 0, -4.55, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Jul to 31 Jul 16', 0, 0, 0, 181.82, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 5 Jul 16', 0, 0, 0, 1064.80, '05-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 7 Jul 16', 0, 0, 0, 909.00, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Aug to 31 Aug 16', 0, 0, 0, 16.55, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Sep to 30 Sep 16', 0, 0, 0, 3726.29, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Sep to 30 Sep 16', 0, 0, 0, -1919.23, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '2,000 Printed items 19 Sep 16', 0, 0, 0, 500.00, '19-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 29 Sep 16', 0, 0, 0, 1000.00, '29-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 0, 1835.63, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Oct to 31 Oct 16', 0, 0, 0, -4.55, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Printing 4 Oct 16', 0, 0, 0, 4545.45, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 4 Oct 16', 0, 0, 0, 1270.00, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 0, 745.36, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Nov to 30 Nov 16', 0, 0, 0, -4.55, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,500 Printed items 24 Nov 16', 0, 0, 0, 1080.00, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '55,000 Printed items 27 Nov 16', 0, 0, 0, 69760.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 1 Jun to 30 Jun 16', 0, 0, 0, 53455.61, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 2 Jun 16', 0, 0, 0, 454.50, '02-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 7 Jun 16', 0, 0, 0, 898.44, '07-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 9 Jun 16', 0, 0, 0, 454.50, '09-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 14 Jun 16', 0, 0, 0, 1064.80, '14-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '58,000 Printed items 14 Jun 16', 0, 0, 0, 8720.00, '14-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 16 Jun 16', 0, 0, 0, 454.50, '16-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 21 Jun 16', 0, 0, 0, 1064.80, '21-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '57,630 Printed items 21 Jun 16', 0, 0, 0, 2542.58, '21-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 21 Jun 16', 0, 0, 0, 2906.24, '21-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 23 Jun 16', 0, 0, 0, 454.50, '23-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 28 Jun 16', 0, 0, 0, 1397.55, '28-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 30 Jun 16', 0, 0, 0, 454.50, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 2 Jul 16', 0, 0, 0, 419.53, '02-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 2 Jul 16', 0, 0, 0, 32.14, '02-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 1 Aug 16', 0, 0, 0, 340.03, '01-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 1 Aug 16', 0, 0, 0, 34.68, '01-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 1 Sep 16', 0, 0, 0, 328.60, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 1 Sep 16', 0, 0, 0, 32.63, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 2 Oct 16', 0, 0, 0, 352.44, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 2 Oct 16', 0, 0, 0, 32.50, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 1 Nov 16', 0, 0, 0, 305.01, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 1 Nov 16', 0, 0, 0, 32.50, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 2 Dec 16', 0, 0, 0, 305.93, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 2 Dec 16', 0, 0, 0, 32.53, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 14 Jul 16', 0, 0, 0, 71.97, '14-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 15 Jul 16', 0, 0, 0, 63.59, '15-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 11 Aug 16', 0, 0, 0, 56.36, '11-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 14 Aug 16', 0, 0, 0, 63.59, '14-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 11 Sep 16', 0, 0, 0, 75.29, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 17 Sep 16', 0, 0, 0, 63.59, '17-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 11 Oct 16', 0, 0, 0, 76.58, '11-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 15 Oct 16', 0, 0, 0, 63.59, '15-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 11 Nov 16', 0, 0, 0, 67.96, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 15 Nov 16', 0, 0, 0, 63.59, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 11 Dec 16', 0, 0, 0, 60.24, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 15 Dec 16', 0, 0, 0, 63.59, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Perth to Sydney', 0, 0, 0, 1679.45, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Sydney to Canberra', 0, 0, 0, 0, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '4 Dec 16 - Canberra to Melbourne', 0, 0, 0, 2357.39, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Ian Goodenough', 'Representative', 'Moore', 'Western Australia', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '4 Dec 16 - Melbourne to Perth', 0, 0, 0, 0, '04-Dec-2016', '');
