INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 2, 273.00, 0, 546.00, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Official Government or Vice-Regal Function', 2, 273.00, 0, 546.00, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 276.00, 0, 276.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Official Government or Vice-Regal Function', 1, 276.00, 0, 276.00, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Senate Estimates', 5, 276.00, 0, 1380.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Ballarat', 'Parliamentary Political Party Meeting', 1, 286.00, 0, 286.00, '19-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Jul 16 - Melbourne to Canberra', 0, 0, 0, 411.39, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '19 Jul 16 - Canberra to Melbourne', 0, 0, 0, 411.39, '19-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '23 Aug 16 - Melbourne to Canberra', 0, 0, 0, 149.76, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Aug 16 - Canberra to Melbourne', 0, 0, 0, 149.76, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Melbourne to Canberra', 0, 0, 0, 149.76, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Sep 16 - Canberra to Melbourne', 0, 0, 0, 149.76, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Sep 16 - Melbourne to Sydney', 0, 0, 0, 154.16, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Sep 16 - Sydney to Melbourne', 0, 0, 0, 154.16, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne to Canberra', 0, 0, 0, 149.76, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '5 Oct 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Oct 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne to Canberra', 0, 0, 0, 149.76, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Oct 16 - Canberra to Melbourne', 0, 0, 0, 149.76, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Oct 16 - Melbourne to Canberra', 0, 0, 0, 149.76, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Canberra to Melbourne', 0, 0, 0, 149.76, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Oct 16 - Melbourne to Sydney', 0, 0, 0, 154.16, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '3 Nov 16 - Sydney to Melbourne', 0, 0, 0, 154.16, '03-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne to Canberra', 0, 0, 0, 149.76, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '7 Nov 16 - Canberra to Sydney', 0, 0, 0, 334.35, '07-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '8 Nov 16 - Sydney to Canberra', 0, 0, 0, 334.35, '08-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Nov 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '12 Nov 16 - Melbourne to Sydney', 0, 0, 0, 154.16, '12-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '12 Nov 16 - Sydney to Melbourne', 0, 0, 0, 154.16, '12-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Melbourne to Canberra', 0, 0, 0, 149.76, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Dec 16 - Canberra to Melbourne', 0, 0, 0, 149.76, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Jul to 16 Aug 16', 0, 0, 0, 888.20, '16-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 1 Aug to 27 Aug 16', 0, 0, 0, 339.75, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Aug to 16 Sep 16', 0, 0, 0, 888.20, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Additional maintenance 19 Aug 16', 0, 0, 0, 308.28, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Sep to 16 Oct 16', 0, 0, 0, 888.20, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 29 Sep to 22 Oct 16', 0, 0, 0, 131.36, '22-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Oct to 16 Nov 16', 0, 0, 0, 888.18, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 17 Nov 16', 0, 0, 0, 68.67, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Nov to 16 Dec 16', 0, 0, 0, 888.18, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Additional maintenance 29 May 16', 0, 0, 0, 34.08, '29-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Fuel 2 Jun to 19 Jun 16', 0, 0, 0, 342.28, '19-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Lease 17 Jun to 16 Jul 16', 0, 0, 0, 888.20, '16-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Fuel 29 Jun to 8 Jul 16', 0, 0, 0, 135.77, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Jul 16 - Melbourne', 0, 0, 0, 80.80, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Jul 16 - Canberra', 0, 0, 0, 80.40, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Jul 16 - Canberra', 0, 0, 0, 78.60, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Jul 16 - Canberra', 0, 0, 0, 78.60, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Jul 16 - Canberra', 0, 0, 0, 40.00, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Jul 16 - Canberra', 0, 0, 0, 78.60, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '19 Jul 16 - Canberra', 0, 0, 0, 40.00, '19-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '19 Jul 16 - Melbourne', 0, 0, 0, 49.71, '19-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Aug 16 - Melbourne', 0, 0, 0, 60.81, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Aug 16 - Canberra', 0, 0, 0, 41.80, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Aug 16 - Canberra', 0, 0, 0, 78.60, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 78.60, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Aug 16 - Canberra', 0, 0, 0, 40.00, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Aug 16 - Canberra', 0, 0, 0, 40.00, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Aug 16 - Melbourne', 0, 0, 0, 74.49, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Aug 16 - Melbourne', 0, 0, 0, 93.98, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '30 Aug 16 - Canberra', 0, 0, 0, 40.00, '30-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '31 Aug 16 - Canberra', 0, 0, 0, 40.00, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Sep 16 - Melbourne', 0, 0, 0, 52.67, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Sep 16 - Melbourne', 0, 0, 0, 40.00, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Sep 16 - Melbourne', 0, 0, 0, 67.25, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Sep 16 - Sydney', 0, 0, 0, 49.80, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Sep 16 - Sydney', 0, 0, 0, 40.00, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Sep 16 - Sydney', 0, 0, 0, 56.33, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Sep 16 - Melbourne', 0, 0, 0, 58.77, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne', 0, 0, 0, 86.90, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Melbourne', 0, 0, 0, 67.70, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Canberra', 0, 0, 0, 80.40, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Canberra', 0, 0, 0, 40.00, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Canberra', 0, 0, 0, 40.00, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Canberra', 0, 0, 0, 40.00, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Melbourne', 0, 0, 0, 46.40, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne', 0, 0, 0, 86.90, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Melbourne', 0, 0, 0, 64.01, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Oct 16 - Melbourne', 0, 0, 0, 86.90, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Oct 16 - Canberra', 0, 0, 0, 80.40, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Oct 16 - Canberra', 0, 0, 0, 78.60, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Oct 16 - Melbourne', 0, 0, 0, 67.94, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Oct 16 - Melbourne', 0, 0, 0, 56.77, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '3 Nov 16 - Melbourne', 0, 0, 0, 66.63, '03-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne', 0, 0, 0, 80.80, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '7 Nov 16 - Sydney', 0, 0, 0, 43.80, '07-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Nov 16 - Sydney', 0, 0, 0, 44.90, '08-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Nov 16 - Melbourne', 0, 0, 0, 56.60, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Nov 16 - Melbourne', 0, 0, 0, 86.90, '12-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Nov 16 - Sydney', 0, 0, 0, 88.60, '12-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Nov 16 - Sydney', 0, 0, 0, 78.60, '12-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Nov 16 - Melbourne', 0, 0, 0, 88.90, '12-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Nov 16 - Melbourne', 0, 0, 0, 85.70, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne', 0, 0, 0, 86.90, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Canberra', 0, 0, 0, 80.40, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Canberra', 0, 0, 0, 78.60, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '29 Nov 16 - Canberra', 0, 0, 0, 176.85, '29-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '30 Nov 16 - Canberra', 0, 0, 0, 40.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Melbourne', 0, 0, 0, 71.89, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Dec 16 - Melbourne', 0, 0, 0, 62.01, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Dec 16 - Canberra', 0, 0, 0, 41.80, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Dec 16 - Canberra', 0, 0, 0, 40.00, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Dec 16 - Melbourne', 0, 0, 0, 50.91, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Dec 16 - Melbourne', 0, 0, 0, 69.87, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Dec 16 - Melbourne', 0, 0, 0, 58.77, '22-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'Before 1 July 2016', '', '', '', '26 Jun 16', 0, 0, 0, 70.21, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'Before 1 July 2016', '', '', '', '26 Jun 16', 0, 0, 0, 61.48, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 21538.10, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 217.41, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jul to 31 Jul 16', 0, 0, 0, 814.99, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Jul to 31 Jul 16', 0, 0, 0, 471.80, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 0.79, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 10.65, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 23.00, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 208.34, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 2.61, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 1576.52, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 21.00, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 1909.09, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 2.42, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 631.64, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 18.10, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 91.22, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 3.64, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 0, 174.21, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Nov to 30 Nov 16', 0, 0, 0, 487.73, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Software reimbursement 2015/16', 0, 0, 0, 545.45, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 1 May to 31 May 16', 0, 0, 0, 280.25, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Flags 1 May to 31 May 16', 0, 0, 0, 433.20, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 May to 27 Jun 16', 0, 0, 0, 41.33, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 May to 27 Jun 16', 0, 0, 0, 19.53, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jun to 30 Jun 16', 0, 0, 0, 168.08, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 433.38, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 18.42, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Jul to 31 Jul 16', 0, 0, 0, 12.59, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 1 Jul 16', 0, 0, 0, 269.16, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 16 Aug 16', 0, 0, 0, 70.00, '16-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 31 Aug 16', 0, 0, 0, 134.00, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Sep to 30 Sep 16', 0, 0, 0, 6.36, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 16 Sep 16', 0, 0, 0, 70.00, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 1 Oct 16', 0, 0, 0, 263.60, '01-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 0, 135.18, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 4 Oct to 25 Oct 16', 0, 0, 0, 23.00, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 0, 386.68, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '2,500 Printed items 5 Dec 16', 0, 0, 0, 3836.62, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 13 May 16', 0, 0, 0, 27.08, '13-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 1 Jun to 30 Jun 16', 0, 0, 0, 15298.86, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution credit 1 Jun to 30 Jun 16', 0, 0, 0, -45.64, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 27 Jun 16', 0, 0, 0, 640.63, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 29 Jun to 30 Jun 16', 0, 0, 0, 90.21, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 29 Jun 16', 0, 0, 0, 3443.31, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 30 Jun 16', 0, 0, 0, 50.00, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 1 Aug to 28 Aug 16', 0, 0, 0, 27.27, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 1 Aug to 28 Aug 16', 0, 0, 0, 27.60, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Spectator 1 Aug to 28 Aug 16', 0, 0, 0, 39.82, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Geelong Advertiser (Sat) 1 Aug to 28 Aug 16', 0, 0, 0, 8.18, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian Jewish News 1 Aug to 28 Aug 16', 0, 0, 0, 13.82, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Geelong Advertiser 1 Aug to 28 Aug 16', 0, 0, 0, 27.27, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian Financial Review 1 Aug to 28 Aug 16', 0, 0, 0, 72.73, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Age 1 Aug to 28 Aug 16', 0, 0, 0, 45.45, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 1 Aug to 28 Aug 16', 0, 0, 0, 49.09, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 Quadrant 29 Aug to 25 Sep 16', 0, 0, 0, 8.09, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 29 Aug to 25 Sep 16', 0, 0, 0, 27.85, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Spectator 29 Aug to 25 Sep 16', 0, 0, 0, 39.82, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Geelong Advertiser (Sat) 29 Aug to 25 Sep 16', 0, 0, 0, 8.18, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian Jewish News 29 Aug to 25 Sep 16', 0, 0, 0, 13.82, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Geelong Advertiser 29 Aug to 25 Sep 16', 0, 0, 0, 27.27, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian Financial Review 29 Aug to 25 Sep 16', 0, 0, 0, 72.73, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 29 Aug to 25 Sep 16', 0, 0, 0, 49.09, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 29 Aug to 25 Sep 16', 0, 0, 0, 27.27, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Age 29 Aug to 25 Sep 16', 0, 0, 0, 45.45, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 Herald Sun 26 Sep to 30 Oct 16', 0, 0, 0, 34.09, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 The Age 26 Sep to 30 Oct 16', 0, 0, 0, 62.27, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 The Australian Financial Review 26 Sep to 30 Oct 16', 0, 0, 0, 90.91, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 The Geelong Advertiser 26 Sep to 30 Oct 16', 0, 0, 0, 34.09, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Australian Jewish News 26 Sep to 30 Oct 16', 0, 0, 0, 17.27, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Geelong Advertiser (Sat) 26 Sep to 30 Oct 16', 0, 0, 0, 10.23, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Spectator 26 Sep to 30 Oct 16', 0, 0, 0, 49.77, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 26 Sep to 30 Oct 16', 0, 0, 0, 34.75, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 Quadrant 26 Sep to 30 Oct 16', 0, 0, 0, 8.09, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 The Australian 26 Sep to 30 Oct 16', 0, 0, 0, 61.36, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Age 31 Oct to 27 Nov 16', 0, 0, 0, 50.91, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 31 Oct to 27 Nov 16', 0, 0, 0, 27.85, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Spectator 31 Oct to 27 Nov 16', 0, 0, 0, 39.82, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Geelong Advertiser (Sat) 31 Oct to 27 Nov 16', 0, 0, 0, 8.18, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian Jewish News 31 Oct to 27 Nov 16', 0, 0, 0, 13.82, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Geelong Advertiser 31 Oct to 27 Nov 16', 0, 0, 0, 27.27, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 31 Oct to 27 Nov 16', 0, 0, 0, 49.09, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 31 Oct to 27 Nov 16', 0, 0, 0, 27.27, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 Quadrant 31 Oct to 27 Nov 16', 0, 0, 0, 8.09, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian Financial Review 31 Oct to 27 Nov 16', 0, 0, 0, 72.73, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', 'Administrative fees 30 May to 26 Jun 16', 0, 0, 0, 27.35, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '3 The Australian Jewish News 30 May to 26 Jun 16', 0, 0, 0, 10.36, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 The Spectator 30 May to 26 Jun 16', 0, 0, 0, 39.82, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Geelong Advertiser 30 May to 26 Jun 16', 0, 0, 0, 25.45, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '1 Quadrant 30 May to 26 Jun 16', 0, 0, 0, 8.09, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 The Geelong Advertiser (Sat) 30 May to 26 Jun 16', 0, 0, 0, 8.18, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 Herald Sun 30 May to 26 Jun 16', 0, 0, 0, 27.27, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Age 30 May to 26 Jun 16', 0, 0, 0, 45.45, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Australian 30 May to 26 Jun 16', 0, 0, 0, 49.09, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '19 The Australian Financial Review 30 May to 26 Jun 16', 0, 0, 0, 69.09, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '5 The Geelong Advertiser 27 Jun to 31 Jul 16', 0, 0, 0, 6.82, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '1 Quadrant 27 Jun to 31 Jul 16', 0, 0, 0, 8.09, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '5 The Spectator Australia 27 Jun to 31 Jul 16', 0, 0, 0, 49.77, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '5 The Geelong Advertiser (Sat) 27 Jun to 31 Jul 16', 0, 0, 0, 10.23, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '5 The Australian Jewish News 27 Jun to 31 Jul 16', 0, 0, 0, 17.27, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '25 The Australian Financial Review 27 Jun to 31 Jul 16', 0, 0, 0, 90.91, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '25 The Age 27 Jun to 31 Jul 16', 0, 0, 0, 56.82, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '25 Herald Sun 27 Jun to 31 Jul 16', 0, 0, 0, 34.09, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Geelong Advertiser 27 Jun to 31 Jul 16', 0, 0, 0, 25.45, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '25 The Australian 27 Jun to 31 Jul 16', 0, 0, 0, 61.36, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', 'Administrative fees 27 Jun to 31 Jul 16', 0, 0, 0, 34.75, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Jul 16', 0, 0, 0, 193.96, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Jul 16', 0, 0, 0, 32.50, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Aug 16', 0, 0, 0, 391.46, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Aug 16', 0, 0, 0, 32.14, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Sep 16', 0, 0, 0, 236.11, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Sep 16', 0, 0, 0, 32.14, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Oct 16', 0, 0, 0, 214.82, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Oct 16', 0, 0, 0, 32.53, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Nov 16', 0, 0, 0, 194.88, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Nov 16', 0, 0, 0, 31.77, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 July 2016', '', '', '', 'Office phones 26 Jun 16', 0, 0, 0, 250.98, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 July 2016', '', '', '', 'Office fax 26 Jun 16', 0, 0, 0, 33.03, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('James Paterson', 'Senator', '', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '28 Nov 16 - Canberra to Melbourne', 0, 0, 0, 149.76, '28-Nov-2016', '');
