INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 2, 273.00, 0, 546.00, '16-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '28-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '09-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '16-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '06-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '20-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Canberra to Mount Dandenong 18 Jul 16', 0, 0, 0, 458.70, '18-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Mount Dandenong to Canberra 28 Aug 16', 0, 0, 0, 458.70, '28-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Canberra to Mount Dandenong 2 Sep 16', 0, 0, 0, 458.70, '02-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Mount Dandenong to Canberra 11 Sep 16', 0, 0, 0, 234.70, '11-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Canberra to Mount Dandenong 16 Sep 16', 0, 0, 0, 234.70, '16-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Mount Dandenong to Canberra 9 Oct 16', 0, 0, 0, 458.70, '09-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Canberra to Mount Dandenong 14 Oct 16', 0, 0, 0, 458.70, '14-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Mount Dandenong to Canberra 16 Oct 16', 0, 0, 0, 458.70, '16-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Canberra to Mount Dandenong 21 Oct 16', 0, 0, 0, 458.70, '21-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Mount Dandenong to Canberra 6 Nov 16', 0, 0, 0, 277.70, '06-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Canberra to Mount Dandenong 11 Nov 16', 0, 0, 0, 234.70, '11-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Mount Dandenong to Canberra 20 Nov 16', 0, 0, 0, 234.70, '20-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Canberra to Mount Dandenong 25 Nov 16', 0, 0, 0, 234.70, '25-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Melbourne to Canberra 27 Nov 16', 0, 0, 0, 234.70, '27-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Canberra to Melbourne 2 Dec 16', 0, 0, 0, 234.70, '02-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 59045.15, '01-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 9020.50, '01-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jul to 31 Jul 16', 0, 0, 0, 2197.43, '31-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Jul to 31 Jul 16', 0, 0, 0, 943.60, '31-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 9.20, '27-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 93.49, '27-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 99.65, '31-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 5.74, '27-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 2239.21, '27-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 25.50, '01-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 2318.18, '01-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 7.26, '27-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 667.74, '27-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 912.00, '31-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 6.13, '27-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 320.36, '27-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 0, 517.00, '30-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Reimbursement of office requisites and stationery 30 Sep 15', 0, 0, 0, -45.41, '30-Sep-2015');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 30 Sep 15', 0, 0, 0, 45.41, '30-Sep-2015');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', '12 Month planner 30 Sep 15', 0, 0, 0, 45.41, '30-Sep-2015');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 1 May to 31 May 16', 0, 0, 0, 129.64, '31-May-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 May to 27 Jun 16', 0, 0, 0, 18.03, '27-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 May to 27 Jun 16', 0, 0, 0, 1499.09, '27-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jun to 30 Jun 16', 0, 0, 0, 494.55, '30-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 1696.02, '27-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 3.51, '27-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 1 Jul 16', 0, 0, 0, 12977.49, '01-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Web-services 2 Jul 16 to 1 Jul 17', 0, 0, 0, 300.00, '02-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '55,000 Printed items 2 Jul 16', 0, 0, 0, 6702.73, '02-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 31 Aug 16', 0, 0, 0, 60.00, '31-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 1 Sep to 30 Sep 16', 0, 0, 0, 86.13, '30-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Sep to 30 Sep 16', 0, 0, 0, 2727.27, '30-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Sep to 30 Sep 16', 0, 0, 0, -68.18, '30-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 0, 28.36, '31-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 1 Oct to 31 Oct 16', 0, 0, 0, 22.33, '31-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Printing 8 Oct 16', 0, 0, 0, 1363.64, '08-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 0, 24176.83, '30-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Nov to 30 Nov 16', 0, 0, 0, -45.45, '30-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '53,800 Printed items 4 Nov 16', 0, 0, 0, 37072.35, '04-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '53,500 Printed items 4 Nov 16', 0, 0, 0, 6243.00, '04-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '53,500 Printed items 29 Nov 16', 0, 0, 0, 4370.00, '29-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 18 May 16', 0, 0, 0, 2499.99, '18-May-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '53,000 Printed items 20 May 16', 0, 0, 0, 84.27, '20-May-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '53,000 Printed items 20 May 16', 0, 0, 0, 3343.13, '20-May-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 25 May 16', 0, 0, 0, 2499.99, '25-May-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution credit 1 Jun to 30 Jun 16', 0, 0, 0, -14842.44, '30-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 1 Jun to 30 Jun 16', 0, 0, 0, 23930.22, '30-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution late payment fee Jun 16', 0, 0, 0, 15.00, '01-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 3 Jul to 30 Jul 16', 0, 0, 0, 27.27, '30-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 3 Jul to 30 Jul 16', 0, 0, 0, 49.09, '30-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 3 Jul to 30 Jul 16', 0, 0, 0, 9.00, '30-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 31 Jul to 3 Sep 16', 0, 0, 0, 12.27, '03-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 Herald Sun 31 Jul to 3 Sep 16', 0, 0, 0, 34.09, '03-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 The Australian 31 Jul to 3 Sep 16', 0, 0, 0, 61.36, '03-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 4 Sep to 1 Oct 16', 0, 0, 0, 10.36, '01-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 4 Sep to 1 Oct 16', 0, 0, 0, 49.09, '01-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 4 Sep to 1 Oct 16', 0, 0, 0, 27.27, '01-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 Melway 2 Oct to 29 Oct 16', 0, 0, 0, 44.50, '29-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 2 Oct to 29 Oct 16', 0, 0, 0, 49.09, '29-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 2 Oct to 29 Oct 16', 0, 0, 0, 10.36, '29-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 2 Oct to 29 Oct 16', 0, 0, 0, 27.27, '29-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 The Australian 30 Oct to 3 Dec 16', 0, 0, 0, 61.36, '03-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '25 Herald Sun 30 Oct to 3 Dec 16', 0, 0, 0, 34.09, '03-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 30 Oct to 3 Dec 16', 0, 0, 0, 12.27, '03-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 Herald Sun 5 Jun to 2 Jul 16', 0, 0, 0, 27.27, '02-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '20 The Australian 5 Jun to 2 Jul 16', 0, 0, 0, 49.09, '02-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', 'Administrative fees 5 Jun to 2 Jul 16', 0, 0, 0, 9.00, '02-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Jul 16', 0, 0, 0, 294.48, '26-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Jul 16', 0, 0, 0, 32.63, '26-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Aug 16', 0, 0, 0, 341.24, '26-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Aug 16', 0, 0, 0, 32.14, '26-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Sep 16', 0, 0, 0, 258.04, '26-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Sep 16', 0, 0, 0, 32.14, '26-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Oct 16', 0, 0, 0, 281.82, '26-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Oct 16', 0, 0, 0, 33.23, '26-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Nov 16', 0, 0, 0, 302.21, '26-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Nov 16', 0, 0, 0, 32.14, '26-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 July 2016', '', '', '', 'Office phones 26 Jun 16', 0, 0, 0, 450.50, '26-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 July 2016', '', '', '', 'Office fax 26 Jun 16', 0, 0, 0, 37.95, '26-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 2 Jul 16', 0, 0, 0, 67.40, '02-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 8 Jul 16', 0, 0, 0, 36.66, '08-Jul-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 1 Aug 16', 0, 0, 0, 63.59, '01-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 8 Aug 16', 0, 0, 0, 31.77, '08-Aug-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 1 Sep 16', 0, 0, 0, 63.59, '01-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 8 Sep 16', 0, 0, 0, 32.37, '08-Sep-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 2 Oct 16', 0, 0, 0, 63.59, '02-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 6 Oct 16', 0, 0, 0, 35.30, '06-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 1 Nov 16', 0, 0, 0, 63.59, '01-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 8 Nov 16', 0, 0, 0, 34.10, '08-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 2 Dec 16', 0, 0, 0, 63.59, '02-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date)
VALUES ('Jason Wood', 'Representative', 'La Trobe', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 8 Dec 16', 0, 0, 0, 36.78, '08-Dec-2016');
