INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 273.00, 0, 273.00, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Official Government or Vice-Regal Function', 2, 273.00, 0, 546.00, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 0, 828.00, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 0, 828.00, '07-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 0, 828.00, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Aug 16 - Sydney to Canberra', 0, 0, 0, 599.25, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Aug 16 - Canberra to Sydney', 0, 0, 0, 599.25, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Sydney to Canberra', 0, 0, 0, 526.99, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 July 2016', '', '', '', 'Sydney to Canberra 17 Jul 16', 0, 0, 0, 411.84, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 11 Sep 16', 0, 0, 0, 7.14, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 15 Aug and 17 Aug 16', 0, 0, 0, 218.18, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 83214.44, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 23.18, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 2318.18, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Kitchen crockery 25 Jul 16', 0, 0, 0, 92.73, '25-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Kitchen crockery 25 Jul 16', 0, 0, 0, 24.27, '25-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Kitchen crockery 25 Jul 16', 0, 0, 0, 159.18, '25-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Tape measure 27 Jul 16', 0, 0, 0, 9.09, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 1609.53, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Aug to 31 Aug 16', 0, 0, 0, 2019.38, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Kitchen crockery 8 Aug 16', 0, 0, 0, 111.59, '08-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'General office supplies 9 Aug 16', 0, 0, 0, 89.30, '09-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '9 Greeting cards 13 Aug 16', 0, 0, 0, 48.03, '13-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Portable and attractive items 17 Aug 16', 0, 0, 0, 1726.36, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office crockery 24 Aug 16', 0, 0, 0, 90.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 7.82, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 269.01, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Freight costs 29 Aug 16', 0, 0, 0, 100.00, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 443.53, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Sep to 30 Sep 16', 0, 0, 0, 1820.30, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'General office consumables 12 Sep 16', 0, 0, 0, 6.55, '12-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 17.53, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 171.05, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 1988.33, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Oct to 31 Oct 16', 0, 0, 0, 471.80, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 42.84, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 14.56, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Extension lead 24 Nov 16', 0, 0, 0, 17.95, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Aug to 31 Aug 16', 0, 0, 0, -34.09, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Aug to 31 Aug 16', 0, 0, 0, 1505.27, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '2,000 Printed items 15 Aug 16', 0, 0, 0, 459.00, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 30 Aug 16', 0, 0, 0, 587.00, '30-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Printing 31 Aug 16', 0, 0, 0, 805.50, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '6,820 Personalised letterhead stationery 31 Aug 16', 0, 0, 0, 2007.90, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Sep to 30 Sep 16', 0, 0, 0, 454.55, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Sep to 30 Sep 16', 0, 0, 0, -11.36, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '500 Printed items 13 Sep 16', 0, 0, 0, 142.00, '13-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 0, 2866.23, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution late payment fee Oct 16', 0, 0, 0, 15.00, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Oct to 31 Oct 16', 0, 0, 0, -45.45, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 11 Oct 16', 0, 0, 0, 575.30, '11-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 13 Oct 16', 0, 0, 0, 30.14, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 21 Oct 16', 0, 0, 0, 39.86, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Nov to 30 Nov 16', 0, 0, 0, -11.36, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 0, 734.45, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 1 Nov 16', 0, 0, 0, 498.00, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 1 Nov 16', 0, 0, 0, 747.00, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '10,000 Personalised letterhead stationery 2 Nov 16', 0, 0, 0, 584.00, '02-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 18 Nov 16', 0, 0, 0, 60.15, '18-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '65,000 Printed items 25 Nov 16', 0, 0, 0, 9170.51, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 29 Nov 16', 0, 0, 0, 242.50, '29-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 30 Nov 16', 0, 0, 0, 1140.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 30 Nov 16', 0, 0, 0, 525.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 30 Nov 16', 0, 0, 0, 52.13, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 1 Dec 16', 0, 0, 0, 12.22, '01-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 4 Dec 16', 0, 0, 0, 810.00, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 Australian Geographic Explorers: The Olympics: Faster, Higher, Stronger 15 Aug 16', 0, 0, 0, 22.68, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '3 Dare I Say: Inside Stories of the World''s Most Powerful Speeches 5 Nov 16', 0, 0, 0, 27.25, '05-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Aug 16', 0, 0, 0, 285.74, '09-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Aug 16', 0, 0, 0, 39.11, '09-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Sep 16', 0, 0, 0, 511.63, '09-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Sep 16', 0, 0, 0, 43.61, '09-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Oct 16', 0, 0, 0, 464.11, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Oct 16', 0, 0, 0, 51.59, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Nov 16', 0, 0, 0, 447.26, '09-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Nov 16', 0, 0, 0, 45.05, '09-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 4 Aug 16', 0, 0, 0, 112.08, '04-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 4 Sep 16', 0, 0, 0, 111.15, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 4 Oct 16', 0, 0, 0, 97.45, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 4 Nov 16', 0, 0, 0, 97.45, '04-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Dedicated data line 4 Dec 16', 0, 0, 0, 97.45, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Aug 16 - Sydney to Canberra', 0, 0, 0, 599.25, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '17 Aug 16 - Canberra to Sydney', 0, 0, 0, 599.25, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '29 Aug 16 - Sydney to Canberra', 0, 0, 0, 334.35, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '31 Aug 16 - Canberra to Sydney', 0, 0, 0, 174.30, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '14 Sep 16 - Sydney to Canberra', 0, 0, 0, 334.35, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Canberra to Sydney', 0, 0, 0, 334.35, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Sydney to Canberra', 0, 0, 0, 526.99, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '28 Nov 16 - Canberra to Sydney', 0, 0, 0, 599.25, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '14 Sep 16 - Sydney to Canberra', 0, 0, 0, 334.35, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Jason Falinski', 'Representative', 'Mackellar', 'New South Wales', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Canberra to Sydney', 0, 0, 0, 334.35, '16-Sep-2016', '');
