INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 273.00, 0, 273.00, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Official Government or Vice-Regal Function', 2, 273.00, 0, 546.00, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Economics - Reps', 2, 276.00, 0, 552.00, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Jul 16 - Melbourne to Canberra', 0, 0, 0, 1682.73, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Jul 16 - Canberra to Melbourne', 0, 0, 0, 0, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Aug 16 - Melbourne to Canberra', 0, 0, 0, 687.87, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Aug 16 - Canberra to Melbourne', 0, 0, 0, 687.87, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Canberra to Melbourne', 0, 0, 0, 689.24, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Sep 16 - Melbourne to Sydney', 0, 0, 0, 808.14, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '22 Sep 16 - Sydney to Melbourne', 0, 0, 0, 808.14, '22-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '4 Oct 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Oct 16 - Canberra to Melbourne', 0, 0, 0, 689.24, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Oct 16 - Canberra to Melbourne', 0, 0, 0, 689.24, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Oct 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Oct 16 - Canberra to Melbourne', 0, 0, 0, 689.24, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '10 Nov 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '24 Nov 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Dec 16 - Canberra to Melbourne', 0, 0, 0, 689.24, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 31 Jul 16', 0, 0, 0, 60.60, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 12 Aug 16', 0, 0, 0, 62.09, '12-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Aug to 16 Sep 16', 0, 0, 0, 902.21, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 24 Aug to 22 Sep 16', 0, 0, 0, 181.15, '22-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Sep to 16 Oct 16', 0, 0, 0, 902.21, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 29 Sep to 28 Oct 16', 0, 0, 0, 178.66, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Additional maintenance 14 Oct 16', 0, 0, 0, 389.26, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Oct to 16 Nov 16', 0, 0, 0, 902.20, '16-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 6 Nov to 18 Nov 16', 0, 0, 0, 116.67, '18-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Car cleaning 11 Nov 16', 0, 0, 0, 13.65, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 17 Nov to 16 Dec 16', 0, 0, 0, 902.20, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Aug 16 - Melbourne', 0, 0, 0, 60.70, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Aug 16 - Canberra', 0, 0, 0, 41.80, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Aug 16 - Melbourne', 0, 0, 0, 58.77, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Aug 16 - Melbourne', 0, 0, 0, 86.90, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne', 0, 0, 0, 86.90, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Sep 16 - Canberra', 0, 0, 0, 80.40, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Sep 16 - Canberra', 0, 0, 0, 40.00, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Sep 16 - Melbourne', 0, 0, 0, 71.87, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Melbourne', 0, 0, 0, 56.77, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Sydney', 0, 0, 0, 43.70, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Sep 16 - Sydney', 0, 0, 0, 40.00, '22-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Sep 16 - Melbourne', 0, 0, 0, 95.45, '22-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Oct 16 - Melbourne', 0, 0, 0, 93.45, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Oct 16 - Canberra', 0, 0, 0, 41.80, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Oct 16 - Canberra', 0, 0, 0, 40.00, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Oct 16 - Canberra', 0, 0, 0, 40.00, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Canberra', 0, 0, 0, 40.00, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Canberra', 0, 0, 0, 40.00, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Canberra', 0, 0, 0, 78.60, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Canberra', 0, 0, 0, 40.00, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Canberra', 0, 0, 0, 40.00, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Canberra', 0, 0, 0, 40.00, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Melbourne', 0, 0, 0, 56.05, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne', 0, 0, 0, 86.90, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Canberra', 0, 0, 0, 40.00, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Melbourne', 0, 0, 0, 56.15, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Oct 16 - Melbourne', 0, 0, 0, 86.90, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Oct 16 - Melbourne', 0, 0, 0, 71.87, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne', 0, 0, 0, 86.90, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '10 Nov 16 - Melbourne', 0, 0, 0, 78.60, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Nov 16 - Melbourne', 0, 0, 0, 86.90, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Nov 16 - Melbourne', 0, 0, 0, 74.49, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne', 0, 0, 0, 86.90, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Canberra', 0, 0, 0, 80.40, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '30 Nov 16 - Canberra', 0, 0, 0, 40.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Canberra', 0, 0, 0, 40.00, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Melbourne', 0, 0, 0, 57.91, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Melbourne', 0, 0, 0, 89.63, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '29 Aug 16', 0, 0, 0, 17.15, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '29 Aug 16', 0, 0, 0, 15.94, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '1 Sep 16', 0, 0, 0, 110.10, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '4 Oct 16', 0, 0, 0, 8.58, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '11 Oct 16', 0, 0, 0, 10.09, '11-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '17 Oct 16', 0, 0, 0, 9.59, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '17 Oct 16', 0, 0, 0, 10.39, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '18 Oct 16', 0, 0, 0, 10.19, '18-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '19 Oct 16', 0, 0, 0, 10.60, '19-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '23 Nov 16', 0, 0, 0, 24.74, '23-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '27 Nov 16', 0, 0, 0, 8.44, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '27 Nov 16', 0, 0, 0, 8.73, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 18 Jul 16', 0, 0, 0, 25.23, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 22189.23, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 502.28, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Aug to 31 Aug 16', 0, 0, 0, 365.86, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Compact power adapter 26 Aug 16', 0, 0, 0, 99.95, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Camera battery charger 26 Aug 16', 0, 0, 0, 62.73, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '2 Pens 27 Aug 16', 0, 0, 0, 3.62, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '2 Notes flags 27 Aug 16', 0, 0, 0, 3.64, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '2 Pens 27 Aug 16', 0, 0, 0, 1.82, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '2 Highlighters 27 Aug 16', 0, 0, 0, 1.80, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Weekly note book 27 Aug 16', 0, 0, 0, 14.31, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Tablet Case 27 Aug 16', 0, 0, 0, 8.18, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Key topper 27 Aug 16', 0, 0, 0, 1.82, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Shield case 27 Aug 16', 0, 0, 0, 6.36, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Nov 16', 0, 0, 0, 0.19, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Nov 16', 0, 0, 0, 0.01, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 226.69, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Sep to 30 Sep 16', 0, 0, 0, 1191.18, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '200 C5 Blank envelopes 6 Sep 16', 0, 0, 0, 50.00, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 20.42, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Oct to 31 Oct 16', 0, 0, 0, 50.35, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 0, 276.05, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '100 Printed items 5 Sep 16', 0, 0, 0, 110.00, '05-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Personalised letterhead stationery 18 Sep 16', 0, 0, 0, 225.00, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Personalised letterhead stationery 19 Sep 16', 0, 0, 0, 225.00, '19-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '500 Printed items 5 Oct 16', 0, 0, 0, 343.75, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '8,000 Personalised letterhead stationery 5 Oct 16', 0, 0, 0, 1535.00, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'PO Box 102 rental 1 Nov 16 to 31 Mar 17', 0, 0, 0, 93.18, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 31 Aug to 25 Sep 16', 0, 0, 0, 16.69, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '17 The Australian Financial Review 31 Aug to 25 Sep 16', 0, 0, 0, 61.82, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '17 The Australian 31 Aug to 25 Sep 16', 0, 0, 0, 41.73, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '17 The Age 31 Aug to 25 Sep 16', 0, 0, 0, 38.64, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '17 Herald Sun 31 Aug to 25 Sep 16', 0, 0, 0, 23.18, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Neos Kosmos 17 Sep 16', 0, 0, 0, 9.09, '17-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '16 The Australian 26 Sep to 30 Oct 16', 0, 0, 0, 39.27, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Australian Financial Review 26 Sep to 30 Oct 16', 0, 0, 0, 58.18, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 Herald Sun 26 Sep to 30 Oct 16', 0, 0, 0, 21.82, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 26 Sep to 30 Oct 16', 0, 0, 0, 15.71, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '10 The Age 26 Sep to 30 Oct 16', 0, 0, 0, 25.45, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 The Age 26 Sep to 30 Oct 16', 0, 0, 0, 2.55, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Age 26 Sep to 30 Oct 16', 0, 0, 0, 11.36, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 31 Oct to 27 Nov 16', 0, 0, 0, 13.75, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '14 The Australian Financial Review 31 Oct to 27 Nov 16', 0, 0, 0, 50.91, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '14 The Australian 31 Oct to 27 Nov 16', 0, 0, 0, 34.36, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '14 Herald Sun 31 Oct to 27 Nov 16', 0, 0, 0, 19.09, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '14 The Age 31 Oct to 27 Nov 16', 0, 0, 0, 35.64, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones directory charges 2 Jul to 31 Dec 16', 0, 0, 0, 1962.29, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Aug 16', 0, 0, 0, 60.07, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Sep 16', 0, 0, 0, 197.47, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Sep 16', 0, 0, 0, 27.27, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Oct 16', 0, 0, 0, 218.07, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Oct 16', 0, 0, 0, 27.27, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Nov 16', 0, 0, 0, 127.48, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Nov 16', 0, 0, 0, 27.27, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '29 Aug 16 - Melbourne to Canberra', 0, 0, 0, 159.19, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra to Melbourne', 0, 0, 0, 159.19, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '28 Nov 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '29 Aug 16 - Melbourne', 0, 0, 0, 73.80, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra', 0, 0, 0, 40.00, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '1 Sep 16 - Melbourne', 0, 0, 0, 66.63, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne', 0, 0, 0, 71.18, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra', 0, 0, 0, 47.96, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne', 0, 0, 0, 66.63, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Nov 16 - Melbourne', 0, 0, 0, 81.04, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne to Canberra', 0, 0, 0, 416.12, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Julia Banks', 'Representative', 'Chisholm', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '15-Sep-2016', '');
