INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Yeppoon', 'Electorate Business', 2, 90.00, 0, 180.00, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Melbourne', 'Electorate Business', 1, 382.00, 0, 382.00, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Sydney', 'Electorate Business', 2, 400.00, 0, 800.00, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Legal and Constitutional Affairs', 1, 276.00, 0, 276.00, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Kawana', 'Electorate Business', 2, 90.00, 0, 180.00, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Charleville', 'Electorate Business', 3, 268.00, 0, 804.00, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Sydney', 'Electorate Business', 1, 134.00, 0, 134.00, '19-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Rockhampton', 'Electorate Business', 1, 96.00, 0, 96.00, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Aug 16 - Brisbane to Canberra', 0, 0, 0, 597.09, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Aug 16 - Canberra to Brisbane', 0, 0, 0, 203.37, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '19 Aug 16 - Brisbane to Townsville', 0, 0, 0, 206.07, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '19 Aug 16 - Townsville to Brisbane', 0, 0, 0, 183.23, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '22 Aug 16 - Brisbane to Canberra', 0, 0, 0, 203.37, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '26 Aug 16 - Canberra to Brisbane', 0, 0, 0, 203.37, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '29 Aug 16 - Brisbane to Sydney', 0, 0, 0, 790.66, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '29 Aug 16 - Sydney to Canberra', 0, 0, 0, 0, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Sep 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Sep 16 - Melbourne to Brisbane', 0, 0, 0, 211.84, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Brisbane to Canberra', 0, 0, 0, 203.37, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Canberra to Brisbane', 0, 0, 0, 535.53, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Brisbane to Rockhampton', 0, 0, 0, 0, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Sep 16 - Rockhampton to Brisbane', 0, 0, 0, 388.46, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Sep 16 - Brisbane to Melbourne', 0, 0, 0, 0, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '19 Sep 16 - Melbourne to Brisbane', 0, 0, 0, 211.84, '19-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '23 Sep 16 - Brisbane to Sydney', 0, 0, 0, 164.75, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Sep 16 - Sydney to Brisbane', 0, 0, 0, 272.80, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '4 Oct 16 - Brisbane to Canberra', 0, 0, 0, 739.64, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '5 Oct 16 - Canberra to Sydney', 0, 0, 0, 282.30, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '5 Oct 16 - Sydney to Brisbane', 0, 0, 0, 0, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Brisbane to Canberra', 0, 0, 0, 289.27, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Oct 16 - Newcastle to Brisbane', 0, 0, 0, 270.88, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Oct 16 - Brisbane to Norfolk Island', 0, 0, 0, 1274.62, '18-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Norfolk Island to Sydney', 0, 0, 0, 0, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Sydney to Brisbane', 0, 0, 0, 164.75, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Oct 16 - Brisbane to Canberra', 0, 0, 0, 203.37, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Oct 16 - Canberra to Brisbane', 0, 0, 0, 203.37, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '29 Oct 16 - Brisbane to Newcastle', 0, 0, 0, 270.88, '29-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '30 Oct 16 - Newcastle to Brisbane', 0, 0, 0, 270.88, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Brisbane to Canberra', 0, 0, 0, 318.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Nov 16 - Canberra to Sydney', 0, 0, 0, 626.43, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Nov 16 - Sydney to Brisbane', 0, 0, 0, 0, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '19 Nov 16 - Brisbane to Sydney', 0, 0, 0, 164.75, '19-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Sydney to Canberra', 0, 0, 0, 121.30, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Nov 16 - Canberra to Brisbane', 0, 0, 0, 535.60, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Nov 16 - Brisbane to Rockhampton', 0, 0, 0, 0, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '26 Nov 16 - Rockhampton to Brisbane', 0, 0, 0, 180.37, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Brisbane to Canberra', 0, 0, 0, 476.06, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Dec 16 - Canberra to Brisbane', 0, 0, 0, 203.37, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Dec 16 - Brisbane to Townsville', 0, 0, 0, 206.07, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Aug 16 - Canberra', 0, 0, 0, 40.00, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Aug 16 - Canberra', 0, 0, 0, 78.60, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '31 Aug 16 - Canberra', 0, 0, 0, 40.00, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Sep 16 - Canberra', 0, 0, 0, 40.00, '12-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '13 Sep 16 - Canberra', 0, 0, 0, 40.00, '13-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra', 0, 0, 0, 47.16, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Sep 16 - Melbourne', 0, 0, 0, 82.80, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '19 Sep 16 - Melbourne', 0, 0, 0, 225.42, '19-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '19 Sep 16 - Melbourne', 0, 0, 0, 97.88, '19-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Sep 16 - Sydney', 0, 0, 0, 49.80, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '4 Oct 16 - Canberra', 0, 0, 0, 41.80, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Canberra', 0, 0, 0, 78.60, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Oct 16 - Canberra', 0, 0, 0, 40.00, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '10 Oct 16 - Canberra', 0, 0, 0, 40.00, '10-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Oct 16 - Canberra', 0, 0, 0, 47.96, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Oct 16 - Canberra', 0, 0, 0, 40.00, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Oct 16 - Canberra', 0, 0, 0, 40.00, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Oct 16 - Canberra', 0, 0, 0, 91.70, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Oct 16 - Canberra', 0, 0, 0, 40.00, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Oct 16 - Canberra', 0, 0, 0, 40.00, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Nov 16 - Canberra', 0, 0, 0, 80.40, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '10 Nov 16 - Canberra', 0, 0, 0, 40.00, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Canberra', 0, 0, 0, 78.60, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Canberra', 0, 0, 0, 78.60, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '30 Nov 16 - Canberra', 0, 0, 0, 40.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 14 Jul 16', 0, 0, 0, 14.73, '14-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 25 Jul 16', 0, 0, 0, 13.64, '25-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 27 Jul 16', 0, 0, 0, 13.64, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 15 Aug 16', 0, 0, 0, 26.04, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 15 Aug 16', 0, 0, 0, 25.03, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 19 Aug 16', 0, 0, 0, 22.50, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 22 Aug 16', 0, 0, 0, 36.13, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 23 Sep 16', 0, 0, 0, 14.82, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 25 Jul and 27 Jul 16', 0, 0, 0, 84.55, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 15 Aug and 17 Aug 16', 0, 0, 0, 51.18, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking 19 Aug 16', 0, 0, 0, 48.18, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 22 Aug and 25 Aug 16', 0, 0, 0, 59.73, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 29 Aug and 2 Sep 16', 0, 0, 0, 67.64, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 9 Oct and 17 Oct 16', 0, 0, 0, 90.73, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 18 Oct and 21 Oct 16', 0, 0, 0, 50.76, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 27 Oct and 29 Oct 16', 0, 0, 0, 66.36, '29-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 29 Oct and 30 Oct 16', 0, 0, 0, 33.07, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 6 Nov and 11 Nov 16', 0, 0, 0, 63.21, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 19 Nov and 26 Nov 16', 0, 0, 0, 72.48, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Car Costs', 'Parking', 'From 1 July 2016', '', '', '', 'Parking between 27 Nov and 2 Dec 16', 0, 0, 0, 63.21, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 35798.26, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 0.40, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 3.78, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 139.14, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 4.28, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 21.86, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 437.24, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Oct to 31 Oct 16', 0, 0, 0, 566.16, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '3 Self-ink date stampers 3 Oct 16', 0, 0, 0, 73.53, '03-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Stamp pad ink 3 Oct 16', 0, 0, 0, 6.34, '03-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Digital camera 17 Oct 16', 0, 0, 0, 1327.27, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Digital camera accessories 17 Oct 16', 0, 0, 0, 1316.95, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 10.29, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 60.35, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Digital camera 28 Oct 16', 0, 0, 0, 1395.45, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Coffee machine 6 Nov 16', 0, 0, 0, 180.91, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'General office consumables 10 Nov 16', 0, 0, 0, 107.64, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Digital AV adapter 24 Nov 16', 0, 0, 0, 53.64, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Lightning digital AV adapter AME 24 Nov 16', 0, 0, 0, 68.18, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '16 Energiser batteries packs 25 Nov 16', 0, 0, 0, 18.08, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 17 Oct 16', 0, 0, 0, 300.00, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '15,000 Personalised letterhead stationery 17 Oct 16', 0, 0, 0, 1542.73, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 0, 179.64, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 20 Aug 16', 0, 0, 0, 25.02, '20-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 21 Sep 16', 0, 0, 0, 1159.67, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 21 Sep 16', 0, 0, 0, 211.21, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 21 Oct 16', 0, 0, 0, 311.69, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 21 Oct 16', 0, 0, 0, 31.77, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 21 Nov 16', 0, 0, 0, 281.95, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 21 Nov 16', 0, 0, 0, 32.04, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 10 Sep 16', 0, 0, 0, 88.55, '10-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 10 Oct 16', 0, 0, 0, 127.21, '10-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residentialphones 10 Nov 16', 0, 0, 0, 37.44, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 9 Dec 16', 0, 0, 0, 51.62, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '13 Sep 16 - Hobart to Melbourne', 0, 0, 0, 456.86, '13-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '13 Sep 16 - Melbourne to Canberra', 0, 0, 0, 0, '13-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Melbourne', 0, 0, 0, 456.86, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne to Hobart', 0, 0, 0, 0, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '14 Sep 16 - Coolangatta to Sydney', 0, 0, 0, 278.23, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '14 Sep 16 - Sydney to Canberra', 0, 0, 0, 0, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Coolangatta', 0, 0, 0, 254.92, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '14 Sep 16 - Melbourne to Canberra', 0, 0, 0, 159.19, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Pauline Hanson', 'Senator', '', 'Queensland', 'Pauline Hanson''s One Nation', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Melbourne', 0, 0, 0, 149.76, '15-Sep-2016', '');
