INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 July 2016', '', '', 'Perth', 'Shadow Minister - Official Business', 2, 411.00, 0, 822.00, '13-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 July 2016', '', '', 'Geelong', 'Shadow Minister - Official Business', 1, 283.00, 0, 283.00, '15-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 22 Jul to 21 Aug 16', 0, 0, 0, 1067.44, '21-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 5 Aug to 22 Aug 16', 0, 0, 0, 93.91, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 22 Aug to 21 Sep 16', 0, 0, 0, 1067.44, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 28 Aug to 18 Sep 16', 0, 0, 0, 163.50, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 22 Sep to 21 Oct 16', 0, 0, 0, 1067.44, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 9 Oct to 22 Oct 16', 0, 0, 0, 99.91, '22-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 22 Oct to 21 Nov 16', 0, 0, 0, 1067.44, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Infringement notice fee 10 May 16', 0, 0, 0, 15.00, '10-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Fuel 31 May to 23 Jun 16', 0, 0, 0, 269.45, '23-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Lease 22 Jun to 21 Jul 16', 0, 0, 0, 1067.44, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Fuel 29 Jun to 22 Jul 16', 0, 0, 0, 196.62, '22-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 July 2016', '', '', '', '14 Jun 16 - Perth', 0, 0, 0, 292.13, '14-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 July 2016', '', '', '', '26 Jun 16 - Townsville', 0, 0, 0, 42.00, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 July 2016', '', '', '', '27 Jun 16 - Townsville', 0, 0, 0, 54.40, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 July 2016', '', '', '', '27 Jun 16 - Townsville', 0, 0, 0, 42.00, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 July 2016', '', '', '', '28 Jun 16 - Townsville', 0, 0, 0, 60.48, '28-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 July 2016', '', '', '', '29 Jun 16 - Townsville', 0, 0, 0, 60.48, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'Before 1 July 2016', '', '', '', '29 Jun 16 - Townsville', 0, 0, 0, 60.48, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Other Car Costs', 'Before 1 July 2016', '', '', '', 'Melbourne 15 Jun to 16 Jun 16', 0, 0, 0, 178.90, '16-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Other Car Costs', 'Before 1 July 2016', '', '', '', 'Launceston to Devonport 20 Jun to 21 Jun 16', 0, 0, 0, 92.05, '21-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Other Car Costs', 'Before 1 July 2016', '', '', '', 'Rockhampton to Hervey Bay 27 Jun to 28 Jun 16', 0, 0, 0, 429.49, '28-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Parking', 'Before 1 July 2016', '', '', '', 'Parking between 13 Jun and 16 Jun 16', 0, 0, 0, 107.27, '16-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 81252.98, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 4291.27, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Jul to 31 Jul 16', 0, 0, 0, 905.00, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 205.92, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 306.25, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Sep to 30 Sep 16', 0, 0, 0, 1441.10, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 1500.00, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Software reimbursement 2016/17', 0, 0, 0, 933.64, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 May to 27 Jun 16', 0, 0, 0, 105.40, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jun to 30 Jun 16', 0, 0, 0, 104.92, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jun to 27 Nov 16', 0, 0, 0, 1013.17, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jun to 27 Nov 16', 0, 0, 0, 15.21, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Aug to 31 Aug 16', 0, 0, 0, 909.09, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Aug to 31 Aug 16', 0, 0, 0, -22.73, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 4 Aug 16', 0, 0, 0, 420.00, '04-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '500 Personalised letterhead stationery 19 Aug 16', 0, 0, 0, 332.73, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 1 Sep 16', 0, 0, 0, 290.00, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 0, 1785.87, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 21 Oct 16', 0, 0, 0, 440.00, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 0, 2258.95, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution late payment fee Nov 16', 0, 0, 0, 15.00, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Nov to 30 Nov 16', 0, 0, 0, -22.73, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 25 Nov 16', 0, 0, 0, 290.00, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 8 Dec 16', 0, 0, 0, 3046.50, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '69,000 Printed items 9 Dec 16', 0, 0, 0, 19243.64, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 4 Mar 16', 0, 0, 0, 313.18, '04-Mar-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Printing 31 May 16', 0, 0, 0, 720.00, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '5,000 Printed items 31 May 16', 0, 0, 0, 1021.82, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 1 Jun to 30 Jun 16', 0, 0, 0, 3460.30, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 16 Jun 16', 0, 0, 0, 3046.50, '16-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 20 Jun 16', 0, 0, 0, 880.00, '20-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '69,000 Printed items 21 Jun 16', 0, 0, 0, 5761.82, '21-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '2 Printed items 25 Jun to 29 Jun 16', 0, 0, 0, 3653.52, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 27 Jun 16', 0, 0, 0, 880.00, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 28 Jun 16', 0, 0, 0, 3046.50, '28-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 9 Jul to 31 Jul 16', 0, 0, 0, 8.04, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '2 The Daily Telegraph (Sat) 9 Jul to 31 Jul 16', 0, 0, 0, 4.00, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '2 The Daily Telegraph (Sat) 9 Jul to 31 Jul 16', 0, 0, 0, 4.36, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Illawarra Mercury (Sat) 9 Jul to 31 Jul 16', 0, 0, 0, 8.36, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sunday Telegraph 9 Jul to 31 Jul 16', 0, 0, 0, 10.18, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sun-Herald 9 Jul to 31 Jul 16', 0, 0, 0, 10.91, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sydney Morning Herald (Sat) 9 Jul to 31 Jul 16', 0, 0, 0, 12.73, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Australian 9 Jul to 31 Jul 16', 0, 0, 0, 12.73, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Financial Review 9 Jul to 31 Jul 16', 0, 0, 0, 14.55, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 1 Aug to 28 Aug 16', 0, 0, 0, 1.82, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '21 The Australian Financial Review 1 Aug to 28 Aug 16', 0, 0, 0, 76.36, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '21 Illawarra Mercury 1 Aug to 28 Aug 16', 0, 0, 0, 26.73, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Weekend Financial Review 6 Aug to 4 Sep 16', 0, 0, 0, 18.18, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '2 The Sunday Telegraph 6 Aug to 4 Sep 16', 0, 0, 0, 5.45, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '3 The Sunday Telegraph 6 Aug to 4 Sep 16', 0, 0, 0, 7.64, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 Illawarra Mercury (Sat) 6 Aug to 4 Sep 16', 0, 0, 0, 10.45, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Daily Telegraph (Sat) 6 Aug to 4 Sep 16', 0, 0, 0, 10.91, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Sun-Herald 6 Aug to 4 Sep 16', 0, 0, 0, 13.64, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Weekend Australian 6 Aug to 4 Sep 16', 0, 0, 0, 15.91, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 6 Aug to 4 Sep 16', 0, 0, 0, 9.82, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Sydney Morning Herald (Sat) 6 Aug to 4 Sep 16', 0, 0, 0, 15.91, '04-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 Illawarra Mercury 29 Aug to 25 Sept 16', 0, 0, 0, 1.27, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 The Daily Telegraph 29 Aug to 25 Sep 16', 0, 0, 0, 1.36, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Illawarra Mercury 29 Aug to 25 Sep 16', 0, 0, 0, 25.45, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian Financial Review 29 Aug to 25 Sep 16', 0, 0, 0, 72.73, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Refund of publications 29 Aug to 25 Sep 16', 0, 0, 0, -3.64, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 29 Aug to 25 Sep 16', 0, 0, 0, 1.82, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Illawarra Mercury (Sat) 5 Sep to 2 Oct 16', 0, 0, 0, 8.36, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 5 Sep to 2 Oct 16', 0, 0, 0, 8.04, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Financial Review 5 Sep to 2 Oct 16', 0, 0, 0, 14.55, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Australian 5 Sep to 2 Oct 16', 0, 0, 0, 12.73, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sydney Morning Herald (Sat) 5 Sep to 2 Oct 16', 0, 0, 0, 12.73, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sun-Herald 5 Sep to 2 Oct 16', 0, 0, 0, 10.91, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sunday Telegraph 5 Sep to 2 Oct 16', 0, 0, 0, 10.91, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Daily Telegraph (Sat) 5 Sep to 2 Oct 16', 0, 0, 0, 8.73, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '24 Illawarra Mercury 26 Sep to 30 Oct 16', 0, 0, 0, 30.55, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '24 The Australian Financial Review 26 Sep to 30 Oct 16', 0, 0, 0, 87.27, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 26 Sep to 30 Oct 16', 0, 0, 0, 1.82, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 8 Oct to 6 Nov 16', 0, 0, 0, 9.82, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Weekend Financial Review 8 Oct to 6 Nov 16', 0, 0, 0, 18.18, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Weekend Australian 8 Oct to 6 Nov 16', 0, 0, 0, 15.91, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Sydney Morning Herald (Sat) 8 Oct to 6 Nov 16', 0, 0, 0, 17.27, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Sun-Herald 8 Oct to 6 Nov 16', 0, 0, 0, 15.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Sunday Telegraph 8 Oct to 6 Nov 16', 0, 0, 0, 13.64, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 The Daily Telegraph (Sat) 8 Oct to 6 Nov 16', 0, 0, 0, 10.91, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '5 Illawarra Mercury (Sat) 8 Oct to 6 Nov 16', 0, 0, 0, 10.45, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '21 Illawarra Mercury 31 Oct to 27 Nov 16', 0, 0, 0, 26.73, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 31 Oct to 27 Nov 16', 0, 0, 0, 1.82, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian Financial Review 31 Oct to 27 Nov 16', 0, 0, 0, 72.73, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 The Daily Telegraph 31 Oct to 27 Nov 16', 0, 0, 0, 1.36, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Financial Review 12 Nov to 4 Dec 16', 0, 0, 0, 14.55, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 12 Nov to 4 Dec 16', 0, 0, 0, 8.04, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Australian 12 Nov to 4 Dec 16', 0, 0, 0, 12.73, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sydney Morning Herald (Sat) 12 Nov to 4 Dec 16', 0, 0, 0, 13.82, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sun-Herald 12 Nov to 4 Dec 16', 0, 0, 0, 12.00, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Sunday Telegraph 12 Nov to 4 Dec 16', 0, 0, 0, 10.91, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Daily Telegraph (Sat) 12 Nov to 4 Dec 16', 0, 0, 0, 8.73, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Illawarra Mercury (Sat) 12 Nov to 4 Dec 16', 0, 0, 0, 8.36, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 Illawarra Mercury 30 May to 26 Jun 16', 0, 0, 0, 26.73, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '21 The Australian Financial Review 30 May to 26 Jun 16', 0, 0, 0, 76.36, '26-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 The Sun-Herald 11 Jun to 3 Jul 16', 0, 0, 0, 10.91, '03-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', 'Administrative fees 11 Jun to 3 Jul 16', 0, 0, 0, 8.04, '03-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 The Weekend Financial Review 11 Jun to 3 Jul 16', 0, 0, 0, 14.55, '03-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 The Sydney Morning Herald (Sat) 11 Jun to 3 Jul 16', 0, 0, 0, 12.73, '03-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 The Sunday Telegraph 11 Jun to 3 Jul 16', 0, 0, 0, 10.18, '03-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 The Daily Telegraph (Sat) 11 Jun to 3 Jul 16', 0, 0, 0, 8.00, '03-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 Illawarra Mercury (Sat) 11 Jun to 3 Jul 16', 0, 0, 0, 8.36, '03-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '4 The Weekend Australian 11 Jun to 3 Jul 16', 0, 0, 0, 12.73, '03-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '27 The Australian Financial Review 27 Jun to 31 Jul 16', 0, 0, 0, 98.18, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '27 Illawarra Mercury 27 Jun to 31 Jul 16', 0, 0, 0, 34.36, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Jul 16', 0, 0, 0, 367.95, '09-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Jul 16', 0, 0, 0, 37.18, '09-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Aug 16', 0, 0, 0, 220.44, '09-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Aug 16', 0, 0, 0, 32.64, '09-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Sep 16', 0, 0, 0, 242.94, '09-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Sep 16', 0, 0, 0, 35.85, '09-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Oct 16', 0, 0, 0, 272.37, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Oct 16', 0, 0, 0, 33.35, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 9 Nov 16', 0, 0, 0, 239.53, '09-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 9 Nov 16', 0, 0, 0, 33.74, '09-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 5 Jul 16', 0, 0, 0, 31.77, '05-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 5 Aug 16', 0, 0, 0, 31.77, '05-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 5 Sep 16', 0, 0, 0, 31.77, '05-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones adj 5 Oct 16', 0, 0, 0, -7.31, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 July 2016', '', '', '', '27 Jun 16 - Mackay to Rockhampton', 0, 0, 0, 236.95, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 July 2016', '', '', '', '28 Jun 16 - Hervey Bay to Brisbane', 0, 0, 0, 472.97, '28-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 July 2016', '', '', '', '28 Jun 16 - Brisbane to Cairns', 0, 0, 0, 0, '28-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 July 2016', '', '', '', '29 Jun 16 - Cairns to Brisbane', 0, 0, 0, 390.87, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Sharon Bird', 'Representative', 'Cunningham', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 July 2016', '', '', '', '29 Jun 16 - Brisbane to Sydney', 0, 0, 0, 0, '29-Jun-2016', '');
