INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Official Government or Vice-Regal Function', 3, 273.00, 0, 819.00, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Ceduna', 'Electorate Business', 1, 286.00, 0, 286.00, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Melbourne', 'Education and Employment - Sen', 2, 382.00, 0, 764.00, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Community Affairs', 1, 276.00, 0, 276.00, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Senate Estimates', 5, 276.00, 0, 1380.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Melbourne', 'Economics - Sen', 1, 382.00, 0, 382.00, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '22 Aug 16 - Adelaide to Canberra', 0, 0, 0, 302.85, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Aug 16 - Canberra to Melbourne', 0, 0, 0, 336.49, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Aug 16 - Melbourne to Adelaide', 0, 0, 0, 0, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Adelaide to Canberra', 0, 0, 0, 340.01, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra to Adelaide', 0, 0, 0, 202.81, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Adelaide to Canberra', 0, 0, 0, 202.81, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Canberra to Sydney', 0, 0, 0, 505.72, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Sydney to Adelaide', 0, 0, 0, 0, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '26 Sep 16 - Adelaide to Ceduna', 0, 0, 0, 418.95, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Sep 16 - Ceduna to Adelaide', 0, 0, 0, 205.95, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Oct 16 - Adelaide to Melbourne', 0, 0, 0, 432.03, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '4 Oct 16 - Melbourne to Adelaide', 0, 0, 0, 190.48, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Adelaide to Canberra', 0, 0, 0, 491.54, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Oct 16 - Canberra to Adelaide', 0, 0, 0, 202.81, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Oct 16 - Adelaide to Canberra', 0, 0, 0, 491.54, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Canberra to Melbourne', 0, 0, 0, 500.53, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Melbourne to Adelaide', 0, 0, 0, 0, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Oct 16 - Adelaide to Sydney', 0, 0, 0, 174.25, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '3 Nov 16 - Sydney to Adelaide', 0, 0, 0, 174.25, '03-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Adelaide to Canberra', 0, 0, 0, 491.54, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Nov 16 - Canberra to Adelaide', 0, 0, 0, 491.54, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Nov 16 - Adelaide to Melbourne', 0, 0, 0, 154.98, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Nov 16 - Melbourne to Adelaide', 0, 0, 0, 190.48, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Adelaide to Canberra', 0, 0, 0, 491.54, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '24 Nov 16 - Canberra to Adelaide', 0, 0, 0, 202.81, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Adelaide to Melbourne', 0, 0, 0, 500.53, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne to Canberra', 0, 0, 0, 0, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '3 Dec 16 - Canberra to Melbourne', 0, 0, 0, 500.53, '03-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '3 Dec 16 - Melbourne to Adelaide', 0, 0, 0, 0, '03-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '13 Dec 16 - Adelaide to Mildura', 0, 0, 0, 411.22, '13-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Dec 16 - Mildura to Adelaide', 0, 0, 0, 411.22, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Adelaide', 0, 0, 0, 40.00, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Canberra', 0, 0, 0, 41.80, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Aug 16 - Canberra', 0, 0, 0, 40.00, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Aug 16 - Canberra', 0, 0, 0, 40.00, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Aug 16 - Adelaide', 0, 0, 0, 78.60, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Canberra', 0, 0, 0, 78.60, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '29 Nov 16 - Canberra', 0, 0, 0, 216.15, '29-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '21 Oct 16', 0, 0, 0, 23.41, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '25 Oct 16', 0, 0, 0, 23.21, '25-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '3 Nov 16', 0, 0, 0, 34.01, '03-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '11 Nov 16', 0, 0, 0, 24.27, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '11 Nov 16', 0, 0, 0, 25.23, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '11 Nov 16', 0, 0, 0, 25.23, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '14 Nov 16', 0, 0, 0, 21.90, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '14 Nov 16', 0, 0, 0, 58.79, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '15 Nov 16', 0, 0, 0, 28.15, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '20 Nov 16', 0, 0, 0, 28.56, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '24 Nov 16', 0, 0, 0, 31.18, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '27 Nov 16', 0, 0, 0, 28.58, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '3 Dec 16', 0, 0, 0, 30.07, '03-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 16 Sep 16', 0, 0, 0, 24.12, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 26 Sep 16', 0, 0, 0, 26.44, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 27 Sep 16', 0, 0, 0, 29.87, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 2 Oct 16', 0, 0, 0, 64.15, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 2 Oct 16', 0, 0, 0, 29.67, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 4 Oct 16', 0, 0, 0, 61.37, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 4 Oct 16', 0, 0, 0, 29.97, '04-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 9 Oct 16', 0, 0, 0, 28.65, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 14 Oct 16', 0, 0, 0, 30.57, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Reimbursement of taxi fare 14 Oct 16', 0, 0, 0, -30.57, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 16 Oct 16', 0, 0, 0, 27.65, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 21 Oct 16', 0, 0, 0, 23.20, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Reimbursement of taxi fare 21 Oct 16', 0, 0, 0, -23.20, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 50825.42, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 0.87, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 21.86, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Freight costs 5 Aug 16', 0, 0, 0, 600.00, '05-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 1.97, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 25.26, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 317.55, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 135.07, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 13.32, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 789.46, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 141.50, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 5.64, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 0, 82.03, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Nov to 30 Nov 16', 0, 0, 0, 471.80, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '6,400 Personalised letterhead stationery 27 Sep 16', 0, 0, 0, 950.00, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Printing 27 Sep 16', 0, 0, 0, 670.00, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Web-design 1 Nov 16', 0, 0, 0, 3333.33, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Web-design 29 Nov 16', 0, 0, 0, 5000.00, '29-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 6 Oct 16', 0, 0, 0, 2999.43, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 6 Oct 16', 0, 0, 0, 177.11, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Adelaide to Canberra', 0, 0, 0, 340.01, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra to Adelaide', 0, 0, 0, 202.81, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '10 Oct 16 - Adelaide to Canberra', 0, 0, 0, 151.53, '10-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '12 Oct 16 - Canberra to Adelaide', 0, 0, 0, 202.81, '12-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Adelaide to Melbourne', 0, 0, 0, 500.53, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne to Canberra', 0, 0, 0, 0, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Skye Kakoschke-Moore', 'Senator', '', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '28 Nov 16 - Canberra to Adelaide', 0, 0, 0, 491.54, '28-Nov-2016', '');
