INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 273.00, 0, 273.00, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Official Government or Vice-Regal Function', 2, 273.00, 0, 546.00, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 2, 273.00, 0, 546.00, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 6, 276.00, 0, 1656.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Sydney', 'Health - Reps', 1, 400.00, 0, 400.00, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 0, 828.00, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Jul 16 - Adelaide to Melbourne', 0, 0, 0, 686.61, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Jul 16 - Melbourne to Canberra', 0, 0, 0, 0, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '22 Jul 16 - Canberra to Adelaide', 0, 0, 0, 0, '22-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Aug 16 - Adelaide to Canberra', 0, 0, 0, 772.01, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Aug 16 - Canberra to Adelaide', 0, 0, 0, 859.66, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '23 Aug 16 - Adelaide to Canberra', 0, 0, 0, 861.02, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Aug 16 - Canberra to Adelaide', 0, 0, 0, 861.02, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Aug 16 - Adelaide to Melbourne', 0, 0, 0, 870.04, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Aug 16 - Melbourne to Canberra', 0, 0, 0, 0, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Sep 16 - Canberra to Sydney', 0, 0, 0, 875.52, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Sep 16 - Sydney to Adelaide', 0, 0, 0, 0, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Adelaide to Canberra', 0, 0, 0, 861.02, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Canberra to Melbourne', 0, 0, 0, 870.04, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Sep 16 - Melbourne to Adelaide', 0, 0, 0, 0, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Adelaide to Canberra', 0, 0, 0, 772.01, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '13 Oct 16 - Canberra to Adelaide', 0, 0, 0, 861.23, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Oct 16 - Adelaide to Canberra', 0, 0, 0, 861.23, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Oct 16 - Canberra to Adelaide', 0, 0, 0, 861.23, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Adelaide to Canberra', 0, 0, 0, 861.23, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Nov 16 - Canberra to Adelaide', 0, 0, 0, 861.23, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Nov 16 - Adelaide to Sydney', 0, 0, 0, 939.90, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Nov 16 - Sydney to Adelaide', 0, 0, 0, 939.90, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Nov 16 - Adelaide to Canberra', 0, 0, 0, 861.23, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '24 Nov 16 - Canberra to Adelaide', 0, 0, 0, 861.23, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Adelaide to Canberra', 0, 0, 0, 861.02, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '5 Dec 16 - Adelaide to Melbourne', 0, 0, 0, 870.25, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '5 Dec 16 - Melbourne to Canberra', 0, 0, 0, 0, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '5 Dec 16 - Canberra to Adelaide', 0, 0, 0, 861.23, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 7 Jul to 6 Aug 16', 0, 0, 0, 797.97, '06-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 7 Jul to 22 Jul 16', 0, 0, 0, 128.22, '22-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Car cleaning 26 Jul 16', 0, 0, 0, 54.50, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 29 Jul 16', 0, 0, 0, 18.65, '29-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Vehicle transport 29 Jul 16', 0, 0, 0, 38.50, '29-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 7 Aug to 6 Sep 16', 0, 0, 0, 797.97, '06-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 12 Aug 16', 0, 0, 0, 76.47, '12-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 3 Sep to 24 Sep 16', 0, 0, 0, 145.17, '24-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 7 Sep to 6 Oct 16', 0, 0, 0, 797.97, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 7 Oct to 6 Nov 16', 0, 0, 0, 797.97, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 14 Oct to 27 Oct 16', 0, 0, 0, 152.71, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Additional maintenance 1 Nov 16', 0, 0, 0, 643.16, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'End of lease adj 1 Nov 16', 0, 0, 0, -598.19, '01-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 2 Nov to 1 Dec 16', 0, 0, 0, 1167.18, '01-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 5 Nov to 19 Nov 16', 0, 0, 0, 151.19, '19-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Aug 16 - Adelaide', 0, 0, 0, 40.00, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Aug 16 - Adelaide', 0, 0, 0, 41.80, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Aug 16 - Adelaide', 0, 0, 0, 40.00, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Aug 16 - Canberra', 0, 0, 0, 80.40, '23-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 60.26, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 73.36, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Aug 16 - Canberra', 0, 0, 0, 40.00, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Aug 16 - Adelaide', 0, 0, 0, 41.80, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Aug 16 - Adelaide', 0, 0, 0, 78.60, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Aug 16 - Canberra', 0, 0, 0, 80.40, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Aug 16 - Canberra', 0, 0, 0, 78.60, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Aug 16 - Canberra', 0, 0, 0, 78.60, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra', 0, 0, 0, 78.60, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Sep 16 - Adelaide', 0, 0, 0, 41.80, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Sep 16 - Adelaide', 0, 0, 0, 78.60, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra', 0, 0, 0, 78.60, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Sep 16 - Adelaide', 0, 0, 0, 41.80, '16-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Oct 16 - Adelaide', 0, 0, 0, 78.60, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '13 Oct 16 - Adelaide', 0, 0, 0, 41.80, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Oct 16 - Adelaide', 0, 0, 0, 78.60, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Oct 16 - Adelaide', 0, 0, 0, 41.80, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Nov 16 - Adelaide', 0, 0, 0, 78.60, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Nov 16 - Adelaide', 0, 0, 0, 41.80, '11-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Adelaide', 0, 0, 0, 40.00, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Sydney', 0, 0, 0, 50.00, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Nov 16 - Sydney', 0, 0, 0, 40.00, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Nov 16 - Sydney', 0, 0, 0, 55.30, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Nov 16 - Sydney', 0, 0, 0, 66.24, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Nov 16 - Adelaide', 0, 0, 0, 41.80, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Nov 16 - Adelaide', 0, 0, 0, 40.00, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Nov 16 - Adelaide', 0, 0, 0, 41.80, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Adelaide', 0, 0, 0, 78.60, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Adelaide', 0, 0, 0, 41.80, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Adelaide', 0, 0, 0, 40.00, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Canberra', 0, 0, 0, 41.80, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Canberra', 0, 0, 0, 40.00, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Adelaide', 0, 0, 0, 41.80, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 52109.69, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Courier costs 27 Jul 16', 0, 0, 0, 22.33, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 0.82, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 0.02, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 29 Jul 16', 0, 0, 0, 1.15, '29-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 29 Jul 16', 0, 0, 0, 15.98, '29-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 2128.69, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Freight costs 10 Aug 16', 0, 0, 0, 240.00, '10-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 12 Aug 16', 0, 0, 0, 7.98, '12-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 12 Aug 16', 0, 0, 0, 1.15, '12-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 52.96, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 209.98, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 752.87, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Sep to 30 Sep 16', 0, 0, 0, 2049.01, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 146.79, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 25.23, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 375.25, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Laminator A3 6 Oct 16', 0, 0, 0, 117.27, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 7 Oct 16', 0, 0, 0, 23.98, '07-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 7 Oct 16', 0, 0, 0, 1.15, '07-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 47.95, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 129.84, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 0, 4523.56, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 4 Nov 16', 0, 0, 0, 1.15, '04-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 4 Nov 16', 0, 0, 0, 23.98, '04-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Courier costs 18 Nov 16', 0, 0, 0, 29.81, '18-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 2 Dec 16', 0, 0, 0, 23.98, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 2 Dec 16', 0, 0, 0, 1.15, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 16 Dec 16', 0, 0, 0, 1.15, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Water refills 16 Dec 16', 0, 0, 0, 39.98, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '500 Printed items 31 Aug 16', 0, 0, 0, 131.00, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Sep to 30 Sep 16', 0, 0, 0, -25.00, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Sep to 30 Sep 16', 0, 0, 0, 1000.00, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '40,000 Personalised letterhead stationery 21 Sep 16', 0, 0, 0, 1520.00, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '5,000 Personalised letterhead stationery 23 Sep 16', 0, 0, 0, 582.00, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 0, 909.09, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Oct to 31 Oct 16', 0, 0, 0, -22.73, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '500 Printed items 10 Oct 16', 0, 0, 0, 240.00, '10-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 12 Oct 16', 0, 0, 0, 390.00, '12-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 24 Oct 16', 0, 0, 0, 318.18, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Printed items 24 Oct 16', 0, 0, 0, 390.00, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '73,500 Printed items 24 Oct 16', 0, 0, 0, 5721.82, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 24 Oct 16', 0, 0, 0, 3386.36, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '73,500 Printed items 30 Nov 16', 0, 0, 0, 2820.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '73,376 Printed items 30 Nov 16', 0, 0, 0, 4630.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '74,000 Printed items 30 Nov 16', 0, 0, 0, 8080.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '10,000 Personalised letterhead stationery 8 Dec 16', 0, 0, 0, 752.00, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '2,000 Printed Items 9 Dec 16', 0, 0, 0, 550.00, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian 22 Aug to 18 Sep 16', 0, 0, 0, 9.82, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 22 Aug to 18 Sep 16', 0, 0, 0, 1.00, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Advertiser 22 Aug to 18 Sep 16', 0, 0, 0, 5.45, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian 13 Sep to 25 Sep 16', 0, 0, 0, 14.73, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '2 The Australian Financial Review 13 Sep to 25 Sep 16', 0, 0, 0, 7.27, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Advertiser 19 Sep to 16 Oct 16', 0, 0, 0, 27.27, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '19 The Australian 19 Sep to 16 Oct 16', 0, 0, 0, 46.64, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 19 Sep to 16 Oct 16', 0, 0, 0, 4.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian 26 Sep to 30 Oct 16', 0, 0, 0, 19.64, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian Financial Review 26 Sep to 30 Oct 16', 0, 0, 0, 29.09, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 17 Oct to 13 Nov 16', 0, 0, 0, 4.00, '13-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 17 Oct to 13 Nov 16', 0, 0, 0, 49.09, '13-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Advertiser 17 Oct to 13 Nov 16', 0, 0, 0, 27.27, '13-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian 31 Oct to 27 Nov 16', 0, 0, 0, 19.64, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian Financial Review 31 Oct to 27 Nov 16', 0, 0, 0, 29.09, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Advertiser 14 Nov to 11 Dec 16', 0, 0, 0, 27.27, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 14 Nov to 11 Dec 16', 0, 0, 0, 49.09, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 14 Nov to 11 Dec 16', 0, 0, 0, 4.00, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Steve Georganas', 'Representative', 'Hindmarsh', 'South Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 7 Nov 16', 0, 0, 0, 65.09, '07-Nov-2016', '');
