INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 273.00, 0, 273.00, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Official Government or Vice-Regal Function', 2, 273.00, 0, 546.00, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Sydney', 'Electorate Business', 1, 134.00, 0, 134.00, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Sydney', 'Electorate Business', 1, 134.00, 0, 134.00, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Jul 16 - Melbourne to Canberra', 0, 0, 0, 1762.73, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Jul 16 - Canberra to Melbourne', 0, 0, 0, 0, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Jul 16 - Melbourne to Sydney', 0, 0, 0, 781.55, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Jul 16 - Sydney to Melbourne', 0, 0, 0, 781.55, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '26 Jul 16 - Melbourne to Sydney', 0, 0, 0, 781.55, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '26 Jul 16 - Sydney to Melbourne', 0, 0, 0, 781.55, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Aug 16 - Melbourne to Canberra', 0, 0, 0, 687.87, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Aug 16 - Canberra to Melbourne', 0, 0, 0, 687.87, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '22 Aug 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '22 Aug 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra to Melbourne', 0, 0, 0, 689.24, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Sep 16 - Melbourne to Sydney', 0, 0, 0, 808.14, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Sep 16 - Sydney to Melbourne', 0, 0, 0, 808.14, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Oct 16 - Melbourne to Sydney', 0, 0, 0, 808.14, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Oct 16 - Sydney to Melbourne', 0, 0, 0, 808.14, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '13 Oct 16 - Canberra to Sydney', 0, 0, 0, 599.25, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Oct 16 - Sydney to Melbourne', 0, 0, 0, 730.58, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Oct 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Oct 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '10 Nov 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Nov 16 - Melbourne to Sydney', 0, 0, 0, 808.14, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Nov 16 - Sydney to Melbourne', 0, 0, 0, 808.14, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Melbourne to Canberra', 0, 0, 0, 613.09, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '24 Nov 16 - Canberra to Melbourne', 0, 0, 0, 613.09, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Dec 16 - Melbourne to Sydney', 0, 0, 0, 814.95, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Dec 16 - Sydney to Melbourne', 0, 0, 0, 814.95, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Jul 16 - Melbourne', 0, 0, 0, 66.05, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Jul 16 - Melbourne', 0, 0, 0, 66.74, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '26 Jul 16 - Melbourne', 0, 0, 0, 64.74, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '26 Jul 16 - Melbourne', 0, 0, 0, 71.98, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Jul 16 - Melbourne', 0, 0, 0, 67.36, '28-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '29 Jul 16 - Melbourne', 0, 0, 0, 206.91, '29-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Aug 16 - Melbourne', 0, 0, 0, 84.39, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Aug 16 - Canberra', 0, 0, 0, 56.82, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Aug 16 - Melbourne', 0, 0, 0, 87.70, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Melbourne', 0, 0, 0, 68.67, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Canberra', 0, 0, 0, 41.80, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Canberra', 0, 0, 0, 40.00, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Melbourne', 0, 0, 0, 62.81, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Aug 16 - Melbourne', 0, 0, 0, 85.70, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '29 Aug 16 - Canberra', 0, 0, 0, 40.00, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Sep 16 - Melbourne', 0, 0, 0, 145.96, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Sep 16 - Melbourne', 0, 0, 0, 79.84, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Melbourne', 0, 0, 0, 96.18, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Sydney', 0, 0, 0, 171.90, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Sydney', 0, 0, 0, 70.82, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Sydney', 0, 0, 0, 40.00, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Melbourne', 0, 0, 0, 64.04, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Melbourne', 0, 0, 0, 85.70, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Sydney', 0, 0, 0, 49.80, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Sydney', 0, 0, 0, 55.02, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Oct 16 - Melbourne', 0, 0, 0, 87.70, '06-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Oct 16 - Melbourne', 0, 0, 0, 85.70, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '13 Oct 16 - Sydney', 0, 0, 0, 50.00, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Sydney', 0, 0, 0, 40.00, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Sydney', 0, 0, 0, 56.33, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Oct 16 - Melbourne', 0, 0, 0, 87.70, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Oct 16 - Melbourne', 0, 0, 0, 87.35, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Nov 16 - Melbourne', 0, 0, 0, 255.89, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '10 Nov 16 - Melbourne', 0, 0, 0, 78.53, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Melbourne', 0, 0, 0, 85.70, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Sydney', 0, 0, 0, 54.90, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Nov 16 - Sydney', 0, 0, 0, 40.00, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Nov 16 - Sydney', 0, 0, 0, 40.00, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Nov 16 - Sydney', 0, 0, 0, 72.45, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Nov 16 - Melbourne', 0, 0, 0, 46.12, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Nov 16 - Melbourne', 0, 0, 0, 58.95, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Nov 16 - Melbourne', 0, 0, 0, 85.70, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Nov 16 - Melbourne', 0, 0, 0, 82.46, '24-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne', 0, 0, 0, 149.89, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '30 Nov 16 - Canberra', 0, 0, 0, 40.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Canberra', 0, 0, 0, 78.60, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Dec 16 - Melbourne', 0, 0, 0, 87.70, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Dec 16 - Melbourne', 0, 0, 0, 67.36, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Dec 16 - Sydney', 0, 0, 0, 69.43, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Dec 16 - Melbourne', 0, 0, 0, 102.11, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '1 Sep 16', 0, 0, 0, 13.32, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '1 Sep 16', 0, 0, 0, 78.84, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '12 Sep 16', 0, 0, 0, 10.80, '12-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '14 Sep 16', 0, 0, 0, 9.38, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '12 Oct 16', 0, 0, 0, 9.79, '12-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '13 Oct 16', 0, 0, 0, 10.27, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '14 Oct 16', 0, 0, 0, 11.51, '14-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '17 Oct 16', 0, 0, 0, 10.39, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '18 Oct 16', 0, 0, 0, 8.48, '18-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '20 Oct 16', 0, 0, 0, 78.65, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '1 Dec 16', 0, 0, 0, 9.21, '01-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '2 Dec 16', 0, 0, 0, 10.55, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 18 Jul 16', 0, 0, 0, 24.93, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 18 Jul 16', 0, 0, 0, 94.02, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 18 Jul 16', 0, 0, 0, 12.82, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 21 Jul 16', 0, 0, 0, 31.13, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 15 Aug 16', 0, 0, 0, 10.97, '15-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 16 Aug 16', 0, 0, 0, 9.81, '16-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Car Costs', 'Other Car Costs', 'From 1 July 2016', '', '', '', 'Taxi 17 Aug 16', 0, 0, 0, 7.97, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 67202.24, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 385.88, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 4.82, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Aug to 31 Aug 16', 0, 0, 0, 3063.85, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 8.77, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 219.87, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 747.13, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 9.66, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 214.26, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Oct to 31 Oct 16', 0, 0, 0, 837.17, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 460.09, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 14.24, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 0, 485.49, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Nov to 30 Nov 16', 0, 0, 0, 2984.20, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', '1 Digital camera 8 Nov 16', 0, 0, 0, 1280.86, '08-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Web-services 4 Aug 16', 0, 0, 0, 2340.91, '04-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Sep to 30 Sep 16', 0, 0, 0, -68.18, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Sep to 30 Sep 16', 0, 0, 0, 2833.91, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Web-design 14 Sep 16', 0, 0, 0, 12462.50, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '71,900 Printed items 18 Sep 16', 0, 0, 0, 3059.00, '18-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 29 Sep 16', 0, 0, 0, 5800.00, '29-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Printing 29 Sep 16', 0, 0, 0, 737.50, '29-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 0, 3984.85, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Oct to 31 Oct 16', 0, 0, 0, -11.36, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1,000 Personalised letterhead stationery 16 Oct 16', 0, 0, 0, 319.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '6,500 Printed items 20 Oct 16', 0, 0, 0, 955.00, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '10,000 Personalised letterhead stationery 20 Oct 16', 0, 0, 0, 717.19, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '30,000 Personalised letterhead stationery 20 Oct 16', 0, 0, 0, 1739.40, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '7,000 Personalised letterhead stationery 20 Oct 16', 0, 0, 0, 335.00, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '20,000 Personalised letterhead stationery 20 Oct 16', 0, 0, 0, 1268.44, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '20,000 Personalised letterhead stationery 24 Oct 16', 0, 0, 0, 2815.45, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 28 Oct 16', 0, 0, 0, 998.20, '28-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '2,000 Personalised letterhead stationery 15 Nov 16', 0, 0, 0, 687.70, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Printing 20 Nov 16', 0, 0, 0, 840.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '2,000 Printed items 21 Nov 16', 0, 0, 0, 1535.18, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '10,000 Personalised letterhead stationery 21 Nov 16', 0, 0, 0, 396.00, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '73,000 Printed items 28 Nov 16', 0, 0, 0, 6109.09, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '73,000 Printed items 30 Nov 16', 0, 0, 0, 7993.50, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '73,000 Printed items 30 Nov 16', 0, 0, 0, 7223.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Web-design 30 Nov 16', 0, 0, 0, 12462.50, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 21 Jul to 31 Jul 16', 0, 0, 0, 4.88, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian Financial Review 21 Jul to 31 Jul 16', 0, 0, 0, 29.09, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '10 The Age 21 Jul to 31 Jul 16', 0, 0, 0, 25.45, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Australian 22 Jul to 14 Aug 16', 0, 0, 0, 12.73, '14-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '16 Herald Sun 22 Jul to 14 Aug 16', 0, 0, 0, 21.82, '14-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 22 Jul to 14 Aug 16', 0, 0, 0, 8.91, '14-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '16 The Australian 22 Jul to 14 Aug 16', 0, 0, 0, 39.27, '14-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Herald Sun (Sat) 22 Jul to 14 Aug 16', 0, 0, 0, 8.73, '14-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Sunday Herald Sun 22 Jul to 14 Aug 16', 0, 0, 0, 9.82, '14-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 1 Aug to 28 Aug 16', 0, 0, 0, 14.18, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '28 The Age 1 Aug to 28 Aug 16', 0, 0, 0, 69.09, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '24 The Australian Financial Review 1 Aug to 28 Aug 16', 0, 0, 0, 87.27, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Australian 15 Aug to 11 Sep 16', 0, 0, 0, 12.73, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Herald Sun (Sat) 15 Aug to 11 Sep 16', 0, 0, 0, 8.73, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '3 Sunday Herald Sun 15 Aug to 11 Sep 16', 0, 0, 0, 8.18, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 15 Aug to 11 Sep 16', 0, 0, 0, 49.09, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 15 Aug to 11 Sep 16', 0, 0, 0, 27.27, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 Sunday Herald Sun 15 Aug to 11 Sep 16', 0, 0, 0, 2.45, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 15 Aug to 11 Sep 16', 0, 0, 0, 10.36, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian 23 Aug to 25 Sep 16', 0, 0, 0, 9.82, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Age 23 Aug to 25 Sep 16', 0, 0, 0, 12.36, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian Financial Review 23 Aug to 25 Sep 16', 0, 0, 0, 14.55, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Herald Sun 23 Aug to 25 Sep 16', 0, 0, 0, 11.27, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '24 The Australian Financial Review 29 Aug to 25 Sep 16', 0, 0, 0, 87.27, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '28 The Age 29 Aug to 25 Sep 16', 0, 0, 0, 69.09, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 29 Aug to 25 Sep 16', 0, 0, 0, 14.64, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Sunday Herald Sun 12 Sep to 9 Oct 16', 0, 0, 0, 10.91, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 12 Sep to 9 Oct 16', 0, 0, 0, 27.27, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Herald Sun (Sat) 12 Sep to 9 Oct 16', 0, 0, 0, 8.73, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Weekend Australian 12 Sep to 9 Oct 16', 0, 0, 0, 12.73, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 12 Sep to 9 Oct 16', 0, 0, 0, 11.27, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 12 Sep to 9 Oct 16', 0, 0, 0, 49.09, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '24 The Australian Financial Review 26 Sep to 23 Oct 16', 0, 0, 0, 87.27, '23-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '28 The Age 26 Sep to 23 Oct 16', 0, 0, 0, 74.82, '23-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 26 Sep to 23 Oct 16', 0, 0, 0, 14.82, '23-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 Herald Sun 26 Sep to 30 Oct 16', 0, 0, 0, 22.55, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Age 26 Sep to 30 Oct 16', 0, 0, 0, 29.09, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian 26 Sep to 30 Oct 16', 0, 0, 0, 19.64, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian Financial Review 26 Sep to 30 Oct 16', 0, 0, 0, 29.09, '30-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 Herald Sun 10 Oct to 6 Nov 16', 0, 0, 0, 27.27, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '20 The Australian 10 Oct to 6 Nov 16', 0, 0, 0, 49.09, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Herald Sun (Sat) 10 Oct to 6 Nov 16', 0, 0, 0, 8.73, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 Sunday Herald Sun 10 Oct to 6 Nov 16', 0, 0, 0, 10.91, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '4 The Australian 10 Oct to 6 Nov 16', 0, 0, 0, 12.73, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 10 Oct to 6 Nov 16', 0, 0, 0, 11.27, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 Herald Sun 31 Oct to 27 Nov 16', 0, 0, 0, 22.55, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Age 31 Oct to 27 Nov 16', 0, 0, 0, 29.09, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian 31 Oct to 27 Nov 16', 0, 0, 0, 19.64, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '8 The Australian Financial Review 31 Oct to 27 Nov 16', 0, 0, 0, 29.09, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '12 The Australian Financial Review 7 Nov to 20 Nov 16', 0, 0, 0, 43.64, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '14 The Age 7 Nov to 20 Nov 16', 0, 0, 0, 38.36, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', 'Administrative fees 7 Nov to 20 Nov 16', 0, 0, 0, 7.36, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones directory charges 2 Jul to 31 Dec 16', 0, 0, 0, 1962.29, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Jul 16', 0, 0, 0, 230.46, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Jul 16', 0, 0, 0, 32.50, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Aug 16', 0, 0, 0, 320.08, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Aug 16', 0, 0, 0, 32.14, '26-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Sep 16', 0, 0, 0, 347.36, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Sep 16', 0, 0, 0, 32.14, '26-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Oct 16', 0, 0, 0, 352.31, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Oct 16', 0, 0, 0, 32.50, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 26 Nov 16', 0, 0, 0, 371.22, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 26 Nov 16', 0, 0, 0, 32.14, '26-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '29 Aug 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra to Melbourne', 0, 0, 0, 416.12, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne to Canberra', 0, 0, 0, 689.24, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Canberra to Melbourne', 0, 0, 0, 689.24, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '29 Aug 16 - Melbourne', 0, 0, 0, 67.36, '29-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra', 0, 0, 0, 40.00, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '1 Sep 16 - Melbourne', 0, 0, 0, 75.90, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Tim Wilson', 'Representative', 'Goldstein', 'Victoria', 'Liberal Party of Australia', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Melbourne', 0, 0, 0, 87.70, '27-Nov-2016', '');
