INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 273.00, 0, 273.00, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Electorate Business', 1, 273.00, 0, 273.00, '21-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 0, 1104.00, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 July 2016', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 0, 1380.00, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '7 Jul 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '8 Jul 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Aug 16 - Brisbane to Sydney', 0, 0, 0, 781.48, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '18 Aug 16 - Sydney to Brisbane', 0, 0, 0, 781.48, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Aug 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '21-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '22 Aug 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '24 Aug 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Sep 16 - Canberra to Brisbane', 0, 0, 0, 476.06, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '11 Sep 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Sep 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Sep 16 - Brisbane to Sydney', 0, 0, 0, 781.48, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Sep 16 - Sydney to Brisbane', 0, 0, 0, 781.48, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '23 Sep 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '23 Sep 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '9 Oct 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '13 Oct 16 - Canberra to Brisbane', 0, 0, 0, 739.64, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '16 Oct 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Oct 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Brisbane to Sydney', 0, 0, 0, 781.48, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '21 Oct 16 - Sydney to Brisbane', 0, 0, 0, 781.48, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '24 Oct 16 - Brisbane to Sydney', 0, 0, 0, 781.48, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '24 Oct 16 - Sydney to Brisbane', 0, 0, 0, 781.48, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '6 Nov 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '10 Nov 16 - Canberra to Brisbane', 0, 0, 0, 739.64, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Nov 16 - Brisbane to Sydney', 0, 0, 0, 815.57, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '17 Nov 16 - Sydney to Brisbane', 0, 0, 0, 815.57, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '20 Nov 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '25 Nov 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '27 Nov 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '2 Dec 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '02-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '14 Dec 16 - Brisbane to Perth', 0, 0, 0, 2083.77, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 July 2016', '', '', '', '15 Dec 16 - Perth to Brisbane', 0, 0, 0, 2083.77, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 1 Jul to 26 Jul 16', 0, 0, 0, 294.47, '26-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 9 Jul to 8 Aug 16', 0, 0, 0, 1354.56, '08-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 31 Jul to 19 Aug 16', 0, 0, 0, 260.18, '19-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 9 Aug to 8 Sep 16', 0, 0, 0, 1354.56, '08-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 30 Aug to 24 Sep 16', 0, 0, 0, 236.52, '24-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 9 Sep to 8 Oct 16', 0, 0, 0, 1354.56, '08-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Fuel 27 Sep to 27 Oct 16', 0, 0, 0, 295.43, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 July 2016', '', '', '', 'Lease 9 Oct to 8 Nov 16', 0, 0, 0, 1354.55, '08-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Infringement notice fee 4 May 16', 0, 0, 0, 15.00, '04-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Fuel 30 May to 25 Jun 16', 0, 0, 0, 380.30, '25-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 July 2016', '', '', '', 'Lease 9 Jun to 8 Jul 16', 0, 0, 0, 1354.56, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '7 Jul 16 - Brisbane', 0, 0, 0, 45.30, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '7 Jul 16 - Canberra', 0, 0, 0, 59.44, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Jul 16 - Canberra', 0, 0, 0, 40.00, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Jul 16 - Canberra', 0, 0, 0, 40.00, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Jul 16 - Brisbane', 0, 0, 0, 49.60, '08-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '12 Jul 16 - Brisbane', 0, 0, 0, 44.00, '12-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Jul 16 - Brisbane', 0, 0, 0, 88.20, '23-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Aug 16 - Brisbane', 0, 0, 0, 40.00, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Aug 16 - Sydney', 0, 0, 0, 96.26, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Aug 16 - Sydney', 0, 0, 0, 49.78, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '18 Aug 16 - Brisbane', 0, 0, 0, 50.90, '18-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Aug 16 - Brisbane', 0, 0, 0, 78.60, '21-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Aug 16 - Canberra', 0, 0, 0, 80.40, '21-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Canberra', 0, 0, 0, 40.00, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Canberra', 0, 0, 0, 110.04, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Canberra', 0, 0, 0, 40.00, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '22 Aug 16 - Brisbane', 0, 0, 0, 49.60, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Brisbane', 0, 0, 0, 44.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 80.40, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Canberra', 0, 0, 0, 40.00, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Aug 16 - Brisbane', 0, 0, 0, 49.60, '24-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '28 Aug 16 - Brisbane', 0, 0, 0, 82.60, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '1 Sep 16 - Canberra', 0, 0, 0, 40.00, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '2 Sep 16 - Brisbane', 0, 0, 0, 45.70, '02-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '11 Sep 16 - Brisbane', 0, 0, 0, 83.60, '11-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Sep 16 - Brisbane', 0, 0, 0, 49.60, '15-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Brisbane', 0, 0, 0, 44.00, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Sydney', 0, 0, 0, 49.80, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Sydney', 0, 0, 0, 72.05, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Sep 16 - Brisbane', 0, 0, 0, 49.80, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Sep 16 - Brisbane', 0, 0, 0, 40.00, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Sep 16 - Canberra', 0, 0, 0, 145.90, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Sep 16 - Canberra', 0, 0, 0, 119.21, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '23 Sep 16 - Brisbane', 0, 0, 0, 45.60, '23-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '9 Oct 16 - Brisbane', 0, 0, 0, 82.60, '09-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '13 Oct 16 - Brisbane', 0, 0, 0, 45.00, '13-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '16 Oct 16 - Brisbane', 0, 0, 0, 82.60, '16-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Oct 16 - Brisbane', 0, 0, 0, 51.00, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Oct 16 - Brisbane', 0, 0, 0, 40.00, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Oct 16 - Sydney', 0, 0, 0, 50.00, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Oct 16 - Sydney', 0, 0, 0, 40.00, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '21 Oct 16 - Brisbane', 0, 0, 0, 50.60, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Oct 16 - Brisbane', 0, 0, 0, 44.00, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Oct 16 - Sydney', 0, 0, 0, 88.60, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '24 Oct 16 - Brisbane', 0, 0, 0, 51.00, '24-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '6 Nov 16 - Brisbane', 0, 0, 0, 78.60, '06-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '10 Nov 16 - Brisbane', 0, 0, 0, 50.60, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Nov 16 - Brisbane', 0, 0, 0, 44.00, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Nov 16 - Sydney', 0, 0, 0, 50.00, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Nov 16 - Sydney', 0, 0, 0, 41.92, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '17 Nov 16 - Brisbane', 0, 0, 0, 40.00, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '20 Nov 16 - Brisbane', 0, 0, 0, 78.60, '20-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '25 Nov 16 - Brisbane', 0, 0, 0, 49.60, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '27 Nov 16 - Brisbane', 0, 0, 0, 83.90, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '5 Dec 16 - Brisbane', 0, 0, 0, 40.00, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '8 Dec 16 - Brisbane', 0, 0, 0, 51.00, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Dec 16 - Perth', 0, 0, 0, 40.00, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '14 Dec 16 - Perth', 0, 0, 0, 41.31, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Dec 16 - Perth', 0, 0, 0, 40.00, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Dec 16 - Perth', 0, 0, 0, 40.00, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '15 Dec 16 - Brisbane', 0, 0, 0, 49.65, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '7 Jul 16', 0, 0, 0, 25.32, '07-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '1 Sep 16', 0, 0, 0, 25.23, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '10 Oct 16', 0, 0, 0, 30.47, '10-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '11 Oct 16', 0, 0, 0, 24.92, '11-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '12 Oct 16', 0, 0, 0, 27.04, '12-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '17 Oct 16', 0, 0, 0, 25.63, '17-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '8 Nov 16', 0, 0, 0, 25.90, '08-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '21 Nov 16', 0, 0, 0, 24.17, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '25 Nov 16', 0, 0, 0, 23.50, '25-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 July 2016', '', '', '', '1 Dec 16', 0, 0, 0, 22.63, '01-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 48034.85, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 July 2016', '', '', '', 'Aggregated Total', 0, 0, 0, 2291.09, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Jul to 31 Jul 16', 0, 0, 0, 3209.06, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Jul to 31 Jul 16', 0, 0, 0, 3372.85, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 58.84, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jul to 27 Aug 16', 0, 0, 0, 571.41, '27-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 160.27, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Aug to 27 Sep 16', 0, 0, 0, 4.49, '27-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Sep to 30 Sep 16', 0, 0, 0, 162.86, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Sep to 30 Sep 16', 0, 0, 0, 144.00, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 18.42, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Sep to 27 Oct 16', 0, 0, 0, 75.98, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 137.53, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Oct to 27 Nov 16', 0, 0, 0, 48.20, '27-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 0, 385.85, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 July 2016', '', '', '', 'Flags 1 Nov to 30 Nov 16', 0, 0, 0, 1680.01, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 May to 27 Jun 16', 0, 0, 0, 1637.12, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 May to 27 Jun 16', 0, 0, 0, 206.12, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'Flags 1 Jun to 30 Jun 16', 0, 0, 0, 391.49, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Colour copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 2717.95, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 July 2016', '', '', '', 'MFD Monochrome copy charge 28 Jun to 27 Jul 16', 0, 0, 0, 55.26, '27-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution late payment fee Jul 16', 0, 0, 0, 15.00, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Jul to 31 Jul 16', 0, 0, 0, 17.05, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 4 Jul to 18 Jul 16', 0, 0, 0, 161.23, '18-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 5 Jul 16', 0, 0, 0, 11.96, '05-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 5 Jul 16', 0, 0, 0, 653.80, '05-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Aug to 31 Aug 16', 0, 0, 0, 454.55, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution credit 1 Aug to 31 Aug 16', 0, 0, 0, -11.36, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 22 Aug 16', 0, 0, 0, 901.06, '22-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 31 Aug 16', 0, 0, 0, 566.30, '31-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Sep to 30 Sep 16', 0, 0, 0, 1.77, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 9 Sep 16', 0, 0, 0, 300.00, '09-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 14 Sep 16', 0, 0, 0, 687.18, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 14 Sep 16', 0, 0, 0, 1140.47, '14-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 25 Sep 16', 0, 0, 0, 593.02, '25-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 30 Sep 16', 0, 0, 0, 113.41, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', '1 Printed item 26 Oct 16', 0, 0, 0, 260.00, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Printing 26 Oct 16', 0, 0, 0, 30.00, '26-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'e-material 31 Oct 16', 0, 0, 0, 477.38, '31-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 July 2016', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 0, 2524.91, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 15 Apr 16', 0, 0, 0, 300.00, '15-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Printing 21 Apr 16', 0, 0, 0, 100.00, '21-Apr-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 9 May 16', 0, 0, 0, 20320.64, '09-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '31,063 Postal vote applications 9 May 16', 0, 0, 0, 848.02, '09-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Printing 11 May 16', 0, 0, 0, 300.00, '11-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Printing 13 May 16', 0, 0, 0, 250.00, '13-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 24 May 16', 0, 0, 0, 600.00, '24-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 27 May 16', 0, 0, 0, 949.85, '27-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '148,124 Printed items 31 May 16', 0, 0, 0, 4667.41, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 31 May 16', 0, 0, 0, 72.30, '31-May-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 1 Jun to 30 Jun 16', 0, 0, 0, 17177.77, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Printing 3 Jun 16', 0, 0, 0, 300.00, '03-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Distribution 12 Jun 16', 0, 0, 0, 5805.90, '12-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'Printing 20 Jun 16', 0, 0, 0, 900.00, '20-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 22 Jun 16', 0, 0, 0, 280.00, '22-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 22 Jun 16', 0, 0, 0, 2435.40, '22-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 27 Jun 16', 0, 0, 0, 948.29, '27-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 29 Jun 16', 0, 0, 0, 283.18, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 29 Jun 16', 0, 0, 0, 1655.00, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 29 Jun 16', 0, 0, 0, 1655.00, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 29 Jun 16', 0, 0, 0, 3310.00, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', '1 Printed item 29 Jun 16', 0, 0, 0, 2435.40, '29-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 30 Jun 16', 0, 0, 0, 275.13, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 July 2016', '', '', '', 'e-material 30 Jun 16', 0, 0, 0, 12.66, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '13 The Sunday Mail 1 Jul to 30 Sep 16', 0, 0, 0, 35.45, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '14 The Courier Mail (Sat) 1 Jul to 30 Sep 16', 0, 0, 0, 31.82, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '65 The Australian 1 Jul to 30 Sep 16', 0, 0, 0, 159.55, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '14 The Weekend Australian 1 Jul to 30 Sep 16', 0, 0, 0, 0, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '', 0, 0, 0, 44.55, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '65 The Courier Mail 1 Jul to 30 Sep 16', 0, 0, 0, 0, '30-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '', 0, 0, 0, 88.64, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '1 The Financial Times (digital) 18 Nov 16 to 17 Nov 17', 0, 0, 0, 0, '18-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '', 0, 0, 0, 335.40, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '302 The Australian Financial Review and 1 The Australian Financial Review (digital) 7 Dec 16 to 6 Dec 17', 0, 0, 0, 0, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 July 2016', '', '', '', '', 0, 0, 0, 715.47, '01-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '13 The Sunday Mail 1 Apr to 30 Jun 16', 0, 0, 0, 31.91, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '13 The Weekend Australian 1 Apr to 30 Jun 16', 0, 0, 0, 41.36, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '65 The Australian 1 Apr to 30 Jun 16', 0, 0, 0, 159.55, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '65 The Courier Mail 1 Apr to 30 Jun 16', 0, 0, 0, 88.64, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 July 2016', '', '', '', '13 The Courier Mail (Sat) 1 Apr to 30 Jun 16', 0, 0, 0, 26.00, '30-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 21 Jul 16', 0, 0, 0, 622.17, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 21 Jul 16', 0, 0, 0, 32.86, '21-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 20 Aug 16', 0, 0, 0, 313.29, '20-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 20 Aug 16', 0, 0, 0, 32.53, '20-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 21 Sep 16', 0, 0, 0, 313.55, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 21 Sep 16', 0, 0, 0, 32.26, '21-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 21 Oct 16', 0, 0, 0, 275.75, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 21 Oct 16', 0, 0, 0, 32.26, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office phones 21 Nov 16', 0, 0, 0, 277.84, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 July 2016', '', '', '', 'Office fax 21 Nov 16', 0, 0, 0, 33.41, '21-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 17 Jul 16', 0, 0, 0, 107.56, '17-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 17 Aug 16', 0, 0, 0, 156.35, '17-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 19 Sep 16', 0, 0, 0, 160.90, '19-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 20 Oct 16', 0, 0, 0, 123.98, '20-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 July 2016', '', '', '', 'Residential phones 17 Nov 16', 0, 0, 0, 129.93, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '28 Aug 16 - Brisbane to Canberra', 0, 0, 0, 799.62, '28-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 July 2016', '', '', '', '30 Aug 16 - Canberra to Brisbane', 0, 0, 0, 799.62, '30-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Spouse, Amount, Date, Notes)
VALUES ('Wayne Swan', 'Representative', 'Lilley', 'Queensland', 'Australian Labor Party', 'Family Travel Costs', 'COMCAR', 'From 1 July 2016', '', '', '', '30 Aug 16 - Brisbane', 0, 0, 0, 49.60, '30-Aug-2016', '');
