INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Electorate Business', 1, 400.00, 400.00, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Brisbane', 'Electorate Business', 1, 411.00, 411.00, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Brisbane', 'Electorate Business', 1, 411.00, 411.00, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Chair Parl Committee on Committee Business', 3, 276.00, 828.00, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Brisbane', 'Electorate Business', 1, 411.00, 411.00, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Feb 17 - Wellcamp to Sydney', 0, 0, 389.53, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Sydney to Canberra', 0, 0, 341.03, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Canberra to Brisbane', 0, 0, 478.43, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Wellcamp to Sydney', 0, 0, 725.03, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Sydney to Canberra', 0, 0, 0, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Canberra to Sydney', 0, 0, 725.03, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney to Wellcamp', 0, 0, 0, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Wellcamp to Sydney', 0, 0, 725.03, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Sydney to Canberra', 0, 0, 0, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Feb 17 - Canberra to Brisbane', 0, 0, 478.43, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Brisbane to Canberra', 0, 0, 497.34, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Mar 17 - Brisbane to Melbourne', 0, 0, 672.42, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Mar 17 - Melbourne to Wellcamp', 0, 0, 917.46, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Mar 17 - Wellcamp to Cairns', 0, 0, 171.82, '17-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Cairns to Brisbane', 0, 0, 712.66, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Brisbane to Canberra', 0, 0, 0, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '1 Oct 16 - Brisbane to Longreach', 0, 0, 80.00, '01-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '2 Oct 16 - Longreach to Brisbane', 0, 0, 88.00, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '1 Feb 17', 0, 0, 17.26, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '2 Feb 17', 0, 0, 43.26, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '2 Feb 17', 0, 0, 15.73, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '6 Feb 17', 0, 0, 63.67, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '12 Feb 17', 0, 0, 64.18, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '18 Feb 17', 0, 0, 9.69, '18-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '26 Feb 17', 0, 0, 28.77, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Car Costs', 'Other Car Costs', 'Before 1 January 2017', '', '', '', 'Cairns to Townsville 6 Jun to 10 Jun 16', 0, 0, 424.54, '10-Jun-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 29038.75, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 1414.55, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 23 Jan 17', 0, 0, 22.00, '23-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Jan to 23 Feb 17', 0, 0, 76.88, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Jan to 23 Feb 17', 0, 0, 5.13, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 101.55, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 3 Feb 17', 0, 0, 22.00, '03-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 24 Feb 17', 0, 0, 22.00, '24-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 14 Mar 17', 0, 0, 22.00, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Nov to 23 Dec 16', 0, 0, 2.53, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Nov to 23 Dec 16', 0, 0, 54.24, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Flags 1 Dec to 31 Dec 16', 0, 0, 234.84, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Water refills 21 Dec 16', 0, 0, 22.00, '21-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 68.36, '24-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 6.00, '24-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Jan to 31 Jan 17', 0, 0, -6.82, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 272.73, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '500 Personalised letterhead stationery 30 Jan 17', 0, 0, 120.00, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '500 Personalised letterhead stationery 30 Jan 17', 0, 0, 140.00, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 3135 rental 1 Apr 17 to 31 Mar 18', 0, 0, 271.82, '01-Apr-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 29 Sep 16', 0, 0, 1894.01, '29-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -4.55, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 181.82, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '5 The Chronicle (Sat) 9 Jan to 12 Feb 17', 0, 0, 9.09, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '29 The Australian Financial Review 9 Jan to 12 Feb 17', 0, 0, 105.45, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '10 The Western Star 9 Jan to 12 Feb 17', 0, 0, 13.64, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '24 The Queensland Times 9 Jan to 12 Feb 17', 0, 0, 32.73, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '25 The Australian 9 Jan to 12 Feb 17', 0, 0, 61.36, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '5 The Longreach Leader 9 Jan to 12 Feb 17', 0, 0, 7.50, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '25 The Courier Mail 9 Jan to 12 Feb 17', 0, 0, 34.09, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '6 Queensland Country Life 9 Jan to 12 Feb 17', 0, 0, 21.82, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '5 Balonne Beacon 9 Jan to 12 Feb 17', 0, 0, 6.82, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '5 North Queensland Register 9 Jan to 12 Feb 17', 0, 0, 9.09, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '5 The Courier Mail (Sat) 9 Jan to 12 Feb 17', 0, 0, 11.36, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '5 The Queensland Times (Sat) 9 Jan to 12 Feb 17', 0, 0, 9.09, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '5 The Weekend Australian 9 Jan to 12 Feb 17', 0, 0, 15.91, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '25 The Chronicle 9 Jan to 12 Feb 17', 0, 0, 34.09, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Weekend Australian 13 Feb to 12 Mar 17', 0, 0, 12.73, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 North Queensland Register 13 Feb to 12 Mar 17', 0, 0, 7.27, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Queensland Times (Sat) 13 Feb to 12 Mar 17', 0, 0, 7.27, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Longreach Leader 13 Feb to 12 Mar 17', 0, 0, 6.00, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Courier Mail (Sat) 13 Feb to 12 Mar 17', 0, 0, 9.09, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Chronicle (Sat) 13 Feb to 12 Mar 17', 0, 0, 7.27, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '8 The Western Star 13 Feb to 12 Mar 17', 0, 0, 11.64, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 Queensland Country Life 13 Feb to 12 Mar 17', 0, 0, 14.55, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 Balonne Beacon 13 Feb to 12 Mar 17', 0, 0, 5.82, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '24 The Australian Financial Review 13 Feb to 12 Mar 17', 0, 0, 87.27, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Queensland Times 13 Feb to 12 Mar 17', 0, 0, 30.91, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Courier Mail 13 Feb to 12 Mar 17', 0, 0, 27.27, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Chronicle 13 Feb to 12 Mar 17', 0, 0, 30.91, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian 13 Feb to 12 Mar 17', 0, 0, 54.55, '12-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Queensland Times 14 Nov to 11 Dec 16', 0, 0, 27.27, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Queensland Times (Sat) 14 Nov to 11 Dec 16', 0, 0, 7.27, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '8 The Western Star 14 Nov to 11 Dec 16', 0, 0, 10.91, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Chronicle 14 Nov to 11 Dec 16', 0, 0, 27.27, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Weekend Australian 14 Nov to 11 Dec 16', 0, 0, 12.73, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Longreach Leader 14 Nov to 11 Dec 16', 0, 0, 6.00, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Courier Mail (Sat) 14 Nov to 11 Dec 16', 0, 0, 9.09, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Chronicle (Sat) 14 Nov to 11 Dec 16', 0, 0, 7.27, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 North Queensland Register 14 Nov to 11 Dec 16', 0, 0, 7.27, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Courier Mail 14 Nov to 11 Dec 16', 0, 0, 27.27, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '24 The Australian Financial Review 14 Nov to 11 Dec 16', 0, 0, 87.27, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '8 Queensland Country Life 14 Nov to 11 Dec 16', 0, 0, 29.09, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 Balonne Beacon 14 Nov to 11 Dec 16', 0, 0, 5.45, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian 14 Nov to 11 Dec 16', 0, 0, 49.09, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 North Queensland Register 12 Dec 16 to 8 Jan 17', 0, 0, 5.45, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 Balonne Beacon 12 Dec 16 to 8 Jan 17', 0, 0, 4.09, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '6 Queensland Country Life 12 Dec 16 to 8 Jan 17', 0, 0, 21.82, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Queensland Times (Sat) 12 Dec 16 to 8 Jan 17', 0, 0, 3.64, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Longreach Leader 12 Dec 16 to 8 Jan 17', 0, 0, 3.00, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Courier Mail (Sat) 12 Dec 16 to 8 Jan 17', 0, 0, 4.55, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Chronicle (Sat) 12 Dec 16 to 8 Jan 17', 0, 0, 3.64, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Weekend Australian 12 Dec 16 to 8 Jan 17', 0, 0, 6.36, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '14 The Queensland Times 12 Dec 16 to 8 Jan 17', 0, 0, 19.09, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '14 The Courier Mail 12 Dec 16 to 8 Jan 17', 0, 0, 19.09, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '14 The Australian 12 Dec 16 to 8 Jan 17', 0, 0, 34.36, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '6 The Western Star 12 Dec 16 to 8 Jan 17', 0, 0, 8.18, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '15 The Australian Financial Review 12 Dec 16 to 8 Jan 17', 0, 0, 54.55, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '14 The Chronicle 12 Dec 16 to 8 Jan 17', 0, 0, 19.09, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Jan 17', 0, 0, 511.14, '21-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Jan 17', 0, 0, 42.53, '21-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Feb 17', 0, 0, 148.06, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Feb 17', 0, 0, 26.74, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Mar 17', 0, 0, 401.57, '21-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Mar 17', 0, 0, 31.91, '21-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 21 Dec 16', 0, 0, 524.78, '21-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 21 Dec 16', 0, 0, 40.90, '21-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 2 Jan 17', 0, 0, 28.66, '02-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 2 Jan 17', 0, 0, 68.18, '02-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 2 Feb 17', 0, 0, 38.39, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 2 Feb 17', 0, 0, 68.18, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 3 Mar 17', 0, 0, 31.62, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 3 Mar 17', 0, 0, 68.18, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Wellcamp to Sydney', 0, 0, 725.03, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Sydney to Canberra', 0, 0, 0, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '17 Feb 17 - Canberra to Sydney', 0, 0, 753.07, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '17 Feb 17 - Sydney to Wellcamp', 0, 0, 0, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Brisbane to Canberra', 0, 0, 497.34, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '1 Mar 17 - Canberra to Brisbane', 0, 0, 497.34, '01-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2017', '', '', '', '1 Oct 16 - Brisbane to Longreach', 0, 0, 88.00, '01-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2017', '', '', '', '2 Oct 16 - Longreach to Brisbane', 0, 0, 88.00, '02-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2017', '', '', '', '21 Oct 16 - Canberra to Sydney', 0, 0, 717.85, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2017', '', '', '', '21 Oct 16 - Sydney to Wellcamp', 0, 0, 0, '21-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Barry O''Sullivan', 'Senator', '', 'Queensland', 'The Nationals', 'Charter', 'Electorate', 'Before 1 January 2017', '', '', '', 'Hire car costs Cloncurry 1 Jun 16', 0, 0, 234.94, '01-Jun-2016', '');
