INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Parliamentary Political Party Meeting', 1, 276.00, 276.00, '05-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '06-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '12-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '26-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Economics - Reps', 2, 276.00, 552.00, '06-Mar-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'Before 1 January 2017', '', '', 'Melbourne', 'Economics - Reps', 1, 382.00, 382.00, '16-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Sydney to Canberra 5 Feb 17', 0, 0, 92.84, '05-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Canberra to Sydney 10 Feb 17', 0, 0, 92.84, '10-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Sydney to Canberra 12 Feb 17', 0, 0, 180.84, '12-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Canberra to Sydney 17 Feb 17', 0, 0, 72.24, '17-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Canberra to Sydney 17 Feb 17', 0, 0, 39.60, '17-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Sydney to Canberra 26 Feb 17', 0, 0, 92.84, '26-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Canberra to Sydney 3 Mar 17', 0, 0, 92.84, '03-Mar-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Sydney to Canberra 6 Mar 17', 0, 0, 92.84, '06-Mar-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Canberra to Sydney 8 Mar 17', 0, 0, 92.84, '08-Mar-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 25134.27, '01-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 799.51, '01-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 236.19, '27-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 23.39, '27-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 607.78, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Feb to 28 Feb 17', 0, 0, 693.61, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Reimbursement of price cap overspend 28 May to 27 Jun 16', 0, 0, -326.58, '27-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Reimbursement of price cap overspend 28 Jun to 30 Jun 16', 0, 0, -122.62, '30-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Reimbursement of price cap overspend 30 Jun 16', 0, 0, -649.86, '30-Jun-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 6.31, '27-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 345.56, '27-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 16', 0, 0, 303.95, '31-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 16.62, '28-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 423.99, '28-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution late payment fee Feb 17', 0, 0, 15.00, '01-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Feb to 28 Feb 17', 0, 0, -45.45, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Feb to 28 Feb 17', 0, 0, 1825.49, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 1014 rental 1 Apr 17 to 31 Mar 18', 0, 0, 169.09, '01-Apr-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Nov to 30 Nov 16', 0, 0, 18.82, '30-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '700 Printed items 10 Nov 16', 0, 0, 645.00, '10-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '2,500 Printed items 21 Nov 16', 0, 0, 1760.00, '21-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1,850 Printed items 30 Nov 16', 0, 0, 1350.00, '30-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution late payment fee Dec 16', 0, 0, 15.00, '01-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -45.45, '31-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 1833.55, '31-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 12 Jan 17', 0, 0, 223.46, '12-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 12 Jan 17', 0, 0, 46.65, '12-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 12 Feb 17', 0, 0, 505.41, '12-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 12 Feb 17', 0, 0, 48.46, '12-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 9 Dec 16', 0, 0, 252.44, '09-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 9 Dec 16', 0, 0, 46.59, '09-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 1 Jan 17', 0, 0, 72.68, '01-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 5 Jan 17', 0, 0, 32.29, '05-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 1 Feb 17', 0, 0, 72.68, '01-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 8 Feb 17', 0, 0, 31.77, '08-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 4 Mar 17', 0, 0, 72.68, '04-Mar-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Craig Kelly', 'Representative', 'Hughes', 'New South Wales', 'Liberal Party of Australia', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 9 Mar 17', 0, 0, 31.77, '09-Mar-2017');
