INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Devonport', 'Parliamentary Political Party Meeting', 2, 299.00, 598.00, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '05-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Griffith', 'Agriculture, Resources, Fisheries and Forestry', 2, 286.00, 572.00, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '06-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 224.73, '01-Jan-1900', 'OS Delegation - Accommodation and meals', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 430.00, '01-Jan-1900', 'OS Delegation - Equipment allowance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 2227.34, '01-Jan-1900', 'OS Delegation - Fares', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Overseas Travel', 'Overseas Travel', 'From 1 January 2017', '', '', '', '', 0, 0, 200.00, '01-Jan-1900', 'OS Delegation - Travel advance', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Jan 17 - Sydney to Melbourne', 0, 0, 1175.24, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Jan 17 - Melbourne to Devonport', 0, 0, 0, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '24 Jan 17 - Devonport to Melbourne', 0, 0, 1175.24, '24-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '24 Jan 17 - Melbourne to Sydney', 0, 0, 0, '24-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '5 Feb 17 - Newcastle to Canberra', 0, 0, 812.36, '05-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Feb 17 - Canberra to Newcastle', 0, 0, 0, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Orange to Sydney', 0, 0, 405.73, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Sydney to Canberra', 0, 0, 341.03, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Newcastle to Canberra', 0, 0, 30.54, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra to Newcastle', 0, 0, 369.25, '16-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Feb 17 - Newcastle to Sydney', 0, 0, 808.60, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Feb 17 - Sydney to Griffith', 0, 0, 0, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Griffith to Sydney', 0, 0, 445.00, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Newcastle to Canberra', 0, 0, 812.36, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra to Newcastle', 0, 0, 0, '02-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Sydney to Canberra', 0, 0, 354.03, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Newcastle to Canberra', 0, 0, 30.54, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '23 Mar 17 - Canberra to Newcastle', 0, 0, 378.51, '23-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 9 Jan to 8 Feb 17', 0, 0, 1851.66, '08-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 24 Jan to 22 Feb 17', 0, 0, 603.55, '22-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel interest fee 31 Jan to 15 Feb 17', 0, 0, 1.02, '15-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 9 Feb to 8 Mar 17', 0, 0, 1851.66, '08-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 3 Nov to 25 Nov 16', 0, 0, 306.44, '25-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Accident excess 6 Nov 16', 0, 0, 500.00, '06-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Loan car costs 6 Nov 16', 0, 0, 197.76, '06-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 9 Nov to 8 Dec 16', 0, 0, 1851.66, '08-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 2 Dec to 14 Dec 16', 0, 0, 226.57, '14-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 9 Dec 16 to 8 Jan 17', 0, 0, 1851.66, '09-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 30 Dec 16 to 14 Jan 17', 0, 0, 254.53, '30-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Jan 17 - Sydney', 0, 0, 283.20, '14-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Jan 17 - Sydney', 0, 0, 273.31, '20-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Jan 17 - Sydney', 0, 0, 267.81, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Feb 17 - Sydney', 0, 0, 107.10, '05-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Feb 17 - Sydney', 0, 0, 125.10, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Sydney', 0, 0, 104.25, '16-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Feb 17 - Sydney', 0, 0, 83.40, '19-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Feb 17 - Sydney', 0, 0, 268.35, '21-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Sydney', 0, 0, 137.70, '26-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra', 0, 0, 40.00, '02-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Mar 17 - Canberra', 0, 0, 78.60, '19-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '22 Jan 17', 0, 0, 38.35, '22-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '9 Feb 17', 0, 0, 9.78, '09-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Other Car Costs', 'From 1 January 2017', '', '', '', 'Taxi 7 Feb 17', 0, 0, 46.16, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Other Car Costs', 'Before 1 January 2017', '', '', '', 'Toll charge 31 Dec 16', 0, 0, 15.35, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 28683.36, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 3425.59, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 130.77, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Jan to 23 Feb 17', 0, 0, 44.92, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Jan to 23 Feb 17', 0, 0, 22.29, '23-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 288.00, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Feb to 28 Feb 17', 0, 0, 1848.60, '28-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 50.76, '30-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Nov to 23 Dec 16', 0, 0, 5.59, '23-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Nov to 23 Dec 16', 0, 0, 34.02, '23-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 17.44, '24-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 24 Dec 16 to 23 Jan 17', 0, 0, 104.90, '24-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 2357.98, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution late payment fee Jan 17', 0, 0, 15.00, '01-Jan-1900', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 25 Jan 17', 0, 0, 268.18, '25-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 25 Jan 17', 0, 0, 268.18, '25-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 31 Jan 17', 0, 0, 460.90, '31-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 156 rental 1 Apr 17 to 31 Mar 18', 0, 0, 271.82, '01-Apr-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 15 Sep 16', 0, 0, 30.03, '15-Sep-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 20 Sep 16', 0, 0, 60.00, '20-Sep-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 30 Sep 16', 0, 0, 15.03, '30-Sep-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Printing 5 Oct 16', 0, 0, 350.00, '05-Oct-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 31 Oct 16', 0, 0, 171.05, '31-Oct-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 10 Nov 16', 0, 0, 296.17, '10-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '800 Printed items 15 Nov 16', 0, 0, 2273.00, '15-Nov-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 972.91, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -22.73, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Printing 14 Dec 16', 0, 0, 150.00, '14-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 14 Dec 16', 0, 0, 268.18, '14-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 15 Dec 16', 0, 0, 268.18, '15-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 16 Dec 16', 0, 0, 268.18, '16-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 16 Dec 16', 0, 0, 440.91, '16-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 21 Dec 16', 0, 0, 268.18, '21-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '100 Printed items 22 Dec 16', 0, 0, 129.00, '22-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 22 Dec 16', 0, 0, 156.36, '22-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 22 Dec 16', 0, 0, 312.73, '22-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 22 Dec 16', 0, 0, 268.18, '22-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 23 Dec 16', 0, 0, 268.18, '23-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 The Land 1 Jan to 28 Jan 17', 0, 0, 10.91, '28-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '3 The Newcastle Herald (Sat) 1 Jan to 28 Jan 17', 0, 0, 6.00, '28-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '6 The Maitland Mercury 1 Jan to 28 Jan 17', 0, 0, 8.73, '28-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 1 Jan to 28 Jan 17', 0, 0, 1.00, '28-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '19 The Newcastle Herald 1 Jan to 28 Jan 17', 0, 0, 27.64, '28-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Newcastle Herald (digital) 28 Jan 17', 0, 0, 13.76, '28-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Newcastle Herald (digital) 29 Jan 17', 0, 0, 13.76, '29-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Newcastle Herald (digital) 14 Feb to 13 Mar 17', 0, 0, 13.76, '13-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '8 The Sydney Morning Herald 26 Sep to 30 Oct 16', 0, 0, 20.36, '30-Oct-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '8 The Australian 26 Sep to 30 Oct 16', 0, 0, 19.64, '30-Oct-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '25 The Newcastle Herald 31 Oct to 4 Dec 16', 0, 0, 36.36, '04-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '5 The Newcastle Herald (Sat) 31 Oct to 4 Dec 16', 0, 0, 10.00, '04-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 31 Oct to 4 Dec 16', 0, 0, 8.41, '04-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Newcastle Herald (Sat) 4 Dec to 31 Dec 16', 0, 0, 4.00, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 4 Dec to 31 Dec 16', 0, 0, 1.00, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Land 4 Dec to 31 Dec 16', 0, 0, 14.55, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '14 The Newcastle Herald 4 Dec to 31 Dec 16', 0, 0, 20.36, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '8 The Maitland Mercury 4 Dec to 31 Dec 16', 0, 0, 11.64, '31-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 5 Dec to 25 Dec 16', 0, 0, 5.05, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '5 The Newcastle Herald (Sat) 5 Dec to 25 Dec 16', 0, 0, 6.00, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '15 The Newcastle Herald 5 Dec to 25 Dec 16', 0, 0, 21.82, '25-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 26 Dec 16 to 29 Jan 17', 0, 0, 6.14, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Newcastle Herald (Sat) 26 Dec 16 to 29 Jan 17', 0, 0, 6.00, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 The Newcastle Herald 26 Dec 16 to 29 Jan 17', 0, 0, 27.64, '26-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 12 Jan 17', 0, 0, 295.69, '12-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 12 Jan 17', 0, 0, 61.59, '12-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 12 Feb 17', 0, 0, 378.83, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 12 Feb 17', 0, 0, 66.08, '12-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 9 Dec 16', 0, 0, 421.65, '09-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 9 Dec 16', 0, 0, 66.22, '09-Dec-2016', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 1 Jan 17', 0, 0, 154.54, '01-Jan-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 1 Feb 17', 0, 0, 145.45, '01-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 4 Mar 17', 0, 0, 218.17, '04-Mar-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '5 Feb 17 - Newcastle to Canberra', 0, 0, 812.36, '05-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'From 1 January 2017', '', '', '', '7 Feb 17 - Canberra to Newcastle', 0, 0, 0, '07-Feb-2017', '', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Type, Notes)
VALUES ('Meryl Swanson', 'Representative', 'Paterson', 'New South Wales', 'Australian Labor Party', 'Family Travel Costs', 'Family Traveller COMCAR', 'Before 1 January 2017', '', '', '', '28 Nov 16 - Sydney', 0, 0, 97.30, '28-Nov-2016', '', '');
