INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '05-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '12-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '26-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Wombarra to Canberra 5 Feb 17', 0, 0, 143.88, '05-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Wombarra to Canberra 5 Feb 17', 0, 0, 18.32, '05-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Canberra to Wombarra 10 Feb 17', 0, 0, 91.20, '10-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Wombarra to Canberra 12 Feb 17', 0, 0, 91.20, '12-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Canberra to Wombarra 16 Feb 17', 0, 0, 91.20, '16-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Wombarra to Canberra 26 Feb 17', 0, 0, 91.20, '26-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Car Costs', 'Private Vehicle Allowance', 'From 1 January 2017', '', '', '', 'Canberra to Wombarra 3 Mar 17', 0, 0, 91.20, '03-Mar-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 21749.80, '01-Jan-1900');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 1263.74, '01-Jan-1900');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 245.89, '31-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 4.64, '27-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 571.10, '27-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 3206.95, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Software reimbursement 2016/17', 0, 0, 1500.00, '01-Jan-1900');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Software reimbursement 2016/17', 0, 0, 933.64, '01-Jan-1900');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Nov to 30 Nov 16', 0, 0, 1093.02, '30-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Flags 1 Nov to 30 Nov 16', 0, 0, 2914.66, '30-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 459.33, '27-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 2.02, '27-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 16', 0, 0, 2669.32, '31-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 36.82, '28-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 36.16, '28-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 548.69, '31-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Printing 28 Feb 17', 0, 0, 150.00, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '2,100 Printed items 28 Feb 17', 0, 0, 1863.64, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '48,298 Printed items 28 Feb 17', 0, 0, 2594.55, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 28 Feb 17', 0, 0, 6871.49, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Printing 28 Feb 17', 0, 0, 150.00, '28-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 88 rental 1 Apr 17 to 31 Mar 18', 0, 0, 443.64, '01-Apr-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Oct to 31 Oct 16', 0, 0, 194.32, '31-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 11 Oct 16', 0, 0, 1858.91, '11-Oct-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-services 25 Nov 16', 0, 0, 187.00, '25-Nov-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 7 Dec 16', 0, 0, 1310.91, '07-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 14 Dec 16', 0, 0, 7599.85, '14-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '57,654 Printed items 14 Dec 16', 0, 0, 8136.36, '14-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 12 Jan 17', 0, 0, 322.76, '12-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 12 Jan 17', 0, 0, 38.25, '12-Jan-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 12 Feb 17', 0, 0, 348.82, '12-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 12 Feb 17', 0, 0, 37.98, '12-Feb-2017');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 9 Dec 16', 0, 0, 432.00, '09-Dec-2016');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date)
VALUES ('Mike Freelander', 'Representative', 'Macarthur', 'New South Wales', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 9 Dec 16', 0, 0, 38.37, '09-Dec-2016');
