INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '6 Feb 17 - Adelaide to Canberra', 0, 0, 491.54, '06-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Feb 17 - Canberra to Adelaide', 0, 0, 491.54, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Adelaide to Canberra', 0, 0, 491.54, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra to Adelaide', 0, 0, 491.54, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Adelaide to Melbourne', 0, 0, 450.42, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Melbourne to Albury', 0, 0, 385.86, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Albury to Melbourne', 0, 0, 385.86, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Melbourne to Adelaide', 0, 0, 450.42, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Adelaide to Canberra', 0, 0, 510.48, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Mar 17 - Canberra to Adelaide', 0, 0, 510.48, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Mar 17 - Adelaide to Sydney', 0, 0, 573.24, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Mar 17 - Sydney to Adelaide', 0, 0, 573.24, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '15 Mar 17 - Adelaide to Kingscote', 0, 0, 327.04, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Mar 17 - Kingscote to Adelaide', 0, 0, 327.04, '16-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Adelaide to Canberra', 0, 0, 510.48, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '12 Nov 16 - Cape Jervis to Penneshaw', 0, 0, 260.21, '12-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '14 Nov 16 - Adelaide to Kingscote', 0, 0, 257.63, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '15 Nov 16 - Kingscote to Adelaide', 0, 0, 0, '15-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 1 Jan to 28 Jan 17', 0, 0, 420.15, '28-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 20 Jan to 19 Feb 17', 0, 0, 990.64, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 2 Dec to 28 Dec 16', 0, 0, 587.40, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 20 Dec 16 to 19 Jan 17', 0, 0, 990.64, '20-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 27 Dec to 31 Dec 16', 0, 0, 25.01, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '16 Feb 17', 0, 0, 22.93, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '16 Feb 17', 0, 0, 22.25, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'From 1 January 2017', '', '', '', '21 Feb 17', 0, 0, 16.59, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'Before 1 January 2017', '', '', '', '5 Dec 16', 0, 0, 24.26, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'Before 1 January 2017', '', '', '', '5 Dec 16', 0, 0, 35.87, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'Before 1 January 2017', '', '', '', '5 Dec 16', 0, 0, 14.67, '05-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'Before 1 January 2017', '', '', '', '6 Dec 16', 0, 0, 11.32, '06-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'Before 1 January 2017', '', '', '', '6 Dec 16', 0, 0, 8.44, '06-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Cabcharge', 'Before 1 January 2017', '', '', '', '7 Dec 16', 0, 0, 10.17, '07-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'From 1 January 2017', '', '', '', 'Albury 22 Feb 17', 0, 0, 67.42, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Other Car Costs', 'Before 1 January 2017', '', '', '', 'Taxi 30 Aug 16', 0, 0, 12.90, '30-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Parking', 'Before 1 January 2017', '', '', '', 'Parking between 27 Jul and 28 Jul 16', 0, 0, 56.36, '28-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Car Costs', 'Parking', 'Before 1 January 2017', '', '', '', 'Parking 27 Oct 16', 0, 0, 34.55, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 17426.50, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 3630.38, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 197.93, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 10.13, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 182.65, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 708.32, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 130.39, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 32.36, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 16', 0, 0, 42.31, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Flags 1 Dec to 31 Dec 16', 0, 0, 707.70, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 190.73, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 8.44, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 1542.00, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'e-material 8 Jan 17', 0, 0, 505.68, '08-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 11 Jan 17', 0, 0, 271.82, '11-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 18 Jan 17', 0, 0, 409.09, '18-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 19 Jan 17', 0, 0, 634.25, '19-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 26 Jan 17', 0, 0, 78.55, '26-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'e-material 8 Feb 17', 0, 0, 3789.01, '08-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1,250 Personalised letterhead stationery 8 Feb 17', 0, 0, 220.00, '08-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '500 Printed items 8 Feb 17', 0, 0, 250.00, '08-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '500 Personalised letterhead stationery 8 Feb 17', 0, 0, 240.00, '08-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 9 Feb 17', 0, 0, 271.82, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '4,000 Personalised letterhead stationery 14 Feb 17', 0, 0, 800.00, '14-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '2,000 Personalised letterhead stationery 14 Feb 17', 0, 0, 420.00, '14-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 23 Feb 17', 0, 0, 317.12, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '19,000 Personalised letterhead stationery 2 Mar 17', 0, 0, 2430.00, '02-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 9 Mar 17', 0, 0, 271.82, '09-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 14 Mar 17', 0, 0, 50.00, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '62,145 Printed items 14 Mar 17', 0, 0, 10500.00, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '2 Printed items 9 Sep 16', 0, 0, 540.00, '09-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 29 Sep 16', 0, 0, 104.00, '29-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-design 5 Oct 16', 0, 0, 960.00, '05-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-services 10 Oct 16 to 10 Oct 18', 0, 0, 22.98, '10-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-services 7 Nov 16', 0, 0, 19.95, '07-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 10 Nov 16', 0, 0, 100.00, '10-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 14 Nov 16', 0, 0, 488.08, '14-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 129.32, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 8 Dec 16', 0, 0, 495.46, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 15 Dec 16', 0, 0, 104.00, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 15 Dec 16', 0, 0, 317.12, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 22 Dec 16', 0, 0, 137.78, '22-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Southern Argus 30 Jan to 26 Feb 17', 0, 0, 4.73, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Advertiser 30 Jan to 26 Feb 17', 0, 0, 27.27, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian 30 Jan to 26 Feb 17', 0, 0, 51.82, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian Financial Review 30 Jan to 26 Feb 17', 0, 0, 72.73, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Courier 30 Jan to 26 Feb 17', 0, 0, 5.45, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 The Victor Harbor Times 30 Jan to 26 Feb 17', 0, 0, 6.55, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '4 Stock Journal 30 Jan to 26 Feb 17', 0, 0, 13.09, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The Australian Financial Review 6 Feb to 5 Mar 17', 0, 0, 40.00, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The Australian 6 Feb to 5 Mar 17', 0, 0, 29.18, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Australian 28 Nov 16 to 1 Jan 17', 0, 0, 9.82, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Australian Financial Review 28 Nov 16 to 1 Jan 17', 0, 0, 14.55, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Courier 28 Nov to 25 Dec 16', 0, 0, 5.45, '25-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Advertiser 28 Nov to 25 Dec 16', 0, 0, 27.27, '25-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 Stock Journal 28 Nov to 25 Dec 16', 0, 0, 13.09, '25-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Victor Harbor Times 28 Nov to 25 Dec 16', 0, 0, 6.55, '25-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 The Australian Financial Review 28 Nov to 25 Dec 16', 0, 0, 69.09, '25-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Southern Argus 28 Nov to 25 Dec 16', 0, 0, 4.73, '25-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian 28 Nov to 25 Dec 16', 0, 0, 49.09, '25-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 The Advertiser 26 Dec 16 to 29 Jan 17', 0, 0, 25.91, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 Stock Journal 26 Dec 16 to 29 Jan 17', 0, 0, 13.09, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '2 The Courier 26 Dec 16 to 29 Jan 17', 0, 0, 2.73, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Victor Harbor Times 26 Dec 16 to 29 Jan 17', 0, 0, 4.91, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '3 The Southern Argus 26 Dec 16 to 29 Jan 17', 0, 0, 3.55, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '18 The Australian Financial Review 26 Dec 16 to 29 Jan 17', 0, 0, 65.45, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '19 The Australian 26 Dec 16 to 29 Jan 17', 0, 0, 46.64, '26-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 6 Jan 17', 0, 0, 1287.08, '06-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 6 Jan 17', 0, 0, 243.74, '06-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2017', '', '', '', '12 Nov 16 - Cape Jervis to Penneshaw', 0, 0, 90.29, '12-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Rebekha Sharkie', 'Representative', 'Mayo', 'South Australia', 'Nick Xenophon Team', 'Family Travel Costs', 'Family Traveller Domestic Scheduled Fares', 'Before 1 January 2017', '', '', '', '12 Nov 16 - Penneshaw to Cape Jervis', 0, 0, 0, '12-Nov-2016', '');
