INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 4, 276.00, 1104.00, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Rockhampton', 'Shadow Parliamentary Secretary - Official Business', 1, 286.00, 286.00, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Melbourne', 'Corporations and Financial Services', 1, 382.00, 382.00, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Shadow Parliamentary Secretary - Official Business', 1, 400.00, 400.00, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Melbourne', 'Education and Employment - Reps', 1, 382.00, 382.00, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Shadow Parliamentary Secretary - Official Business', 1, 400.00, 400.00, '16-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 1, 276.00, 276.00, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Sydney', 'Electorate Business', 1, 400.00, 400.00, '20-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 3, 276.00, 828.00, '21-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '30 Jan 17 - Brisbane to Canberra', 0, 0, 739.64, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '31 Jan 17 - Canberra to Brisbane', 0, 0, 478.43, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '5 Feb 17 - Brisbane to Canberra', 0, 0, 799.62, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '9 Feb 17 - Canberra to Brisbane', 0, 0, 799.62, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Brisbane to Canberra', 0, 0, 799.62, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra to Brisbane', 0, 0, 1109.07, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Feb 17 - Brisbane to Rockhampton', 0, 0, 0, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Feb 17 - Rockhampton to Brisbane', 0, 0, 314.98, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Feb 17 - Brisbane to Melbourne', 0, 0, 1184.42, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '22 Feb 17 - Melbourne to Brisbane', 0, 0, 1023.41, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Coolangatta to Canberra', 0, 0, 643.61, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra to Brisbane', 0, 0, 839.17, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '4 Mar 17 - Brisbane to Sydney', 0, 0, 884.56, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '5 Mar 17 - Sydney to Brisbane', 0, 0, 884.56, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Mar 17 - Brisbane to Sydney', 0, 0, 1533.68, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '14 Mar 17 - Sydney to Melbourne', 0, 0, 0, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne to Brisbane', 0, 0, 1023.41, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '16 Mar 17 - Brisbane to Sydney', 0, 0, 768.67, '16-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Mar 17 - Sydney to Brisbane', 0, 0, 768.67, '17-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Brisbane to Canberra', 0, 0, 839.17, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Mar 17 - Canberra to Sydney', 0, 0, 121.30, '20-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '21 Mar 17 - Sydney to Canberra', 0, 0, 354.03, '21-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '24 Mar 17 - Canberra to Brisbane', 0, 0, 739.64, '24-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '8 Dec 16 - Brisbane to Sydney', 0, 0, 755.95, '08-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '9 Dec 16 - Sydney to Brisbane', 0, 0, 755.95, '09-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '13 Dec 16 - Brisbane to Canberra', 0, 0, 799.62, '13-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '14 Dec 16 - Canberra to Melbourne', 0, 0, 416.12, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'Before 1 January 2017', '', '', '', '15 Dec 16 - Melbourne to Brisbane', 0, 0, 1023.41, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Fuel 9 Jan 17', 0, 0, 58.64, '09-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 24 Jan to 23 Feb 17', 0, 0, 695.22, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'From 1 January 2017', '', '', '', 'Lease 24 Feb to 23 Mar 17', 0, 0, 695.22, '23-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 24 Nov to 23 Dec 16', 0, 0, 695.22, '23-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Fuel 4 Dec 16', 0, 0, 41.51, '04-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Private-Plated Vehicle', 'Before 1 January 2017', '', '', '', 'Lease 24 Dec 16 to 23 Jan 17', 0, 0, 695.22, '24-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Jan 17 - Brisbane', 0, 0, 83.00, '14-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Jan 17 - Brisbane', 0, 0, 88.60, '22-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Jan 17 - Brisbane', 0, 0, 44.40, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '30 Jan 17 - Canberra', 0, 0, 41.80, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '31 Jan 17 - Canberra', 0, 0, 40.00, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '31 Jan 17 - Brisbane', 0, 0, 40.00, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Feb 17 - Brisbane', 0, 0, 83.00, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Feb 17 - Canberra', 0, 0, 80.40, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '9 Feb 17 - Brisbane', 0, 0, 51.10, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Brisbane', 0, 0, 83.00, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Canberra', 0, 0, 40.00, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Brisbane', 0, 0, 62.48, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Brisbane', 0, 0, 59.48, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '16 Feb 17 - Brisbane', 0, 0, 59.48, '16-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Brisbane', 0, 0, 121.96, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Brisbane', 0, 0, 50.00, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '22 Feb 17 - Brisbane', 0, 0, 50.00, '22-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Brisbane', 0, 0, 74.00, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Canberra', 0, 0, 80.40, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra', 0, 0, 40.00, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Brisbane', 0, 0, 50.05, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Mar 17 - Brisbane', 0, 0, 83.00, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Mar 17 - Sydney', 0, 0, 88.60, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Mar 17 - Sydney', 0, 0, 78.60, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '4 Mar 17 - Sydney', 0, 0, 78.60, '04-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Mar 17 - Sydney', 0, 0, 78.60, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Mar 17 - Brisbane', 0, 0, 88.80, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Mar 17 - Brisbane', 0, 0, 45.00, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Mar 17 - Sydney', 0, 0, 43.80, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Mar 17 - Sydney', 0, 0, 40.00, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '14 Mar 17 - Melbourne', 0, 0, 59.22, '14-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne', 0, 0, 40.00, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Melbourne', 0, 0, 68.59, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '15 Mar 17 - Brisbane', 0, 0, 45.00, '15-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Mar 17 - Sydney', 0, 0, 40.00, '17-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Mar 17 - Sydney', 0, 0, 118.52, '17-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Mar 17 - Brisbane', 0, 0, 83.00, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Mar 17 - Canberra', 0, 0, 40.00, '20-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Mar 17 - Sydney', 0, 0, 43.80, '20-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Mar 17 - Sydney', 0, 0, 40.00, '20-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '21 Mar 17 - Sydney', 0, 0, 40.00, '21-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Mar 17 - Canberra', 0, 0, 43.23, '24-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Mar 17 - Brisbane', 0, 0, 50.20, '24-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Parking', 'From 1 January 2017', '', '', '', 'Parking between 16 Mar and 17 Mar 17', 0, 0, 66.36, '17-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'Before 1 January 2017', '', '', '', '16 Dec 16', 0, 0, 29.16, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Car Costs', 'Cabcharge', 'Before 1 January 2017', '', '', '', '16 Dec 16', 0, 0, 28.66, '16-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 29889.84, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 814.51, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 194.72, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Jan to 31 Jan 17', 0, 0, 263.20, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 3.90, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 210.36, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 352.67, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 0.84, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 0.67, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 62.12, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Jan to 31 Jan 17', 0, 0, -20.45, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution late payment fee Jan 17', 0, 0, 15.00, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Jan to 31 Jan 17', 0, 0, 830.65, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 7 Jan 17', 0, 0, 130.00, '07-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 20 Jan 17', 0, 0, 323.64, '20-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 30 Jan 17', 0, 0, 400.00, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '5,400 Printed items 30 Jan 17', 0, 0, 440.00, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Printing 30 Jan 17', 0, 0, 375.00, '30-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 31 Jan 17', 0, 0, 225.00, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 31 Jan 17', 0, 0, 299.00, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Feb to 28 Feb 17', 0, 0, -13.64, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Feb to 28 Feb 17', 0, 0, 1276.22, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 9 Feb 17', 0, 0, 400.00, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Printing 9 Feb 17', 0, 0, 442.50, '09-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 13 Feb 17', 0, 0, 344.00, '13-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '4,300 Printed items 13 Feb 17', 0, 0, 400.00, '13-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 20 Feb 17', 0, 0, 1500.00, '20-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 23 Feb 17', 0, 0, 725.40, '23-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', '1 Printed item 27 Feb 17', 0, 0, 9080.00, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Printing 27 Feb 17', 0, 0, 622.50, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 8 Mar 17', 0, 0, 400.00, '08-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'e-material 15 Mar to 17 Mar 17', 0, 0, 320.22, '17-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'e-material 17 Mar to 18 Mar 17', 0, 0, 332.63, '18-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'e-material 17 Mar to 18 Mar 17', 0, 0, 617.91, '18-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 476 rental 1 Apr 17 to 31 Mar 18', 0, 0, 169.09, '01-Apr-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 17 Aug to 25 Aug 16', 0, 0, 46.00, '25-Aug-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 2 Sep to 5 Sep 16', 0, 0, 26.00, '05-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 13 Oct to 27 Oct 16', 0, 0, 238.92, '27-Oct-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 14 Nov to 17 Nov 16', 0, 0, 86.61, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 14 Nov to 17 Nov 16', 0, 0, 12.31, '17-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -34.09, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 5934.95, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 14 Dec 16', 0, 0, 181.82, '14-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '1 Printed item 15 Dec 16', 0, 0, 181.82, '15-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 22 Dec to 28 Dec 16', 0, 0, 143.46, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'e-material 27 Dec to 28 Dec 16', 0, 0, 54.54, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '10 The Courier Mail 2 Jan to 29 Jan 17', 0, 0, 13.64, '29-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '9 The Australian Financial Review 2 Jan to 29 Jan 17', 0, 0, 0, '29-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '', 0, 0, 32.73, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 2 Jan to 29 Jan 17', 0, 0, 0, '29-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '', 0, 0, 5.54, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '10 The Australian 2 Jan to 29 Jan 17', 0, 0, 24.55, '29-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 The Great Divide 9 Jan 17', 0, 0, 0, '09-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '', 0, 0, 24.55, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '1 Student Equity in Australian Higher Education: Twenty-Five Years of Fair Chance For All 25 Jan 17', 0, 0, 186.65, '25-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian Financial Review 30 Jan to 26 Feb 17', 0, 0, 72.73, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Australian 30 Jan to 26 Feb 17', 0, 0, 0, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '', 0, 0, 51.82, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '20 The Courier Mail 30 Jan to 26 Feb 17', 0, 0, 27.27, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 30 Jan to 26 Feb 17', 0, 0, 0, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '', 0, 0, 11.45, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The Courier Mail 6 Feb to 5 Mar 17', 0, 0, 19.00, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Courier Mail 28 Nov 16 to 1 Jan 17', 0, 0, 6.91, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Courier Mail 28 Nov 16 to 1 Jan 17', 0, 0, 27.27, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian 28 Nov 16 to 1 Jan 17', 0, 0, 49.09, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian Financial Review 28 Nov 16 to 1 Jan 17', 0, 0, 72.73, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 28 Nov 16 to 1 Jan 17', 0, 0, 11.45, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Jan 17', 0, 0, 186.94, '21-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Jan 17', 0, 0, 39.78, '21-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Feb 17', 0, 0, 290.79, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Feb 17', 0, 0, 38.82, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 21 Mar 17', 0, 0, 272.44, '21-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 21 Mar 17', 0, 0, 38.32, '21-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office phones 21 Dec 16', 0, 0, 275.80, '21-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'Before 1 January 2017', '', '', '', 'Office fax 21 Dec 16', 0, 0, 37.95, '21-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 24 Jan 17', 0, 0, 38.41, '24-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 24 Jan 17', 0, 0, 99.95, '24-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 21 Feb 17', 0, 0, 51.14, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 21 Feb 17', 0, 0, 99.95, '21-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 23 Mar 17', 0, 0, 38.41, '23-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 23 Mar 17', 0, 0, 99.95, '23-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'Before 1 January 2017', '', '', '', 'Residential phones 21 Dec 16', 0, 0, 38.41, '21-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Terri Butler', 'Representative', 'Griffith', 'Queensland', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'Before 1 January 2017', '', '', '', 'Dedicated data line 21 Dec 16', 0, 0, 99.95, '21-Dec-2016', '');
