INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Melbourne', 'Australian Commission for Law Enforcement Integrity', 2, 382.00, 764.00, '29-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Darwin', 'Australian Commission for Law Enforcement Integrity', 1, 268.00, 268.00, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Perth', 'Public Works', 1, 399.00, 399.00, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Melbourne', 'Public Works', 1, 382.00, 382.00, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Travelling Allowance', 'Parliamentary Travelling Allowance', 'From 1 January 2017', '', '', 'Canberra', 'Sittings of Parliament', 5, 276.00, 1380.00, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '29 Jan 17 - Adelaide to Melbourne', 0, 0, 154.98, '29-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '31 Jan 17 - Melbourne to Cairns', 0, 0, 328.05, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '31 Jan 17 - Cairns to Darwin', 0, 0, 264.65, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Feb 17 - Darwin to Sydney', 0, 0, 483.89, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '1 Feb 17 - Sydney to Adelaide', 0, 0, 0, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide to Perth', 0, 0, 817.83, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Feb 17 - Perth to Adelaide', 0, 0, 304.63, '03-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '5 Feb 17 - Adelaide to Canberra', 0, 0, 491.54, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Canberra to Sydney', 0, 0, 327.81, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '10 Feb 17 - Sydney to Adelaide', 0, 0, 0, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '12 Feb 17 - Adelaide to Canberra', 0, 0, 491.54, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Feb 17 - Canberra to Sydney', 0, 0, 327.88, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '17 Feb 17 - Sydney to Adelaide', 0, 0, 0, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Feb 17 - Adelaide to Melbourne', 0, 0, 190.48, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '20 Feb 17 - Melbourne to Adelaide', 0, 0, 190.48, '20-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '26 Feb 17 - Adelaide to Canberra', 0, 0, 510.48, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra to Adelaide', 0, 0, 202.81, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Domestic Scheduled Fares', 'Fares', 'From 1 January 2017', '', '', '', '19 Mar 17 - Adelaide to Canberra', 0, 0, 491.56, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '29 Jan 17 - Adelaide', 0, 0, 78.60, '29-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '29 Jan 17 - Melbourne', 0, 0, 85.00, '29-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '31 Jan 17 - Melbourne', 0, 0, 42.20, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '31 Jan 17 - Darwin', 0, 0, 40.00, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '1 Feb 17 - Adelaide', 0, 0, 41.80, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Adelaide', 0, 0, 55.02, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '2 Feb 17 - Perth', 0, 0, 40.00, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Perth', 0, 0, 40.00, '03-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Feb 17 - Adelaide', 0, 0, 43.72, '03-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '5 Feb 17 - Adelaide', 0, 0, 78.60, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Canberra', 0, 0, 40.00, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '10 Feb 17 - Adelaide', 0, 0, 45.03, '10-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '12 Feb 17 - Adelaide', 0, 0, 78.60, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Canberra', 0, 0, 40.00, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '17 Feb 17 - Adelaide', 0, 0, 52.89, '17-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Feb 17 - Adelaide', 0, 0, 78.60, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Feb 17 - Melbourne', 0, 0, 82.80, '19-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Feb 17 - Melbourne', 0, 0, 58.08, '20-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Feb 17 - Melbourne', 0, 0, 40.00, '20-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '20 Feb 17 - Adelaide', 0, 0, 50.27, '20-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Feb 17 - Adelaide', 0, 0, 78.60, '26-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Canberra', 0, 0, 40.00, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '3 Mar 17 - Adelaide', 0, 0, 48.96, '03-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '19 Mar 17 - Adelaide', 0, 0, 78.60, '19-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '24 Mar 17 - Adelaide', 0, 0, 52.89, '24-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Car Costs', 'COMCAR', 'From 1 January 2017', '', '', '', '26 Mar 17 - Adelaide', 0, 0, 78.60, '26-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'From 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 22295.64, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Facilities', 'Office Facilities', 'Before 1 January 2017', '', '', '', 'Aggregated Total', 0, 0, 1227.19, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Jan to 31 Jan 17', 0, 0, 56.39, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Jan to 31 Jan 17', 0, 0, 410.46, '31-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 18 Jan 17', 0, 0, 36.00, '18-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 18 Jan 17', 0, 0, 35.00, '18-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Jan to 27 Feb 17', 0, 0, 28.52, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Jan to 27 Feb 17', 0, 0, 40.82, '27-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Office requisites and stationery 1 Feb to 28 Feb 17', 0, 0, 12.36, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Flags 1 Feb to 28 Feb 17', 0, 0, 1390.25, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'From 1 January 2017', '', '', '', 'Water refills 2 Feb 17 to 1 Feb 18', 0, 0, 90.00, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Software reimbursement 2016/17', 0, 0, 1500.00, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Nov to 27 Dec 16', 0, 0, 28.94, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Nov to 27 Dec 16', 0, 0, 33.71, '27-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'Office requisites and stationery 1 Dec to 31 Dec 16', 0, 0, 1825.36, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Monochrome copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 28.39, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Office Consumables and Services', 'Before 1 January 2017', '', '', '', 'MFD Colour copy charge 28 Dec 16 to 27 Jan 17', 0, 0, 34.52, '28-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Web-services 1 Jan 17', 0, 0, 58.00, '01-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Web-services 1 Feb 17', 0, 0, 58.00, '01-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution credit 1 Feb to 28 Feb 17', 0, 0, -11.36, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Distribution 1 Feb to 28 Feb 17', 0, 0, 588.18, '28-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'Web-services 1 Mar to 31 Mar 17', 0, 0, 58.00, '31-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'From 1 January 2017', '', '', '', 'PO Box 775 rental 1 Apr 17 to 31 Mar 18', 0, 0, 271.82, '01-Apr-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Jul to 31 Jul 16', 0, 0, 15.95, '31-Jul-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution late payment fee Jul 16', 0, 0, 15.00, '01-Jan-1900', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-services 1 Sep 16', 0, 0, 58.00, '01-Sep-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '62,000 Personalised letterhead stationery 29 Nov 16', 0, 0, 1630.60, '29-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 30 Nov 16', 0, 0, 3850.00, '30-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution 1 Dec to 31 Dec 16', 0, 0, 8542.52, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Distribution credit 1 Dec to 31 Dec 16', 0, 0, -11.36, '31-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Web-services 1 Dec 16', 0, 0, 58.00, '01-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '62,000 Printed items 6 Dec 16', 0, 0, 7380.00, '06-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', '62,000 Printed items 6 Dec 16', 0, 0, 15195.45, '06-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Printing and Communications', 'Before 1 January 2017', '', '', '', 'Printing 6 Dec 16', 0, 0, 110.00, '06-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '10 The Weekend Australian 7 Jan to 17 Mar 17', 0, 0, 31.82, '17-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', 'Administrative fees 9 Jan to 5 Feb 17', 0, 0, 2.09, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '19 The Australian Financial Review 9 Jan to 5 Feb 17', 0, 0, 69.09, '05-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '50 The Advertiser 10 Jan to 20 Mar 17', 0, 0, 68.18, '20-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '50 The Australian 11 Jan to 21 Mar 17', 0, 0, 109.09, '21-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '40 The Advertiser, 8 The Advertiser (Sat) and 8 Sunday Mail 31 Jan to 10 Apr 17', 0, 0, 109.09, '10-Apr-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The Age 6 Feb to 5 Mar 17', 0, 0, 40.00, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'From 1 January 2017', '', '', '', '11 The Australian 6 Feb to 5 Mar 17', 0, 0, 29.18, '05-Mar-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 14 Nov to 11 Dec 16', 0, 0, 2.18, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '20 The Australian Financial Review 14 Nov to 11 Dec 16', 0, 0, 72.73, '11-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Australian 28 Nov 16 to 1 Jan 17', 0, 0, 9.82, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '4 The Age 28 Nov 16 to 1 Jan 17', 0, 0, 14.55, '28-Nov-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', 'Administrative fees 12 Dec 16 to 8 Jan 17', 0, 0, 1.45, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Office Administrative Costs', 'Publications', 'Before 1 January 2017', '', '', '', '13 The Australian Financial Review 12 Dec 16 to 8 Jan 17', 0, 0, 47.27, '12-Dec-2016', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office phones 6 Jan 17', 0, 0, 991.28, '06-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Usage', 'From 1 January 2017', '', '', '', 'Office fax 6 Jan 17', 0, 0, 171.56, '06-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 12 Jan 17', 0, 0, 36.32, '12-Jan-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Residential phones 2 Feb 17', 0, 0, 1005.94, '02-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 12 Feb 17', 0, 0, 36.32, '12-Feb-2017', '');
INSERT INTO Expense (Name, MemberType, Electorate, State, Party, Category, SubCategory, Period, DateFrom, DateTo, Location, Details, Nights, Rate, Amount, Date, Notes)
VALUES ('Tony Zappia', 'Representative', 'Makin', 'South Australia', 'Australian Labor Party', 'Telecommunications', 'Telecommunications - Residential - Official', 'From 1 January 2017', '', '', '', 'Dedicated data line 12 Mar 17', 0, 0, 36.32, '12-Mar-2017', '');
